// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_project;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * ProjectVersion.
 * Typed representation of the `ProjectVersion` API schema.
 */

public final class ProjectVersion {
    /**
     * Optional `boolean` value serialized in the `active` wire field.
     */
    @Nullable public Boolean active;
    /**
     * Optional `boolean` value serialized in the `isLatest` wire field.
     */
    @Nullable public Boolean isLatest;
    /**
     * Optional `uuid`-formatted value serialized in the `uuid` wire field.
     */
    @Nullable public String uuid;
    /**
     * Optional `string` value serialized in the `version` wire field.
     */
    @Nullable public String version;
    private ProjectVersion() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Boolean active;
        private Boolean isLatest;
        private String uuid;
        private String version;
        public Builder active(Boolean value) { this.active = value; return this; }
        public Builder isLatest(Boolean value) { this.isLatest = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public ProjectVersion build() {
            ProjectVersion result = new ProjectVersion();
            result.active = this.active;
            result.isLatest = this.isLatest;
            if (this.uuid != null) {
                Validation.validateUuid("uuid", this.uuid);
            }
            result.uuid = this.uuid;
            result.version = this.version;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ProjectVersion{"
            + "active=" + active
            + ", isLatest=" + isLatest
            + ", uuid=" + uuid
            + ", version=" + version
            + "}";
    }
}
