// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.violation;

import dependencytrackunofficialsdk.Validation;
import dependencytrackunofficialsdk.models.shared.Component;
import dependencytrackunofficialsdk.models.shared.Project;
import dependencytrackunofficialsdk.models.shared_policy.PolicyCondition;
import javax.annotation.Nullable;

/**
 * PolicyViolation.
 * Typed representation of the `PolicyViolation` API schema.
 */

public final class PolicyViolation {
    /**
     * UNIX epoch timestamp in milliseconds
     */
    public Long timestamp;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Optional object value serialized in the `analysis` wire field.
     */
    @Nullable public ViolationAnalysis analysis;
    /**
     * Optional object value serialized in the `component` wire field.
     */
    @Nullable public Component component;
    /**
     * Optional object value serialized in the `policyCondition` wire field.
     */
    @Nullable public PolicyCondition policyCondition;
    /**
     * Optional object value serialized in the `project` wire field.
     */
    @Nullable public Project project;
    /**
     * Optional `string` value serialized in the `text` wire field.
     */
    @Nullable public String text;
    /**
     * Optional enumerated value serialized in the `type` wire field.
     */
    @Nullable public PolicyViolationTypeEnum type;
    private PolicyViolation() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Long timestamp;
        private String uuid;
        private ViolationAnalysis analysis;
        private Component component;
        private PolicyCondition policyCondition;
        private Project project;
        private String text;
        private PolicyViolationTypeEnum type;
        public Builder timestamp(Long value) { this.timestamp = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder analysis(ViolationAnalysis value) { this.analysis = value; return this; }
        public Builder component(Component value) { this.component = value; return this; }
        public Builder policyCondition(PolicyCondition value) { this.policyCondition = value; return this; }
        public Builder project(Project value) { this.project = value; return this; }
        public Builder text(String value) { this.text = value; return this; }
        public Builder type(PolicyViolationTypeEnum value) { this.type = value; return this; }
        public PolicyViolation build() {
            PolicyViolation result = new PolicyViolation();
            Validation.validateRequired("timestamp", this.timestamp);
            result.timestamp = this.timestamp;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.analysis = this.analysis;
            result.component = this.component;
            result.policyCondition = this.policyCondition;
            result.project = this.project;
            if (this.text != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("text", this.text, __length); }
            }
            result.text = this.text;
            result.type = this.type;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "PolicyViolation{"
            + "timestamp=" + timestamp
            + ", uuid=" + uuid
            + ", analysis=" + analysis
            + ", component=" + component
            + ", policyCondition=" + policyCondition
            + ", project=" + project
            + ", text=" + text
            + ", type=" + type
            + "}";
    }
}
