// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.violation;

/**
 * Optional enumerated value serialized in the `violationAnalysisState` wire field.
 */
public final class ViolationAnalysisViolationAnalysisStateEnum {
    public static final ViolationAnalysisViolationAnalysisStateEnum APPROVED = new ViolationAnalysisViolationAnalysisStateEnum("APPROVED");
    public static final ViolationAnalysisViolationAnalysisStateEnum REJECTED = new ViolationAnalysisViolationAnalysisStateEnum("REJECTED");
    public static final ViolationAnalysisViolationAnalysisStateEnum NOT_SET = new ViolationAnalysisViolationAnalysisStateEnum("NOT_SET");
    private final String value;
    private ViolationAnalysisViolationAnalysisStateEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ViolationAnalysisViolationAnalysisStateEnum fromValue(String value) {
        if ("APPROVED".equals(value)) return APPROVED;
        if ("REJECTED".equals(value)) return REJECTED;
        if ("NOT_SET".equals(value)) return NOT_SET;
        return new ViolationAnalysisViolationAnalysisStateEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ViolationAnalysisViolationAnalysisStateEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
