// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.violationanalysis;

/**
 * The state of the analysis decision
 */
public final class ViolationAnalysisResponseAnalysisStateEnum {
    public static final ViolationAnalysisResponseAnalysisStateEnum APPROVED = new ViolationAnalysisResponseAnalysisStateEnum("APPROVED");
    public static final ViolationAnalysisResponseAnalysisStateEnum REJECTED = new ViolationAnalysisResponseAnalysisStateEnum("REJECTED");
    public static final ViolationAnalysisResponseAnalysisStateEnum NOT_SET = new ViolationAnalysisResponseAnalysisStateEnum("NOT_SET");
    private final String value;
    private ViolationAnalysisResponseAnalysisStateEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ViolationAnalysisResponseAnalysisStateEnum fromValue(String value) {
        if ("APPROVED".equals(value)) return APPROVED;
        if ("REJECTED".equals(value)) return REJECTED;
        if ("NOT_SET".equals(value)) return NOT_SET;
        return new ViolationAnalysisResponseAnalysisStateEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ViolationAnalysisResponseAnalysisStateEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
