// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.violationanalysis;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * ViolationAnalysisRequest.
 * Typed representation of the `ViolationAnalysisRequest` API schema.
 */

public final class ViolationAnalysisRequest {
    /**
     * Required `string` value serialized in the `component` wire field.
     */
    public String component;
    /**
     * Required `string` value serialized in the `policyViolation` wire field.
     */
    public String policyViolation;
    /**
     * Optional enumerated value serialized in the `analysisState` wire field.
     */
    @Nullable public ViolationAnalysisRequestAnalysisStateEnum analysisState;
    /**
     * Optional `string` value serialized in the `comment` wire field.
     */
    @Nullable public String comment;
    /**
     * Optional `boolean` value serialized in the `isSuppressed` wire field.
     */
    @Nullable public Boolean isSuppressed;
    /**
     * Optional `boolean` value serialized in the `suppressed` wire field.
     */
    @Nullable public Boolean suppressed;
    private ViolationAnalysisRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String component;
        private String policyViolation;
        private ViolationAnalysisRequestAnalysisStateEnum analysisState;
        private String comment;
        private Boolean isSuppressed;
        private Boolean suppressed;
        public Builder component(String value) { this.component = value; return this; }
        public Builder policyViolation(String value) { this.policyViolation = value; return this; }
        public Builder analysisState(ViolationAnalysisRequestAnalysisStateEnum value) { this.analysisState = value; return this; }
        public Builder comment(String value) { this.comment = value; return this; }
        public Builder isSuppressed(Boolean value) { this.isSuppressed = value; return this; }
        public Builder suppressed(Boolean value) { this.suppressed = value; return this; }
        public ViolationAnalysisRequest build() {
            ViolationAnalysisRequest result = new ViolationAnalysisRequest();
            Validation.validateRequired("component", this.component);
            Validation.validatePattern("component", this.component, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
            result.component = this.component;
            Validation.validateRequired("policyViolation", this.policyViolation);
            Validation.validatePattern("policyViolation", this.policyViolation, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
            result.policyViolation = this.policyViolation;
            result.analysisState = this.analysisState;
            result.comment = this.comment;
            result.isSuppressed = this.isSuppressed;
            result.suppressed = this.suppressed;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ViolationAnalysisRequest{"
            + "component=" + component
            + ", policyViolation=" + policyViolation
            + ", analysisState=" + analysisState
            + ", comment=" + comment
            + ", isSuppressed=" + isSuppressed
            + ", suppressed=" + suppressed
            + "}";
    }
}
