// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.user;

import dependencytrackunofficialsdk.Validation;
import java.util.List;

/**
 * TeamsSetRequest.
 * Typed representation of the `TeamsSetRequest` API schema.
 */

public final class TeamsSetRequest {
    /**
     * Required array value serialized in the `teams` wire field.
     */
    public List<String> teams;
    /**
     * Required `string` value serialized in the `username` wire field.
     */
    public String username;
    private TeamsSetRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private List<String> teams;
        private String username;
        public Builder teams(List<String> value) { this.teams = value; return this; }
        public Builder username(String value) { this.username = value; return this; }
        public TeamsSetRequest build() {
            TeamsSetRequest result = new TeamsSetRequest();
            Validation.validateRequired("teams", this.teams);
            result.teams = this.teams;
            Validation.validateRequired("username", this.username);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("username", this.username, __length); }
            result.username = this.username;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "TeamsSetRequest{"
            + "teams=" + teams
            + ", username=" + username
            + "}";
    }
}
