// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;

public class Badge {

    public static class GetProjectPolicyViolationsBadge1Request {

        private String name;
        private String version;

        private GetProjectPolicyViolationsBadge1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectPolicyViolationsBadge1Request request = new GetProjectPolicyViolationsBadge1Request();
            public Builder name(String val) { request.name = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public GetProjectPolicyViolationsBadge1Request build() { return request; }
        }
        public String getName() { return name; }
        public String getVersion() { return version; }
    }

    /**
     * Retrieves an SVG badge showing current policy violation metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectPolicyViolationsBadge1(SdkConfig.ClientConfig clientConfig, GetProjectPolicyViolationsBadge1Request request) {
        return getProjectPolicyViolationsBadge1(clientConfig, request, null);
    }

    /**
     * Retrieves an SVG badge showing current policy violation metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectPolicyViolationsBadge1(SdkConfig.ClientConfig clientConfig, GetProjectPolicyViolationsBadge1Request request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        String version = request.getVersion();

        return SdkClient.request(clientConfig, "GET", "/v1/badge/violations/project/" + SdkClient.encodePathSegment(name) + "/" + SdkClient.encodePathSegment(version) + "", null, null, null, new TypeReference<byte[]>(){}, "getProjectPolicyViolationsBadge1", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }


    public static class GetProjectPolicyViolationsBadgeRequest {

        private String uuid;

        private GetProjectPolicyViolationsBadgeRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectPolicyViolationsBadgeRequest request = new GetProjectPolicyViolationsBadgeRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetProjectPolicyViolationsBadgeRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Retrieves an SVG badge showing current policy violation metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectPolicyViolationsBadge(SdkConfig.ClientConfig clientConfig, GetProjectPolicyViolationsBadgeRequest request) {
        return getProjectPolicyViolationsBadge(clientConfig, request, null);
    }

    /**
     * Retrieves an SVG badge showing current policy violation metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectPolicyViolationsBadge(SdkConfig.ClientConfig clientConfig, GetProjectPolicyViolationsBadgeRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/badge/violations/project/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<byte[]>(){}, "getProjectPolicyViolationsBadge", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }


    public static class GetProjectVulnerabilitiesBadge1Request {

        private String name;
        private String version;

        private GetProjectVulnerabilitiesBadge1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectVulnerabilitiesBadge1Request request = new GetProjectVulnerabilitiesBadge1Request();
            public Builder name(String val) { request.name = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public GetProjectVulnerabilitiesBadge1Request build() { return request; }
        }
        public String getName() { return name; }
        public String getVersion() { return version; }
    }

    /**
     * Retrieves an SVG badge showing current vulnerability metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectVulnerabilitiesBadge1(SdkConfig.ClientConfig clientConfig, GetProjectVulnerabilitiesBadge1Request request) {
        return getProjectVulnerabilitiesBadge1(clientConfig, request, null);
    }

    /**
     * Retrieves an SVG badge showing current vulnerability metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectVulnerabilitiesBadge1(SdkConfig.ClientConfig clientConfig, GetProjectVulnerabilitiesBadge1Request request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        String version = request.getVersion();

        return SdkClient.request(clientConfig, "GET", "/v1/badge/vulns/project/" + SdkClient.encodePathSegment(name) + "/" + SdkClient.encodePathSegment(version) + "", null, null, null, new TypeReference<byte[]>(){}, "getProjectVulnerabilitiesBadge1", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }


    public static class GetProjectVulnerabilitiesBadgeRequest {

        private String uuid;

        private GetProjectVulnerabilitiesBadgeRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectVulnerabilitiesBadgeRequest request = new GetProjectVulnerabilitiesBadgeRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetProjectVulnerabilitiesBadgeRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Retrieves an SVG badge showing current vulnerability metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectVulnerabilitiesBadge(SdkConfig.ClientConfig clientConfig, GetProjectVulnerabilitiesBadgeRequest request) {
        return getProjectVulnerabilitiesBadge(clientConfig, request, null);
    }

    /**
     * Retrieves an SVG badge showing current vulnerability metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
     */
    public static byte[] getProjectVulnerabilitiesBadge(SdkConfig.ClientConfig clientConfig, GetProjectVulnerabilitiesBadgeRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/badge/vulns/project/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<byte[]>(){}, "getProjectVulnerabilitiesBadge", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }



}
