// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.shared.BomUploadResponse;
import dependencytrackunofficialsdk.models.shared.IsTokenBeingProcessedResponse;
import dependencytrackunofficialsdk.models.shared.Tag;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Bom {

    public static class UploadBomRequest {

        private Boolean autoCreate;
        private SdkClient.UploadFile bom;
        private Boolean isActive;
        private Boolean isLatest;
        private String parentName;
        private String parentUuid;
        private String parentVersion;
        private String project;
        private String projectName;
        private String projectTags;
        private String projectVersion;

        private UploadBomRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UploadBomRequest request = new UploadBomRequest();
            public Builder autoCreate(Boolean val) { request.autoCreate = val; return this; }
            public Builder bom(SdkClient.UploadFile val) { request.bom = val; return this; }
            public Builder isActive(Boolean val) { request.isActive = val; return this; }
            public Builder isLatest(Boolean val) { request.isLatest = val; return this; }
            public Builder parentName(String val) { request.parentName = val; return this; }
            public Builder parentUuid(String val) { request.parentUuid = val; return this; }
            public Builder parentVersion(String val) { request.parentVersion = val; return this; }
            public Builder project(String val) { request.project = val; return this; }
            public Builder projectName(String val) { request.projectName = val; return this; }
            public Builder projectTags(String val) { request.projectTags = val; return this; }
            public Builder projectVersion(String val) { request.projectVersion = val; return this; }
            public UploadBomRequest build() { return request; }
        }
        public Boolean getAutoCreate() { return autoCreate; }
        public SdkClient.UploadFile getBom() { return bom; }
        public Boolean getIsActive() { return isActive; }
        public Boolean getIsLatest() { return isLatest; }
        public String getParentName() { return parentName; }
        public String getParentUuid() { return parentUuid; }
        public String getParentVersion() { return parentVersion; }
        public String getProject() { return project; }
        public String getProjectName() { return projectName; }
        public String getProjectTags() { return projectTags; }
        public String getProjectVersion() { return projectVersion; }
    }

    /**
     * Uploads a CycloneDX bill of materials (BOM) and starts processing it for a project. Send the BOM as multipart form data; identify the project with `project`, or supply both `projectName` and `projectVersion`, and use `autoCreate` to create a project when needed. The response includes a token for checking processing progress; BOM uploads require the `BOM_UPLOAD` permission, and creating a project also requires one of the documented project-creation permissions.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM artifact may be supplied uncompressed or compressed. If the BOM is uncompressed, the supported MediaType is 'application/xml' or 'application/json'. If the BOM is compressed, the supported MediaType is 'application/gzip' or 'application/zstd' and must match the actual compression of the data. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. Requires permission BOM_UPLOAD
     */
    public static BomUploadResponse uploadBom(SdkConfig.ClientConfig clientConfig, UploadBomRequest request) {
        return uploadBom(clientConfig, request, null);
    }

    /**
     * Uploads a CycloneDX bill of materials (BOM) and starts processing it for a project. Send the BOM as multipart form data; identify the project with `project`, or supply both `projectName` and `projectVersion`, and use `autoCreate` to create a project when needed. The response includes a token for checking processing progress; BOM uploads require the `BOM_UPLOAD` permission, and creating a project also requires one of the documented project-creation permissions.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM artifact may be supplied uncompressed or compressed. If the BOM is uncompressed, the supported MediaType is 'application/xml' or 'application/json'. If the BOM is compressed, the supported MediaType is 'application/gzip' or 'application/zstd' and must match the actual compression of the data. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. Requires permission BOM_UPLOAD
     */
    public static BomUploadResponse uploadBom(SdkConfig.ClientConfig clientConfig, UploadBomRequest request, SdkConfig.RequestOptions options) {
        Boolean autoCreate = request.getAutoCreate();
        SdkClient.UploadFile bom = request.getBom();
        Boolean isActive = request.getIsActive();
        Boolean isLatest = request.getIsLatest();
        String parentName = request.getParentName();
        String parentUuid = request.getParentUuid();
        String parentVersion = request.getParentVersion();
        String project = request.getProject();
        String projectName = request.getProjectName();
        String projectTags = request.getProjectTags();
        String projectVersion = request.getProjectVersion();

        return SdkClient.request(clientConfig, "POST", "/v1/bom", null, SdkClient.q("autoCreate", SdkClient.omitIfNull(autoCreate), "bom", SdkClient.omitIfNull(bom), "isActive", SdkClient.omitIfNull(isActive), "isLatest", SdkClient.omitIfNull(isLatest), "parentName", SdkClient.omitIfNull(parentName), "parentUUID", SdkClient.omitIfNull(parentUuid), "parentVersion", SdkClient.omitIfNull(parentVersion), "project", SdkClient.omitIfNull(project), "projectName", SdkClient.omitIfNull(projectName), "projectTags", SdkClient.omitIfNull(projectTags), "projectVersion", SdkClient.omitIfNull(projectVersion)), "multipart/form-data", new TypeReference<BomUploadResponse>(){}, "uploadBom", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UploadBomBase64EncodedRequest {

        private String bom;
        private String project;
        private String projectName;
        private String projectVersion;
        private Boolean autoCreate;
        private Boolean isActive;
        private Boolean isLatest;
        private String parentName;
        private String parentUuid;
        private String parentVersion;
        private List<Tag> projectTags;

        private UploadBomBase64EncodedRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UploadBomBase64EncodedRequest request = new UploadBomBase64EncodedRequest();
            public Builder bom(String val) { request.bom = val; return this; }
            public Builder project(String val) { request.project = val; return this; }
            public Builder projectName(String val) { request.projectName = val; return this; }
            public Builder projectVersion(String val) { request.projectVersion = val; return this; }
            public Builder autoCreate(Boolean val) { request.autoCreate = val; return this; }
            public Builder isActive(Boolean val) { request.isActive = val; return this; }
            public Builder isLatest(Boolean val) { request.isLatest = val; return this; }
            public Builder parentName(String val) { request.parentName = val; return this; }
            public Builder parentUuid(String val) { request.parentUuid = val; return this; }
            public Builder parentVersion(String val) { request.parentVersion = val; return this; }
            public Builder projectTags(List<Tag> val) { request.projectTags = val; return this; }
            public UploadBomBase64EncodedRequest build() { return request; }
        }
        public String getBom() { return bom; }
        public String getProject() { return project; }
        public String getProjectName() { return projectName; }
        public String getProjectVersion() { return projectVersion; }
        public Boolean getAutoCreate() { return autoCreate; }
        public Boolean getIsActive() { return isActive; }
        public Boolean getIsLatest() { return isLatest; }
        public String getParentName() { return parentName; }
        public String getParentUuid() { return parentUuid; }
        public String getParentVersion() { return parentVersion; }
        public List<Tag> getProjectTags() { return projectTags; }
    }

    /**
     * Uploads a Base64-encoded CycloneDX bill of materials (BOM) and associates it with a project. Supply `project`, `projectName`, and `projectVersion` as required by the schema, and use `autoCreate` to create a project when it does not exist. Processing is asynchronous; use the returned `token` to check progress, and send large BOMs through the POST upload endpoint to avoid the 20,000,000-character limit.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit. Requires permission BOM_UPLOAD
     */
    public static BomUploadResponse uploadBomBase64Encoded(SdkConfig.ClientConfig clientConfig, UploadBomBase64EncodedRequest request) {
        return uploadBomBase64Encoded(clientConfig, request, null);
    }

    /**
     * Uploads a Base64-encoded CycloneDX bill of materials (BOM) and associates it with a project. Supply `project`, `projectName`, and `projectVersion` as required by the schema, and use `autoCreate` to create a project when it does not exist. Processing is asynchronous; use the returned `token` to check progress, and send large BOMs through the POST upload endpoint to avoid the 20,000,000-character limit.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit. Requires permission BOM_UPLOAD
     */
    public static BomUploadResponse uploadBomBase64Encoded(SdkConfig.ClientConfig clientConfig, UploadBomBase64EncodedRequest request, SdkConfig.RequestOptions options) {
        String bom = request.getBom();
        String project = request.getProject();
        String projectName = request.getProjectName();
        String projectVersion = request.getProjectVersion();
        Boolean autoCreate = request.getAutoCreate();
        Boolean isActive = request.getIsActive();
        Boolean isLatest = request.getIsLatest();
        String parentName = request.getParentName();
        String parentUuid = request.getParentUuid();
        String parentVersion = request.getParentVersion();
        List<Tag> projectTags = request.getProjectTags();

        Validation.validatePattern("bom", bom, "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$");

        Validation.validatePattern("project", project, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("projectName", projectName, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("projectVersion", projectVersion, __l); }

        if (parentUuid != null) {
            Validation.validatePattern("parentUUID", parentUuid, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
        }

        return SdkClient.request(clientConfig, "PUT", "/v1/bom", null, SdkClient.q("bom", bom, "project", project, "projectName", projectName, "projectVersion", projectVersion, "autoCreate", SdkClient.omitIfNull(autoCreate), "isActive", SdkClient.omitIfNull(isActive), "isLatest", SdkClient.omitIfNull(isLatest), "parentName", SdkClient.omitIfNull(parentName), "parentUUID", SdkClient.omitIfNull(parentUuid), "parentVersion", SdkClient.omitIfNull(parentVersion), "projectTags", SdkClient.omitIfNull(projectTags)), null, new TypeReference<BomUploadResponse>(){}, "uploadBomBase64Encoded", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class ExportComponentAsCycloneDxRequest {

        private String uuid;
        private String format;
        private String version;

        private ExportComponentAsCycloneDxRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final ExportComponentAsCycloneDxRequest request = new ExportComponentAsCycloneDxRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder format(String val) { request.format = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public ExportComponentAsCycloneDxRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getFormat() { return format; }
        public String getVersion() { return version; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static String exportComponentAsCycloneDx(SdkConfig.ClientConfig clientConfig, ExportComponentAsCycloneDxRequest request) {
        return exportComponentAsCycloneDx(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static String exportComponentAsCycloneDx(SdkConfig.ClientConfig clientConfig, ExportComponentAsCycloneDxRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String format = request.getFormat();
        String version = request.getVersion();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/bom/cyclonedx/component/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("format", SdkClient.queryValue(format, "form", true), "version", SdkClient.queryValue(version, "form", true)), null, null, new TypeReference<String>(){}, "exportComponentAsCycloneDx", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class ExportProjectAsCycloneDxRequest {

        private String uuid;
        private String format;
        private String variant;
        private Boolean download;
        private String version;

        private ExportProjectAsCycloneDxRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final ExportProjectAsCycloneDxRequest request = new ExportProjectAsCycloneDxRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder format(String val) { request.format = val; return this; }
            public Builder variant(String val) { request.variant = val; return this; }
            public Builder download(Boolean val) { request.download = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public ExportProjectAsCycloneDxRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getFormat() { return format; }
        public String getVariant() { return variant; }
        public Boolean getDownload() { return download; }
        public String getVersion() { return version; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO The withVulnerabilities and vdr variants further require any of the following permissions: VIEW_VULNERABILITY VULNERABILITY_ANALYSIS VULNERABILITY_ANALYSIS_READ
     */
    public static byte[] exportProjectAsCycloneDx(SdkConfig.ClientConfig clientConfig, ExportProjectAsCycloneDxRequest request) {
        return exportProjectAsCycloneDx(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO The withVulnerabilities and vdr variants further require any of the following permissions: VIEW_VULNERABILITY VULNERABILITY_ANALYSIS VULNERABILITY_ANALYSIS_READ
     */
    public static byte[] exportProjectAsCycloneDx(SdkConfig.ClientConfig clientConfig, ExportProjectAsCycloneDxRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String format = request.getFormat();
        String variant = request.getVariant();
        Boolean download = request.getDownload();
        String version = request.getVersion();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/bom/cyclonedx/project/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("format", SdkClient.queryValue(format, "form", true), "variant", SdkClient.queryValue(variant, "form", true), "download", SdkClient.queryValue(download, "form", true), "version", SdkClient.queryValue(version, "form", true)), null, null, new TypeReference<byte[]>(){}, "exportProjectAsCycloneDx", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }


    public static class IsTokenBeingProcessedRequest {

        private String uuid;

        private IsTokenBeingProcessedRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final IsTokenBeingProcessedRequest request = new IsTokenBeingProcessedRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public IsTokenBeingProcessedRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * This endpoint is intended to be used in conjunction with uploading a supported BOM document. Upon upload, a token will be returned. The token can then be queried using this endpoint to determine if any tasks (such as vulnerability analysis) is being performed on the BOM: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token. Requires permission BOM_UPLOAD Deprecated . Use /v1/event/token/{uuid} instead.
     *
     * @deprecated This operation is deprecated and may be removed in a future
     *   release.
     */
    @Deprecated
    public static IsTokenBeingProcessedResponse isTokenBeingProcessed(SdkConfig.ClientConfig clientConfig, IsTokenBeingProcessedRequest request) {
        return isTokenBeingProcessed(clientConfig, request, null);
    }

    /**
     * This endpoint is intended to be used in conjunction with uploading a supported BOM document. Upon upload, a token will be returned. The token can then be queried using this endpoint to determine if any tasks (such as vulnerability analysis) is being performed on the BOM: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token. Requires permission BOM_UPLOAD Deprecated . Use /v1/event/token/{uuid} instead.
     *
     * @deprecated This operation is deprecated and may be removed in a future
     *   release.
     */
    @Deprecated
    public static IsTokenBeingProcessedResponse isTokenBeingProcessed(SdkConfig.ClientConfig clientConfig, IsTokenBeingProcessedRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/bom/token/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<IsTokenBeingProcessedResponse>(){}, "isTokenBeingProcessed", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
