// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.config_property.ConfigPropertyResponse;
import dependencytrackunofficialsdk.models.config_property.UpdateConfigPropertyRequest;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class ConfigProperty {

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<ConfigPropertyResponse> getConfigProperties(SdkConfig.ClientConfig clientConfig) {
        return getConfigProperties(clientConfig, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<ConfigPropertyResponse> getConfigProperties(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/configProperty", null, null, null, new TypeReference<List<ConfigPropertyResponse>>(){}, "getConfigProperties", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateConfigProperty1Request {

        private String groupName;
        private String propertyName;
        private String propertyValue;

        private UpdateConfigProperty1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateConfigProperty1Request request = new UpdateConfigProperty1Request();
            public Builder groupName(String val) { request.groupName = val; return this; }
            public Builder propertyName(String val) { request.propertyName = val; return this; }
            public Builder propertyValue(String val) { request.propertyValue = val; return this; }
            public UpdateConfigProperty1Request build() { return request; }
        }
        public String getGroupName() { return groupName; }
        public String getPropertyName() { return propertyName; }
        public String getPropertyValue() { return propertyValue; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static ConfigPropertyResponse updateConfigProperty1(SdkConfig.ClientConfig clientConfig, UpdateConfigProperty1Request request) {
        return updateConfigProperty1(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static ConfigPropertyResponse updateConfigProperty1(SdkConfig.ClientConfig clientConfig, UpdateConfigProperty1Request request, SdkConfig.RequestOptions options) {
        String groupName = request.getGroupName();
        String propertyName = request.getPropertyName();
        String propertyValue = request.getPropertyValue();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("groupName", groupName, __l); }
        Validation.validatePattern("groupName", groupName, "\\P{Cc}+");

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("propertyName", propertyName, __l); }
        Validation.validatePattern("propertyName", propertyName, "\\P{Cc}+");

        if (propertyValue != null) {
            Validation.validatePattern("propertyValue", propertyValue, "\\P{Cc}+");
        }

        return SdkClient.request(clientConfig, "POST", "/v1/configProperty", null, SdkClient.q("groupName", groupName, "propertyName", propertyName, "propertyValue", SdkClient.omitIfNull(propertyValue)), null, new TypeReference<ConfigPropertyResponse>(){}, "updateConfigProperty1", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateConfigPropertyParams {

        private List<UpdateConfigPropertyRequest> body;

        private UpdateConfigPropertyParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateConfigPropertyParams request = new UpdateConfigPropertyParams();
            public Builder body(List<UpdateConfigPropertyRequest> val) { request.body = val; return this; }
            public UpdateConfigPropertyParams build() { return request; }
        }
        public List<UpdateConfigPropertyRequest> getBody() { return body; }
    }

    /**
     * Updates multiple configuration properties from an array of property entries. The authenticated user must have `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission, and each entry must include `groupName` and `propertyName`. The response reports the result for each entry, including an error message when a property cannot be updated.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static List<Object> updateConfigProperty(SdkConfig.ClientConfig clientConfig, UpdateConfigPropertyParams request) {
        return updateConfigProperty(clientConfig, request, null);
    }

    /**
     * Updates multiple configuration properties from an array of property entries. The authenticated user must have `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission, and each entry must include `groupName` and `propertyName`. The response reports the result for each entry, including an error message when a property cannot be updated.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static List<Object> updateConfigProperty(SdkConfig.ClientConfig clientConfig, UpdateConfigPropertyParams request, SdkConfig.RequestOptions options) {
        List<UpdateConfigPropertyRequest> body = request.getBody();

        return SdkClient.request(clientConfig, "POST", "/v1/configProperty/aggregate", null, body, null, new TypeReference<List<Object>>(){}, "updateConfigProperty", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetInternalConfigPropertyRequest {

        private String groupName;
        private String propertyName;

        private GetInternalConfigPropertyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetInternalConfigPropertyRequest request = new GetInternalConfigPropertyRequest();
            public Builder groupName(String val) { request.groupName = val; return this; }
            public Builder propertyName(String val) { request.propertyName = val; return this; }
            public GetInternalConfigPropertyRequest build() { return request; }
        }
        public String getGroupName() { return groupName; }
        public String getPropertyName() { return propertyName; }
    }

    /**
     * Requires authentication, but no permission. Returns both internal and public properties
     */
    public static ConfigPropertyResponse getInternalConfigProperty(SdkConfig.ClientConfig clientConfig, GetInternalConfigPropertyRequest request) {
        return getInternalConfigProperty(clientConfig, request, null);
    }

    /**
     * Requires authentication, but no permission. Returns both internal and public properties
     */
    public static ConfigPropertyResponse getInternalConfigProperty(SdkConfig.ClientConfig clientConfig, GetInternalConfigPropertyRequest request, SdkConfig.RequestOptions options) {
        String groupName = request.getGroupName();
        String propertyName = request.getPropertyName();

        return SdkClient.request(clientConfig, "GET", "/v1/configProperty/internal/" + SdkClient.encodePathSegment(groupName) + "/" + SdkClient.encodePathSegment(propertyName) + "", null, null, null, new TypeReference<ConfigPropertyResponse>(){}, "getInternalConfigProperty", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetPublicConfigPropertyRequest {

        private String groupName;
        private String propertyName;

        private GetPublicConfigPropertyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetPublicConfigPropertyRequest request = new GetPublicConfigPropertyRequest();
            public Builder groupName(String val) { request.groupName = val; return this; }
            public Builder propertyName(String val) { request.propertyName = val; return this; }
            public GetPublicConfigPropertyRequest build() { return request; }
        }
        public String getGroupName() { return groupName; }
        public String getPropertyName() { return propertyName; }
    }

    /**
     * Retrieves a public configuration property by its group and property names. Use `groupName` and `propertyName` to identify the value you want to retrieve.
     */
    public static ConfigPropertyResponse getPublicConfigProperty(SdkConfig.ClientConfig clientConfig, GetPublicConfigPropertyRequest request) {
        return getPublicConfigProperty(clientConfig, request, null);
    }

    /**
     * Retrieves a public configuration property by its group and property names. Use `groupName` and `propertyName` to identify the value you want to retrieve.
     */
    public static ConfigPropertyResponse getPublicConfigProperty(SdkConfig.ClientConfig clientConfig, GetPublicConfigPropertyRequest request, SdkConfig.RequestOptions options) {
        String groupName = request.getGroupName();
        String propertyName = request.getPropertyName();

        return SdkClient.request(clientConfig, "GET", "/v1/configProperty/public/" + SdkClient.encodePathSegment(groupName) + "/" + SdkClient.encodePathSegment(propertyName) + "", null, null, null, new TypeReference<ConfigPropertyResponse>(){}, "getPublicConfigProperty", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
