// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.dependency_graph.DependencyGraphResponse;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class DependencyGraph {

    public static class GetComponentsAndServicesByComponentUuidRequest {

        private String uuid;

        private GetComponentsAndServicesByComponentUuidRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetComponentsAndServicesByComponentUuidRequest request = new GetComponentsAndServicesByComponentUuidRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetComponentsAndServicesByComponentUuidRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyGraphResponse> getComponentsAndServicesByComponentUuid(SdkConfig.ClientConfig clientConfig, GetComponentsAndServicesByComponentUuidRequest request) {
        return getComponentsAndServicesByComponentUuid(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyGraphResponse> getComponentsAndServicesByComponentUuid(SdkConfig.ClientConfig clientConfig, GetComponentsAndServicesByComponentUuidRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/dependencyGraph/component/" + SdkClient.encodePathSegment(uuid) + "/directDependencies", null, null, null, new TypeReference<List<DependencyGraphResponse>>(){}, "getComponentsAndServicesByComponentUuid", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetComponentsAndServicesByProjectUuidRequest {

        private String uuid;

        private GetComponentsAndServicesByProjectUuidRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetComponentsAndServicesByProjectUuidRequest request = new GetComponentsAndServicesByProjectUuidRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetComponentsAndServicesByProjectUuidRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyGraphResponse> getComponentsAndServicesByProjectUuid(SdkConfig.ClientConfig clientConfig, GetComponentsAndServicesByProjectUuidRequest request) {
        return getComponentsAndServicesByProjectUuid(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyGraphResponse> getComponentsAndServicesByProjectUuid(SdkConfig.ClientConfig clientConfig, GetComponentsAndServicesByProjectUuidRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/dependencyGraph/project/" + SdkClient.encodePathSegment(uuid) + "/directDependencies", null, null, null, new TypeReference<List<DependencyGraphResponse>>(){}, "getComponentsAndServicesByProjectUuid", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
