// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.ldap.MappedLdapGroupResponse;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Ldap {

    /**
     * This API performs a pass-through query to the configured LDAP server. Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<String> retrieveLdapGroups(SdkConfig.ClientConfig clientConfig) {
        return retrieveLdapGroups(clientConfig, null);
    }

    /**
     * This API performs a pass-through query to the configured LDAP server. Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<String> retrieveLdapGroups(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/ldap/groups", null, null, null, new TypeReference<List<String>>(){}, "retrieveLdapGroups", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddMapping1Request {

        private String dn;
        private String team;

        private AddMapping1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddMapping1Request request = new AddMapping1Request();
            public Builder dn(String val) { request.dn = val; return this; }
            public Builder team(String val) { request.team = val; return this; }
            public AddMapping1Request build() { return request; }
        }
        public String getDn() { return dn; }
        public String getTeam() { return team; }
    }

    /**
     * Creates a mapping between an LDAP group distinguished name and a team. Supply the `dn` and `team` fields in the JSON body; you need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission. A successful response includes the mapping's UUID.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static MappedLdapGroupResponse addMapping1(SdkConfig.ClientConfig clientConfig, AddMapping1Request request) {
        return addMapping1(clientConfig, request, null);
    }

    /**
     * Creates a mapping between an LDAP group distinguished name and a team. Supply the `dn` and `team` fields in the JSON body; you need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission. A successful response includes the mapping's UUID.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static MappedLdapGroupResponse addMapping1(SdkConfig.ClientConfig clientConfig, AddMapping1Request request, SdkConfig.RequestOptions options) {
        String dn = request.getDn();
        String team = request.getTeam();

        Validation.validatePattern("team", team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

        return SdkClient.request(clientConfig, "PUT", "/v1/ldap/mapping", null, SdkClient.q("dn", dn, "team", team), null, new TypeReference<MappedLdapGroupResponse>(){}, "addMapping1", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteMapping1Request {

        private String uuid;

        private DeleteMapping1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteMapping1Request request = new DeleteMapping1Request();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteMapping1Request build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMapping1(SdkConfig.ClientConfig clientConfig, DeleteMapping1Request request) {
        return deleteMapping1(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMapping1(SdkConfig.ClientConfig clientConfig, DeleteMapping1Request request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/ldap/mapping/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteMapping1", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class RetrieveLdapGroups1Request {

        private String uuid;

        private RetrieveLdapGroups1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RetrieveLdapGroups1Request request = new RetrieveLdapGroups1Request();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public RetrieveLdapGroups1Request build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<MappedLdapGroupResponse> retrieveLdapGroups1(SdkConfig.ClientConfig clientConfig, RetrieveLdapGroups1Request request) {
        return retrieveLdapGroups1(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<MappedLdapGroupResponse> retrieveLdapGroups1(SdkConfig.ClientConfig clientConfig, RetrieveLdapGroups1Request request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/ldap/team/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<List<MappedLdapGroupResponse>>(){}, "retrieveLdapGroups1", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
