// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.metrics.PortfolioMetrics;
import dependencytrackunofficialsdk.models.metrics.VulnerabilityMetrics;
import dependencytrackunofficialsdk.models.shared.DependencyMetrics;
import dependencytrackunofficialsdk.models.shared_project.ProjectMetrics;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Metrics {

    public static class GetComponentCurrentMetricsRequest {

        private String uuid;

        private GetComponentCurrentMetricsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetComponentCurrentMetricsRequest request = new GetComponentCurrentMetricsRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetComponentCurrentMetricsRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static DependencyMetrics getComponentCurrentMetrics(SdkConfig.ClientConfig clientConfig, GetComponentCurrentMetricsRequest request) {
        return getComponentCurrentMetrics(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static DependencyMetrics getComponentCurrentMetrics(SdkConfig.ClientConfig clientConfig, GetComponentCurrentMetricsRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/component/" + SdkClient.encodePathSegment(uuid) + "/current", null, null, null, new TypeReference<DependencyMetrics>(){}, "getComponentCurrentMetrics", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetComponentMetricsXDaysRequest {

        private String uuid;
        private Integer days;

        private GetComponentMetricsXDaysRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetComponentMetricsXDaysRequest request = new GetComponentMetricsXDaysRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder days(Integer val) { request.days = val; return this; }
            public GetComponentMetricsXDaysRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public Integer getDays() { return days; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyMetrics> getComponentMetricsXDays(SdkConfig.ClientConfig clientConfig, GetComponentMetricsXDaysRequest request) {
        return getComponentMetricsXDays(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyMetrics> getComponentMetricsXDays(SdkConfig.ClientConfig clientConfig, GetComponentMetricsXDaysRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        Integer days = request.getDays();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/component/" + SdkClient.encodePathSegment(uuid) + "/days/" + SdkClient.encodePathSegment(days) + "", null, null, null, new TypeReference<List<DependencyMetrics>>(){}, "getComponentMetricsXDays", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RefreshComponentMetricsRequest {

        private String uuid;

        private RefreshComponentMetricsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RefreshComponentMetricsRequest request = new RefreshComponentMetricsRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public RefreshComponentMetricsRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshComponentMetrics(SdkConfig.ClientConfig clientConfig, RefreshComponentMetricsRequest request) {
        return refreshComponentMetrics(clientConfig, request, null);
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshComponentMetrics(SdkConfig.ClientConfig clientConfig, RefreshComponentMetricsRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/component/" + SdkClient.encodePathSegment(uuid) + "/refresh", null, null, null, new TypeReference<Object>(){}, "refreshComponentMetrics", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetComponentMetricsSinceRequest {

        private String uuid;
        private String date;

        private GetComponentMetricsSinceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetComponentMetricsSinceRequest request = new GetComponentMetricsSinceRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder date(String val) { request.date = val; return this; }
            public GetComponentMetricsSinceRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getDate() { return date; }
    }

    /**
     * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyMetrics> getComponentMetricsSince(SdkConfig.ClientConfig clientConfig, GetComponentMetricsSinceRequest request) {
        return getComponentMetricsSince(clientConfig, request, null);
    }

    /**
     * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
     */
    public static List<DependencyMetrics> getComponentMetricsSince(SdkConfig.ClientConfig clientConfig, GetComponentMetricsSinceRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String date = request.getDate();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/component/" + SdkClient.encodePathSegment(uuid) + "/since/" + SdkClient.encodePathSegment(date) + "", null, null, null, new TypeReference<List<DependencyMetrics>>(){}, "getComponentMetricsSince", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static PortfolioMetrics getPortfolioCurrentMetrics(SdkConfig.ClientConfig clientConfig) {
        return getPortfolioCurrentMetrics(clientConfig, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static PortfolioMetrics getPortfolioCurrentMetrics(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/portfolio/current", null, null, null, new TypeReference<PortfolioMetrics>(){}, "getPortfolioCurrentMetrics", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshPortfolioMetrics(SdkConfig.ClientConfig clientConfig) {
        return refreshPortfolioMetrics(clientConfig, null);
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshPortfolioMetrics(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/portfolio/refresh", null, null, null, new TypeReference<Object>(){}, "refreshPortfolioMetrics", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetPortfolioMetricsSinceRequest {

        private String date;

        private GetPortfolioMetricsSinceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetPortfolioMetricsSinceRequest request = new GetPortfolioMetricsSinceRequest();
            public Builder date(String val) { request.date = val; return this; }
            public GetPortfolioMetricsSinceRequest build() { return request; }
        }
        public String getDate() { return date; }
    }

    /**
     * Date format must be YYYYMMDD . The number of days returned is computed against the current UTC date. Requires permission VIEW_PORTFOLIO
     */
    public static List<PortfolioMetrics> getPortfolioMetricsSince(SdkConfig.ClientConfig clientConfig, GetPortfolioMetricsSinceRequest request) {
        return getPortfolioMetricsSince(clientConfig, request, null);
    }

    /**
     * Date format must be YYYYMMDD . The number of days returned is computed against the current UTC date. Requires permission VIEW_PORTFOLIO
     */
    public static List<PortfolioMetrics> getPortfolioMetricsSince(SdkConfig.ClientConfig clientConfig, GetPortfolioMetricsSinceRequest request, SdkConfig.RequestOptions options) {
        String date = request.getDate();

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/portfolio/since/" + SdkClient.encodePathSegment(date) + "", null, null, null, new TypeReference<List<PortfolioMetrics>>(){}, "getPortfolioMetricsSince", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetPortfolioMetricsXDaysRequest {

        private Integer days;

        private GetPortfolioMetricsXDaysRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetPortfolioMetricsXDaysRequest request = new GetPortfolioMetricsXDaysRequest();
            public Builder days(Integer val) { request.days = val; return this; }
            public GetPortfolioMetricsXDaysRequest build() { return request; }
        }
        public Integer getDays() { return days; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<PortfolioMetrics> getPortfolioMetricsXDays(SdkConfig.ClientConfig clientConfig, GetPortfolioMetricsXDaysRequest request) {
        return getPortfolioMetricsXDays(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<PortfolioMetrics> getPortfolioMetricsXDays(SdkConfig.ClientConfig clientConfig, GetPortfolioMetricsXDaysRequest request, SdkConfig.RequestOptions options) {
        Integer days = request.getDays();

        { Validation.RangeOpts __r = new Validation.RangeOpts(); __r.exclusiveMin = 0d; Validation.validateRange("days", days, __r); }

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/portfolio/" + SdkClient.encodePathSegment(days) + "/days", null, null, null, new TypeReference<List<PortfolioMetrics>>(){}, "getPortfolioMetricsXDays", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetProjectCurrentMetricsRequest {

        private String uuid;

        private GetProjectCurrentMetricsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectCurrentMetricsRequest request = new GetProjectCurrentMetricsRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetProjectCurrentMetricsRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static ProjectMetrics getProjectCurrentMetrics(SdkConfig.ClientConfig clientConfig, GetProjectCurrentMetricsRequest request) {
        return getProjectCurrentMetrics(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static ProjectMetrics getProjectCurrentMetrics(SdkConfig.ClientConfig clientConfig, GetProjectCurrentMetricsRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/project/" + SdkClient.encodePathSegment(uuid) + "/current", null, null, null, new TypeReference<ProjectMetrics>(){}, "getProjectCurrentMetrics", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetProjectMetricsXDaysRequest {

        private String uuid;
        private Integer days;

        private GetProjectMetricsXDaysRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectMetricsXDaysRequest request = new GetProjectMetricsXDaysRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder days(Integer val) { request.days = val; return this; }
            public GetProjectMetricsXDaysRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public Integer getDays() { return days; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<ProjectMetrics> getProjectMetricsXDays(SdkConfig.ClientConfig clientConfig, GetProjectMetricsXDaysRequest request) {
        return getProjectMetricsXDays(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<ProjectMetrics> getProjectMetricsXDays(SdkConfig.ClientConfig clientConfig, GetProjectMetricsXDaysRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        Integer days = request.getDays();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/project/" + SdkClient.encodePathSegment(uuid) + "/days/" + SdkClient.encodePathSegment(days) + "", null, null, null, new TypeReference<List<ProjectMetrics>>(){}, "getProjectMetricsXDays", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RefreshProjectMetricsRequest {

        private String uuid;

        private RefreshProjectMetricsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RefreshProjectMetricsRequest request = new RefreshProjectMetricsRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public RefreshProjectMetricsRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshProjectMetrics(SdkConfig.ClientConfig clientConfig, RefreshProjectMetricsRequest request) {
        return refreshProjectMetrics(clientConfig, request, null);
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static Object refreshProjectMetrics(SdkConfig.ClientConfig clientConfig, RefreshProjectMetricsRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/project/" + SdkClient.encodePathSegment(uuid) + "/refresh", null, null, null, new TypeReference<Object>(){}, "refreshProjectMetrics", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetProjectMetricsSinceRequest {

        private String uuid;
        private String date;

        private GetProjectMetricsSinceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetProjectMetricsSinceRequest request = new GetProjectMetricsSinceRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder date(String val) { request.date = val; return this; }
            public GetProjectMetricsSinceRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getDate() { return date; }
    }

    /**
     * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
     */
    public static List<ProjectMetrics> getProjectMetricsSince(SdkConfig.ClientConfig clientConfig, GetProjectMetricsSinceRequest request) {
        return getProjectMetricsSince(clientConfig, request, null);
    }

    /**
     * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
     */
    public static List<ProjectMetrics> getProjectMetricsSince(SdkConfig.ClientConfig clientConfig, GetProjectMetricsSinceRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String date = request.getDate();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/project/" + SdkClient.encodePathSegment(uuid) + "/since/" + SdkClient.encodePathSegment(date) + "", null, null, null, new TypeReference<List<ProjectMetrics>>(){}, "getProjectMetricsSince", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<VulnerabilityMetrics> getVulnerabilityMetrics(SdkConfig.ClientConfig clientConfig) {
        return getVulnerabilityMetrics(clientConfig, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<VulnerabilityMetrics> getVulnerabilityMetrics(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/metrics/vulnerability", null, null, null, new TypeReference<List<VulnerabilityMetrics>>(){}, "getVulnerabilityMetrics", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
