// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.notification.CreateNotificationRuleRequestLevelEnum;
import dependencytrackunofficialsdk.models.notification.CreateNotificationRuleRequestScopeEnum;
import dependencytrackunofficialsdk.models.notification.NotificationPublisherResponse;
import dependencytrackunofficialsdk.models.notification.NotificationRule;
import dependencytrackunofficialsdk.models.notification.NotificationRuleNotifyOnItemEnum;
import dependencytrackunofficialsdk.models.notification.NotificationRuleTriggerTypeEnum;
import dependencytrackunofficialsdk.models.notification.Publisher;
import dependencytrackunofficialsdk.models.shared.Tag;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Notification {

    public static final class GetAllNotificationRulesSortOrder {
        public static final GetAllNotificationRulesSortOrder DESC = new GetAllNotificationRulesSortOrder(" desc");
        public static final GetAllNotificationRulesSortOrder ASC = new GetAllNotificationRulesSortOrder("asc");
        private final String value;
        private GetAllNotificationRulesSortOrder(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
        @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
        public static GetAllNotificationRulesSortOrder fromValue(String value) {
            if (" desc".equals(value)) return DESC;
            if ("asc".equals(value)) return ASC;
            return new GetAllNotificationRulesSortOrder(value);
        }
        @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
        @java.lang.Override public String toString() { return value; }
        @java.lang.Override public boolean equals(Object other) {
            return this == other || (other instanceof GetAllNotificationRulesSortOrder o && value.equals(o.value));
        }
        @java.lang.Override public int hashCode() { return value.hashCode(); }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<NotificationPublisherResponse> getAllNotificationPublishers(SdkConfig.ClientConfig clientConfig) {
        return getAllNotificationPublishers(clientConfig, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<NotificationPublisherResponse> getAllNotificationPublishers(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/notification/publisher", null, null, null, new TypeReference<List<NotificationPublisherResponse>>(){}, "getAllNotificationPublishers", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateNotificationPublisherParams {

        private String extensionName;
        private String name;
        private String uuid;
        private String description;
        private String template;
        private String templateMimeType;

        private UpdateNotificationPublisherParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateNotificationPublisherParams request = new UpdateNotificationPublisherParams();
            public Builder extensionName(String val) { request.extensionName = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder description(String val) { request.description = val; return this; }
            public Builder template(String val) { request.template = val; return this; }
            public Builder templateMimeType(String val) { request.templateMimeType = val; return this; }
            public UpdateNotificationPublisherParams build() { return request; }
        }
        public String getExtensionName() { return extensionName; }
        public String getName() { return name; }
        public String getUuid() { return uuid; }
        public String getDescription() { return description; }
        public String getTemplate() { return template; }
        public String getTemplateMimeType() { return templateMimeType; }
    }

    /**
     * Updates an existing notification publisher, including its extension, name, description, and notification template. Supply `extensionName`, `name`, and `uuid`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission. A 200 response returns the updated notification publisher.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationPublisherResponse updateNotificationPublisher(SdkConfig.ClientConfig clientConfig, UpdateNotificationPublisherParams request) {
        return updateNotificationPublisher(clientConfig, request, null);
    }

    /**
     * Updates an existing notification publisher, including its extension, name, description, and notification template. Supply `extensionName`, `name`, and `uuid`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission. A 200 response returns the updated notification publisher.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationPublisherResponse updateNotificationPublisher(SdkConfig.ClientConfig clientConfig, UpdateNotificationPublisherParams request, SdkConfig.RequestOptions options) {
        String extensionName = request.getExtensionName();
        String name = request.getName();
        String uuid = request.getUuid();
        String description = request.getDescription();
        String template = request.getTemplate();
        String templateMimeType = request.getTemplateMimeType();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("extensionName", extensionName, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("name", name, __l); }

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "POST", "/v1/notification/publisher", null, SdkClient.q("extensionName", extensionName, "name", name, "uuid", uuid, "description", SdkClient.omitIfNull(description), "template", SdkClient.omitIfNull(template), "templateMimeType", SdkClient.omitIfNull(templateMimeType)), null, new TypeReference<NotificationPublisherResponse>(){}, "updateNotificationPublisher", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateNotificationPublisherParams {

        private String extensionName;
        private String name;
        private String description;
        private String template;
        private String templateMimeType;

        private CreateNotificationPublisherParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateNotificationPublisherParams request = new CreateNotificationPublisherParams();
            public Builder extensionName(String val) { request.extensionName = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder description(String val) { request.description = val; return this; }
            public Builder template(String val) { request.template = val; return this; }
            public Builder templateMimeType(String val) { request.templateMimeType = val; return this; }
            public CreateNotificationPublisherParams build() { return request; }
        }
        public String getExtensionName() { return extensionName; }
        public String getName() { return name; }
        public String getDescription() { return description; }
        public String getTemplate() { return template; }
        public String getTemplateMimeType() { return templateMimeType; }
    }

    /**
     * Creates a new notification publisher with its extension, name, and optional template details. Supply `extensionName` and `name`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission. A 201 response returns the created notification publisher with its generated UUID.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationPublisherResponse createNotificationPublisher(SdkConfig.ClientConfig clientConfig, CreateNotificationPublisherParams request) {
        return createNotificationPublisher(clientConfig, request, null);
    }

    /**
     * Creates a new notification publisher with its extension, name, and optional template details. Supply `extensionName` and `name`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission. A 201 response returns the created notification publisher with its generated UUID.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationPublisherResponse createNotificationPublisher(SdkConfig.ClientConfig clientConfig, CreateNotificationPublisherParams request, SdkConfig.RequestOptions options) {
        String extensionName = request.getExtensionName();
        String name = request.getName();
        String description = request.getDescription();
        String template = request.getTemplate();
        String templateMimeType = request.getTemplateMimeType();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("extensionName", extensionName, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("name", name, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/notification/publisher", null, SdkClient.q("extensionName", extensionName, "name", name, "description", SdkClient.omitIfNull(description), "template", SdkClient.omitIfNull(template), "templateMimeType", SdkClient.omitIfNull(templateMimeType)), null, new TypeReference<NotificationPublisherResponse>(){}, "createNotificationPublisher", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class TestNotificationRuleRequest {

        private String uuid;

        private TestNotificationRuleRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final TestNotificationRuleRequest request = new TestNotificationRuleRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public TestNotificationRuleRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION
     */
    public static Object testNotificationRule(SdkConfig.ClientConfig clientConfig, TestNotificationRuleRequest request) {
        return testNotificationRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION
     */
    public static Object testNotificationRule(SdkConfig.ClientConfig clientConfig, TestNotificationRuleRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "POST", "/v1/notification/publisher/test/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "testNotificationRule", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class DeleteNotificationPublisherRequest {

        private String notificationPublisherUuid;

        private DeleteNotificationPublisherRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteNotificationPublisherRequest request = new DeleteNotificationPublisherRequest();
            public Builder notificationPublisherUuid(String val) { request.notificationPublisherUuid = val; return this; }
            public DeleteNotificationPublisherRequest build() { return request; }
        }
        public String getNotificationPublisherUuid() { return notificationPublisherUuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteNotificationPublisher(SdkConfig.ClientConfig clientConfig, DeleteNotificationPublisherRequest request) {
        return deleteNotificationPublisher(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteNotificationPublisher(SdkConfig.ClientConfig clientConfig, DeleteNotificationPublisherRequest request, SdkConfig.RequestOptions options) {
        String notificationPublisherUuid = request.getNotificationPublisherUuid();

        Validation.validateUuid("notificationPublisherUuid", notificationPublisherUuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/notification/publisher/" + SdkClient.encodePathSegment(notificationPublisherUuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteNotificationPublisher", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetNotificationPublisherConfigSchemaRequest {

        private String uuid;

        private GetNotificationPublisherConfigSchemaRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetNotificationPublisherConfigSchemaRequest request = new GetNotificationPublisherConfigSchemaRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetNotificationPublisherConfigSchemaRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Retrieves the configuration schema for a notification publisher. Use this operation to determine the configuration fields supported by the publisher; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_READ` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static String getNotificationPublisherConfigSchema(SdkConfig.ClientConfig clientConfig, GetNotificationPublisherConfigSchemaRequest request) {
        return getNotificationPublisherConfigSchema(clientConfig, request, null);
    }

    /**
     * Retrieves the configuration schema for a notification publisher. Use this operation to determine the configuration fields supported by the publisher; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_READ` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static String getNotificationPublisherConfigSchema(SdkConfig.ClientConfig clientConfig, GetNotificationPublisherConfigSchemaRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/notification/publisher/" + SdkClient.encodePathSegment(uuid) + "/configSchema", null, null, null, new TypeReference<String>(){}, "getNotificationPublisherConfigSchema", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteNotificationRuleParams {

        private String uuid;

        private DeleteNotificationRuleParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteNotificationRuleParams request = new DeleteNotificationRuleParams();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteNotificationRuleParams build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteNotificationRule(SdkConfig.ClientConfig clientConfig, DeleteNotificationRuleParams request) {
        return deleteNotificationRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteNotificationRule(SdkConfig.ClientConfig clientConfig, DeleteNotificationRuleParams request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/notification/rule", null, SdkClient.q("uuid", uuid), null, new TypeReference<Object>(){}, "deleteNotificationRule", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetAllNotificationRulesRequest {

        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetAllNotificationRulesSortOrder sortOrder;
        private NotificationRuleTriggerTypeEnum triggerType;

        private GetAllNotificationRulesRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetAllNotificationRulesRequest request = new GetAllNotificationRulesRequest();
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetAllNotificationRulesSortOrder val) { request.sortOrder = val; return this; }
            public Builder triggerType(NotificationRuleTriggerTypeEnum val) { request.triggerType = val; return this; }
            public GetAllNotificationRulesRequest build() { return request; }
        }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetAllNotificationRulesSortOrder getSortOrder() { return sortOrder; }
        public NotificationRuleTriggerTypeEnum getTriggerType() { return triggerType; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<NotificationRule> getAllNotificationRules(SdkConfig.ClientConfig clientConfig, GetAllNotificationRulesRequest request) {
        return getAllNotificationRules(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<NotificationRule> getAllNotificationRules(SdkConfig.ClientConfig clientConfig, GetAllNotificationRulesRequest request, SdkConfig.RequestOptions options) {
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetAllNotificationRulesSortOrder sortOrder = request.getSortOrder();
        NotificationRuleTriggerTypeEnum triggerType = request.getTriggerType();

        return SdkClient.request(clientConfig, "GET", "/v1/notification/rule", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true), "triggerType", SdkClient.queryValue(triggerType, "form", true)), null, null, new TypeReference<List<NotificationRule>>(){}, "getAllNotificationRules", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateNotificationRuleParams {

        private CreateNotificationRuleRequestLevelEnum level;
        private String name;
        private CreateNotificationRuleRequestScopeEnum scope;
        private String uuid;
        private Boolean enabled;
        private String filterExpression;
        private Boolean logSuccessfulPublish;
        private Boolean notifyChildren;
        private List<NotificationRuleNotifyOnItemEnum> notifyOn;
        private String publisherConfig;
        private String scheduleCron;
        private Boolean scheduleSkipUnchanged;
        private List<Tag> tags;

        private UpdateNotificationRuleParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateNotificationRuleParams request = new UpdateNotificationRuleParams();
            public Builder level(CreateNotificationRuleRequestLevelEnum val) { request.level = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder scope(CreateNotificationRuleRequestScopeEnum val) { request.scope = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder enabled(Boolean val) { request.enabled = val; return this; }
            public Builder filterExpression(String val) { request.filterExpression = val; return this; }
            public Builder logSuccessfulPublish(Boolean val) { request.logSuccessfulPublish = val; return this; }
            public Builder notifyChildren(Boolean val) { request.notifyChildren = val; return this; }
            public Builder notifyOn(List<NotificationRuleNotifyOnItemEnum> val) { request.notifyOn = val; return this; }
            public Builder publisherConfig(String val) { request.publisherConfig = val; return this; }
            public Builder scheduleCron(String val) { request.scheduleCron = val; return this; }
            public Builder scheduleSkipUnchanged(Boolean val) { request.scheduleSkipUnchanged = val; return this; }
            public Builder tags(List<Tag> val) { request.tags = val; return this; }
            public UpdateNotificationRuleParams build() { return request; }
        }
        public CreateNotificationRuleRequestLevelEnum getLevel() { return level; }
        public String getName() { return name; }
        public CreateNotificationRuleRequestScopeEnum getScope() { return scope; }
        public String getUuid() { return uuid; }
        public Boolean getEnabled() { return enabled; }
        public String getFilterExpression() { return filterExpression; }
        public Boolean getLogSuccessfulPublish() { return logSuccessfulPublish; }
        public Boolean getNotifyChildren() { return notifyChildren; }
        public List<NotificationRuleNotifyOnItemEnum> getNotifyOn() { return notifyOn; }
        public String getPublisherConfig() { return publisherConfig; }
        public String getScheduleCron() { return scheduleCron; }
        public Boolean getScheduleSkipUnchanged() { return scheduleSkipUnchanged; }
        public List<Tag> getTags() { return tags; }
    }

    /**
     * Updates an existing notification rule using its UUID. Supply `uuid`, `name`, `level`, and `scope`, and include optional notification, filtering, publisher, or scheduling settings as needed. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule updateNotificationRule(SdkConfig.ClientConfig clientConfig, UpdateNotificationRuleParams request) {
        return updateNotificationRule(clientConfig, request, null);
    }

    /**
     * Updates an existing notification rule using its UUID. Supply `uuid`, `name`, `level`, and `scope`, and include optional notification, filtering, publisher, or scheduling settings as needed. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule updateNotificationRule(SdkConfig.ClientConfig clientConfig, UpdateNotificationRuleParams request, SdkConfig.RequestOptions options) {
        CreateNotificationRuleRequestLevelEnum level = request.getLevel();
        String name = request.getName();
        CreateNotificationRuleRequestScopeEnum scope = request.getScope();
        String uuid = request.getUuid();
        Boolean enabled = request.getEnabled();
        String filterExpression = request.getFilterExpression();
        Boolean logSuccessfulPublish = request.getLogSuccessfulPublish();
        Boolean notifyChildren = request.getNotifyChildren();
        List<NotificationRuleNotifyOnItemEnum> notifyOn = request.getNotifyOn();
        String publisherConfig = request.getPublisherConfig();
        String scheduleCron = request.getScheduleCron();
        Boolean scheduleSkipUnchanged = request.getScheduleSkipUnchanged();
        List<Tag> tags = request.getTags();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("name", name, __l); }

        Validation.validateUuid("uuid", uuid);

        if (filterExpression != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 2048; Validation.validateLength("filterExpression", filterExpression, __l); }
        }

        return SdkClient.request(clientConfig, "POST", "/v1/notification/rule", null, SdkClient.q("level", level, "name", name, "scope", scope, "uuid", uuid, "enabled", SdkClient.omitIfNull(enabled), "filterExpression", SdkClient.omitIfNull(filterExpression), "logSuccessfulPublish", SdkClient.omitIfNull(logSuccessfulPublish), "notifyChildren", SdkClient.omitIfNull(notifyChildren), "notifyOn", SdkClient.omitIfNull(notifyOn), "publisherConfig", SdkClient.omitIfNull(publisherConfig), "scheduleCron", SdkClient.omitIfNull(scheduleCron), "scheduleSkipUnchanged", SdkClient.omitIfNull(scheduleSkipUnchanged), "tags", SdkClient.omitIfNull(tags)), null, new TypeReference<NotificationRule>(){}, "updateNotificationRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateNotificationRuleParams {

        private CreateNotificationRuleRequestLevelEnum level;
        private String name;
        private Publisher publisher;
        private CreateNotificationRuleRequestScopeEnum scope;

        private CreateNotificationRuleParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateNotificationRuleParams request = new CreateNotificationRuleParams();
            public Builder level(CreateNotificationRuleRequestLevelEnum val) { request.level = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder publisher(Publisher val) { request.publisher = val; return this; }
            public Builder scope(CreateNotificationRuleRequestScopeEnum val) { request.scope = val; return this; }
            public CreateNotificationRuleParams build() { return request; }
        }
        public CreateNotificationRuleRequestLevelEnum getLevel() { return level; }
        public String getName() { return name; }
        public Publisher getPublisher() { return publisher; }
        public CreateNotificationRuleRequestScopeEnum getScope() { return scope; }
    }

    /**
     * Creates a new notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationRule createNotificationRule(SdkConfig.ClientConfig clientConfig, CreateNotificationRuleParams request) {
        return createNotificationRule(clientConfig, request, null);
    }

    /**
     * Creates a new notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationRule createNotificationRule(SdkConfig.ClientConfig clientConfig, CreateNotificationRuleParams request, SdkConfig.RequestOptions options) {
        CreateNotificationRuleRequestLevelEnum level = request.getLevel();
        String name = request.getName();
        Publisher publisher = request.getPublisher();
        CreateNotificationRuleRequestScopeEnum scope = request.getScope();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("name", name, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/notification/rule", null, SdkClient.q("level", level, "name", name, "publisher", publisher, "scope", scope), null, new TypeReference<NotificationRule>(){}, "createNotificationRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateScheduledNotificationRuleParams {

        private CreateNotificationRuleRequestLevelEnum level;
        private String name;
        private Publisher publisher;
        private CreateNotificationRuleRequestScopeEnum scope;

        private CreateScheduledNotificationRuleParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateScheduledNotificationRuleParams request = new CreateScheduledNotificationRuleParams();
            public Builder level(CreateNotificationRuleRequestLevelEnum val) { request.level = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder publisher(Publisher val) { request.publisher = val; return this; }
            public Builder scope(CreateNotificationRuleRequestScopeEnum val) { request.scope = val; return this; }
            public CreateScheduledNotificationRuleParams build() { return request; }
        }
        public CreateNotificationRuleRequestLevelEnum getLevel() { return level; }
        public String getName() { return name; }
        public Publisher getPublisher() { return publisher; }
        public CreateNotificationRuleRequestScopeEnum getScope() { return scope; }
    }

    /**
     * Creates a new scheduled notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID; `name` must contain 1 to 255 characters matching the allowed character pattern. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationRule createScheduledNotificationRule(SdkConfig.ClientConfig clientConfig, CreateScheduledNotificationRuleParams request) {
        return createScheduledNotificationRule(clientConfig, request, null);
    }

    /**
     * Creates a new scheduled notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID; `name` must contain 1 to 255 characters matching the allowed character pattern. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
     *
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static NotificationRule createScheduledNotificationRule(SdkConfig.ClientConfig clientConfig, CreateScheduledNotificationRuleParams request, SdkConfig.RequestOptions options) {
        CreateNotificationRuleRequestLevelEnum level = request.getLevel();
        String name = request.getName();
        Publisher publisher = request.getPublisher();
        CreateNotificationRuleRequestScopeEnum scope = request.getScope();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/notification/rule/scheduled", null, SdkClient.q("level", level, "name", name, "publisher", publisher, "scope", scope), null, new TypeReference<NotificationRule>(){}, "createScheduledNotificationRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RemoveProjectFromRuleRequest {

        private String ruleUuid;
        private String projectUuid;

        private RemoveProjectFromRuleRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RemoveProjectFromRuleRequest request = new RemoveProjectFromRuleRequest();
            public Builder ruleUuid(String val) { request.ruleUuid = val; return this; }
            public Builder projectUuid(String val) { request.projectUuid = val; return this; }
            public RemoveProjectFromRuleRequest build() { return request; }
        }
        public String getRuleUuid() { return ruleUuid; }
        public String getProjectUuid() { return projectUuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static NotificationRule removeProjectFromRule(SdkConfig.ClientConfig clientConfig, RemoveProjectFromRuleRequest request) {
        return removeProjectFromRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static NotificationRule removeProjectFromRule(SdkConfig.ClientConfig clientConfig, RemoveProjectFromRuleRequest request, SdkConfig.RequestOptions options) {
        String ruleUuid = request.getRuleUuid();
        String projectUuid = request.getProjectUuid();

        Validation.validateUuid("ruleUuid", ruleUuid);

        Validation.validateUuid("projectUuid", projectUuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/notification/rule/" + SdkClient.encodePathSegment(ruleUuid) + "/project/" + SdkClient.encodePathSegment(projectUuid) + "", null, null, null, new TypeReference<NotificationRule>(){}, "removeProjectFromRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddProjectToRuleRequest {

        private String ruleUuid;
        private String projectUuid;

        private AddProjectToRuleRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddProjectToRuleRequest request = new AddProjectToRuleRequest();
            public Builder ruleUuid(String val) { request.ruleUuid = val; return this; }
            public Builder projectUuid(String val) { request.projectUuid = val; return this; }
            public AddProjectToRuleRequest build() { return request; }
        }
        public String getRuleUuid() { return ruleUuid; }
        public String getProjectUuid() { return projectUuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule addProjectToRule(SdkConfig.ClientConfig clientConfig, AddProjectToRuleRequest request) {
        return addProjectToRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule addProjectToRule(SdkConfig.ClientConfig clientConfig, AddProjectToRuleRequest request, SdkConfig.RequestOptions options) {
        String ruleUuid = request.getRuleUuid();
        String projectUuid = request.getProjectUuid();

        Validation.validateUuid("ruleUuid", ruleUuid);

        Validation.validateUuid("projectUuid", projectUuid);

        return SdkClient.request(clientConfig, "POST", "/v1/notification/rule/" + SdkClient.encodePathSegment(ruleUuid) + "/project/" + SdkClient.encodePathSegment(projectUuid) + "", null, null, null, new TypeReference<NotificationRule>(){}, "addProjectToRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RemoveTeamFromRuleRequest {

        private String ruleUuid;
        private String teamUuid;

        private RemoveTeamFromRuleRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RemoveTeamFromRuleRequest request = new RemoveTeamFromRuleRequest();
            public Builder ruleUuid(String val) { request.ruleUuid = val; return this; }
            public Builder teamUuid(String val) { request.teamUuid = val; return this; }
            public RemoveTeamFromRuleRequest build() { return request; }
        }
        public String getRuleUuid() { return ruleUuid; }
        public String getTeamUuid() { return teamUuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static NotificationRule removeTeamFromRule(SdkConfig.ClientConfig clientConfig, RemoveTeamFromRuleRequest request) {
        return removeTeamFromRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static NotificationRule removeTeamFromRule(SdkConfig.ClientConfig clientConfig, RemoveTeamFromRuleRequest request, SdkConfig.RequestOptions options) {
        String ruleUuid = request.getRuleUuid();
        String teamUuid = request.getTeamUuid();

        Validation.validateUuid("ruleUuid", ruleUuid);

        Validation.validateUuid("teamUuid", teamUuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/notification/rule/" + SdkClient.encodePathSegment(ruleUuid) + "/team/" + SdkClient.encodePathSegment(teamUuid) + "", null, null, null, new TypeReference<NotificationRule>(){}, "removeTeamFromRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddTeamToRuleRequest {

        private String ruleUuid;
        private String teamUuid;

        private AddTeamToRuleRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddTeamToRuleRequest request = new AddTeamToRuleRequest();
            public Builder ruleUuid(String val) { request.ruleUuid = val; return this; }
            public Builder teamUuid(String val) { request.teamUuid = val; return this; }
            public AddTeamToRuleRequest build() { return request; }
        }
        public String getRuleUuid() { return ruleUuid; }
        public String getTeamUuid() { return teamUuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule addTeamToRule(SdkConfig.ClientConfig clientConfig, AddTeamToRuleRequest request) {
        return addTeamToRule(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static NotificationRule addTeamToRule(SdkConfig.ClientConfig clientConfig, AddTeamToRuleRequest request, SdkConfig.RequestOptions options) {
        String ruleUuid = request.getRuleUuid();
        String teamUuid = request.getTeamUuid();

        Validation.validateUuid("ruleUuid", ruleUuid);

        Validation.validateUuid("teamUuid", teamUuid);

        return SdkClient.request(clientConfig, "POST", "/v1/notification/rule/" + SdkClient.encodePathSegment(ruleUuid) + "/team/" + SdkClient.encodePathSegment(teamUuid) + "", null, null, null, new TypeReference<NotificationRule>(){}, "addTeamToRule", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
