// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.oidc.MappedOidcGroupResponse;
import dependencytrackunofficialsdk.models.oidc.OidcGroupResponse;
import dependencytrackunofficialsdk.models.shared.Team;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Oidc {

    /**
     * Reports whether OpenID Connect is available for the application. Use the boolean result to determine whether OpenID Connect is available before relying on it.
     */
    public static Boolean isAvailable(SdkConfig.ClientConfig clientConfig) {
        return isAvailable(clientConfig, null);
    }

    /**
     * Reports whether OpenID Connect is available for the application. Use the boolean result to determine whether OpenID Connect is available before relying on it.
     */
    public static Boolean isAvailable(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/oidc/available", null, null, null, new TypeReference<Boolean>(){}, "isAvailable", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<OidcGroupResponse> retrieveGroups(SdkConfig.ClientConfig clientConfig) {
        return retrieveGroups(clientConfig, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<OidcGroupResponse> retrieveGroups(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/oidc/group", null, null, null, new TypeReference<List<OidcGroupResponse>>(){}, "retrieveGroups", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateGroupRequest {

        private String name;
        private String uuid;

        private UpdateGroupRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateGroupRequest request = new UpdateGroupRequest();
            public Builder name(String val) { request.name = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public UpdateGroupRequest build() { return request; }
        }
        public String getName() { return name; }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static OidcGroupResponse updateGroup(SdkConfig.ClientConfig clientConfig, UpdateGroupRequest request) {
        return updateGroup(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static OidcGroupResponse updateGroup(SdkConfig.ClientConfig clientConfig, UpdateGroupRequest request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        String uuid = request.getUuid();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }
        Validation.validatePattern("name", name, "[\\P{Cc}]+");

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "POST", "/v1/oidc/group", null, SdkClient.q("name", name, "uuid", uuid), null, new TypeReference<OidcGroupResponse>(){}, "updateGroup", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateGroupRequest {

        private String name;

        private CreateGroupRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateGroupRequest request = new CreateGroupRequest();
            public Builder name(String val) { request.name = val; return this; }
            public CreateGroupRequest build() { return request; }
        }
        public String getName() { return name; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static OidcGroupResponse createGroup(SdkConfig.ClientConfig clientConfig, CreateGroupRequest request) {
        return createGroup(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static OidcGroupResponse createGroup(SdkConfig.ClientConfig clientConfig, CreateGroupRequest request, SdkConfig.RequestOptions options) {
        String name = request.getName();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }
        Validation.validatePattern("name", name, "[\\P{Cc}]+");

        return SdkClient.request(clientConfig, "PUT", "/v1/oidc/group", null, SdkClient.q("name", name), null, new TypeReference<OidcGroupResponse>(){}, "createGroup", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteMapping2Request {

        private String groupUuid;
        private String teamUuid;

        private DeleteMapping2Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteMapping2Request request = new DeleteMapping2Request();
            public Builder groupUuid(String val) { request.groupUuid = val; return this; }
            public Builder teamUuid(String val) { request.teamUuid = val; return this; }
            public DeleteMapping2Request build() { return request; }
        }
        public String getGroupUuid() { return groupUuid; }
        public String getTeamUuid() { return teamUuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMapping2(SdkConfig.ClientConfig clientConfig, DeleteMapping2Request request) {
        return deleteMapping2(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMapping2(SdkConfig.ClientConfig clientConfig, DeleteMapping2Request request, SdkConfig.RequestOptions options) {
        String groupUuid = request.getGroupUuid();
        String teamUuid = request.getTeamUuid();

        Validation.validateUuid("groupUuid", groupUuid);

        Validation.validateUuid("teamUuid", teamUuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/oidc/group/" + SdkClient.encodePathSegment(groupUuid) + "/team/" + SdkClient.encodePathSegment(teamUuid) + "/mapping", null, null, null, new TypeReference<Object>(){}, "deleteMapping2", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class DeleteGroupRequest {

        private String uuid;

        private DeleteGroupRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteGroupRequest request = new DeleteGroupRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteGroupRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteGroup(SdkConfig.ClientConfig clientConfig, DeleteGroupRequest request) {
        return deleteGroup(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteGroup(SdkConfig.ClientConfig clientConfig, DeleteGroupRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/oidc/group/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteGroup", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class RetrieveTeamsMappedToGroupRequest {

        private String uuid;

        private RetrieveTeamsMappedToGroupRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RetrieveTeamsMappedToGroupRequest request = new RetrieveTeamsMappedToGroupRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public RetrieveTeamsMappedToGroupRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<Team> retrieveTeamsMappedToGroup(SdkConfig.ClientConfig clientConfig, RetrieveTeamsMappedToGroupRequest request) {
        return retrieveTeamsMappedToGroup(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static List<Team> retrieveTeamsMappedToGroup(SdkConfig.ClientConfig clientConfig, RetrieveTeamsMappedToGroupRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/oidc/group/" + SdkClient.encodePathSegment(uuid) + "/team", null, null, null, new TypeReference<List<Team>>(){}, "retrieveTeamsMappedToGroup", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddMapping2Request {

        private String group;
        private String team;

        private AddMapping2Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddMapping2Request request = new AddMapping2Request();
            public Builder group(String val) { request.group = val; return this; }
            public Builder team(String val) { request.team = val; return this; }
            public AddMapping2Request build() { return request; }
        }
        public String getGroup() { return group; }
        public String getTeam() { return team; }
    }

    /**
     * Creates a mapping between an OIDC group and a team. Supply `group` and `team` as UUID-formatted values to associate them. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static MappedOidcGroupResponse addMapping2(SdkConfig.ClientConfig clientConfig, AddMapping2Request request) {
        return addMapping2(clientConfig, request, null);
    }

    /**
     * Creates a mapping between an OIDC group and a team. Supply `group` and `team` as UUID-formatted values to associate them. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
     */
    public static MappedOidcGroupResponse addMapping2(SdkConfig.ClientConfig clientConfig, AddMapping2Request request, SdkConfig.RequestOptions options) {
        String group = request.getGroup();
        String team = request.getTeam();

        Validation.validatePattern("group", group, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

        Validation.validatePattern("team", team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

        return SdkClient.request(clientConfig, "PUT", "/v1/oidc/mapping", null, SdkClient.q("group", group, "team", team), null, new TypeReference<MappedOidcGroupResponse>(){}, "addMapping2", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteMappingByUuidRequest {

        private String uuid;

        private DeleteMappingByUuidRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteMappingByUuidRequest request = new DeleteMappingByUuidRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteMappingByUuidRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMappingByUuid(SdkConfig.ClientConfig clientConfig, DeleteMappingByUuidRequest request) {
        return deleteMappingByUuid(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Object deleteMappingByUuid(SdkConfig.ClientConfig clientConfig, DeleteMappingByUuidRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/oidc/mapping/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteMappingByUuid", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }



}
