// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.permission.TeamPermissionsSetRequestPermissionsItemEnum;
import dependencytrackunofficialsdk.models.shared.Team;
import dependencytrackunofficialsdk.models.shared.User;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class PermissionApi {

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static TeamPermissionsSetRequestPermissionsItemEnum getAllPermissions(SdkConfig.ClientConfig clientConfig) {
        return getAllPermissions(clientConfig, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
     */
    public static TeamPermissionsSetRequestPermissionsItemEnum getAllPermissions(SdkConfig.ClientConfig clientConfig, SdkConfig.RequestOptions options) {

        return SdkClient.request(clientConfig, "GET", "/v1/permission", null, null, null, new TypeReference<TeamPermissionsSetRequestPermissionsItemEnum>(){}, "getAllPermissions", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class SetTeamPermissionsRequest {

        private List<TeamPermissionsSetRequestPermissionsItemEnum> permissions;
        private String team;

        private SetTeamPermissionsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final SetTeamPermissionsRequest request = new SetTeamPermissionsRequest();
            public Builder permissions(List<TeamPermissionsSetRequestPermissionsItemEnum> val) { request.permissions = val; return this; }
            public Builder team(String val) { request.team = val; return this; }
            public SetTeamPermissionsRequest build() { return request; }
        }
        public List<TeamPermissionsSetRequestPermissionsItemEnum> getPermissions() { return permissions; }
        public String getTeam() { return team; }
    }

    /**
     * Replaces a team's permissions with the supplied list. Provide `team` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static Team setTeamPermissions(SdkConfig.ClientConfig clientConfig, SetTeamPermissionsRequest request) {
        return setTeamPermissions(clientConfig, request, null);
    }

    /**
     * Replaces a team's permissions with the supplied list. Provide `team` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static Team setTeamPermissions(SdkConfig.ClientConfig clientConfig, SetTeamPermissionsRequest request, SdkConfig.RequestOptions options) {
        List<TeamPermissionsSetRequestPermissionsItemEnum> permissions = request.getPermissions();
        String team = request.getTeam();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("team", team, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/permission/team", null, SdkClient.q("permissions", permissions, "team", team), null, new TypeReference<Team>(){}, "setTeamPermissions", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class SetUserPermissionsRequest {

        private List<TeamPermissionsSetRequestPermissionsItemEnum> permissions;
        private String username;

        private SetUserPermissionsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final SetUserPermissionsRequest request = new SetUserPermissionsRequest();
            public Builder permissions(List<TeamPermissionsSetRequestPermissionsItemEnum> val) { request.permissions = val; return this; }
            public Builder username(String val) { request.username = val; return this; }
            public SetUserPermissionsRequest build() { return request; }
        }
        public List<TeamPermissionsSetRequestPermissionsItemEnum> getPermissions() { return permissions; }
        public String getUsername() { return username; }
    }

    /**
     * Replaces a user's permissions with the supplied list. Provide `username` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static User setUserPermissions(SdkConfig.ClientConfig clientConfig, SetUserPermissionsRequest request) {
        return setUserPermissions(clientConfig, request, null);
    }

    /**
     * Replaces a user's permissions with the supplied list. Provide `username` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static User setUserPermissions(SdkConfig.ClientConfig clientConfig, SetUserPermissionsRequest request, SdkConfig.RequestOptions options) {
        List<TeamPermissionsSetRequestPermissionsItemEnum> permissions = request.getPermissions();
        String username = request.getUsername();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("username", username, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/permission/user", null, SdkClient.q("permissions", permissions, "username", username), null, new TypeReference<User>(){}, "setUserPermissions", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RemovePermissionFromTeamRequest {

        private String uuid;
        private String permission;

        private RemovePermissionFromTeamRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RemovePermissionFromTeamRequest request = new RemovePermissionFromTeamRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder permission(String val) { request.permission = val; return this; }
            public RemovePermissionFromTeamRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getPermission() { return permission; }
    }

    /**
     * Removes a permission from a team. Supply the team UUID in `uuid` and the permission to remove in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_DELETE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Team removePermissionFromTeam(SdkConfig.ClientConfig clientConfig, RemovePermissionFromTeamRequest request) {
        return removePermissionFromTeam(clientConfig, request, null);
    }

    /**
     * Removes a permission from a team. Supply the team UUID in `uuid` and the permission to remove in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_DELETE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static Team removePermissionFromTeam(SdkConfig.ClientConfig clientConfig, RemovePermissionFromTeamRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String permission = request.getPermission();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/permission/" + SdkClient.encodePathSegment(permission) + "/team/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Team>(){}, "removePermissionFromTeam", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddPermissionToTeamRequest {

        private String uuid;
        private String permission;

        private AddPermissionToTeamRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddPermissionToTeamRequest request = new AddPermissionToTeamRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder permission(String val) { request.permission = val; return this; }
            public AddPermissionToTeamRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getPermission() { return permission; }
    }

    /**
     * Adds a permission to a team. Supply the team UUID in `uuid` and a valid permission in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static Team addPermissionToTeam(SdkConfig.ClientConfig clientConfig, AddPermissionToTeamRequest request) {
        return addPermissionToTeam(clientConfig, request, null);
    }

    /**
     * Adds a permission to a team. Supply the team UUID in `uuid` and a valid permission in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static Team addPermissionToTeam(SdkConfig.ClientConfig clientConfig, AddPermissionToTeamRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String permission = request.getPermission();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "POST", "/v1/permission/" + SdkClient.encodePathSegment(permission) + "/team/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Team>(){}, "addPermissionToTeam", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RemovePermissionFromUserRequest {

        private String username;
        private String permission;

        private RemovePermissionFromUserRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RemovePermissionFromUserRequest request = new RemovePermissionFromUserRequest();
            public Builder username(String val) { request.username = val; return this; }
            public Builder permission(String val) { request.permission = val; return this; }
            public RemovePermissionFromUserRequest build() { return request; }
        }
        public String getUsername() { return username; }
        public String getPermission() { return permission; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static User removePermissionFromUser(SdkConfig.ClientConfig clientConfig, RemovePermissionFromUserRequest request) {
        return removePermissionFromUser(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
     */
    public static User removePermissionFromUser(SdkConfig.ClientConfig clientConfig, RemovePermissionFromUserRequest request, SdkConfig.RequestOptions options) {
        String username = request.getUsername();
        String permission = request.getPermission();

        return SdkClient.request(clientConfig, "DELETE", "/v1/permission/" + SdkClient.encodePathSegment(permission) + "/user/" + SdkClient.encodePathSegment(username) + "", null, null, null, new TypeReference<User>(){}, "removePermissionFromUser", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddPermissionToUserRequest {

        private String username;
        private String permission;

        private AddPermissionToUserRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddPermissionToUserRequest request = new AddPermissionToUserRequest();
            public Builder username(String val) { request.username = val; return this; }
            public Builder permission(String val) { request.permission = val; return this; }
            public AddPermissionToUserRequest build() { return request; }
        }
        public String getUsername() { return username; }
        public String getPermission() { return permission; }
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static User addPermissionToUser(SdkConfig.ClientConfig clientConfig, AddPermissionToUserRequest request) {
        return addPermissionToUser(clientConfig, request, null);
    }

    /**
     * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
     */
    public static User addPermissionToUser(SdkConfig.ClientConfig clientConfig, AddPermissionToUserRequest request, SdkConfig.RequestOptions options) {
        String username = request.getUsername();
        String permission = request.getPermission();

        return SdkClient.request(clientConfig, "POST", "/v1/permission/" + SdkClient.encodePathSegment(permission) + "/user/" + SdkClient.encodePathSegment(username) + "", null, null, null, new TypeReference<User>(){}, "addPermissionToUser", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
