// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.shared.Project;
import dependencytrackunofficialsdk.models.shared.Tag;
import dependencytrackunofficialsdk.models.shared_policy.Policy;
import dependencytrackunofficialsdk.models.shared_policy.PolicyCondition;
import dependencytrackunofficialsdk.models.shared_policy.PolicyOperatorEnum;
import dependencytrackunofficialsdk.models.shared_policy.PolicyViolationStateEnum;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class PolicyApi {

    public static final class GetPoliciesSortOrder {
        public static final GetPoliciesSortOrder DESC = new GetPoliciesSortOrder(" desc");
        public static final GetPoliciesSortOrder ASC = new GetPoliciesSortOrder("asc");
        private final String value;
        private GetPoliciesSortOrder(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
        @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
        public static GetPoliciesSortOrder fromValue(String value) {
            if (" desc".equals(value)) return DESC;
            if ("asc".equals(value)) return ASC;
            return new GetPoliciesSortOrder(value);
        }
        @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
        @java.lang.Override public String toString() { return value; }
        @java.lang.Override public boolean equals(Object other) {
            return this == other || (other instanceof GetPoliciesSortOrder o && value.equals(o.value));
        }
        @java.lang.Override public int hashCode() { return value.hashCode(); }
    }

    public static class GetPoliciesRequest {

        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetPoliciesSortOrder sortOrder;

        private GetPoliciesRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetPoliciesRequest request = new GetPoliciesRequest();
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetPoliciesSortOrder val) { request.sortOrder = val; return this; }
            public GetPoliciesRequest build() { return request; }
        }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetPoliciesSortOrder getSortOrder() { return sortOrder; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
     */
    public static List<Policy> getPolicies(SdkConfig.ClientConfig clientConfig, GetPoliciesRequest request) {
        return getPolicies(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
     */
    public static List<Policy> getPolicies(SdkConfig.ClientConfig clientConfig, GetPoliciesRequest request, SdkConfig.RequestOptions options) {
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetPoliciesSortOrder sortOrder = request.getSortOrder();

        return SdkClient.request(clientConfig, "GET", "/v1/policy", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true)), null, null, new TypeReference<List<Policy>>(){}, "getPolicies", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdatePolicyRequest {

        private String name;
        private PolicyOperatorEnum operator;
        private String uuid;
        private PolicyViolationStateEnum violationState;
        private Boolean global;
        private Boolean includeChildren;
        private Boolean invertTagMatch;
        private Boolean onlyLatestProjectVersion;
        private List<PolicyCondition> policyConditions;
        private List<Project> projects;
        private List<Tag> tags;

        private UpdatePolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdatePolicyRequest request = new UpdatePolicyRequest();
            public Builder name(String val) { request.name = val; return this; }
            public Builder operator(PolicyOperatorEnum val) { request.operator = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder violationState(PolicyViolationStateEnum val) { request.violationState = val; return this; }
            public Builder global(Boolean val) { request.global = val; return this; }
            public Builder includeChildren(Boolean val) { request.includeChildren = val; return this; }
            public Builder invertTagMatch(Boolean val) { request.invertTagMatch = val; return this; }
            public Builder onlyLatestProjectVersion(Boolean val) { request.onlyLatestProjectVersion = val; return this; }
            public Builder policyConditions(List<PolicyCondition> val) { request.policyConditions = val; return this; }
            public Builder projects(List<Project> val) { request.projects = val; return this; }
            public Builder tags(List<Tag> val) { request.tags = val; return this; }
            public UpdatePolicyRequest build() { return request; }
        }
        public String getName() { return name; }
        public PolicyOperatorEnum getOperator() { return operator; }
        public String getUuid() { return uuid; }
        public PolicyViolationStateEnum getViolationState() { return violationState; }
        public Boolean getGlobal() { return global; }
        public Boolean getIncludeChildren() { return includeChildren; }
        public Boolean getInvertTagMatch() { return invertTagMatch; }
        public Boolean getOnlyLatestProjectVersion() { return onlyLatestProjectVersion; }
        public List<PolicyCondition> getPolicyConditions() { return policyConditions; }
        public List<Project> getProjects() { return projects; }
        public List<Tag> getTags() { return tags; }
    }

    /**
     * Updates an existing policy. If you submit a request body, include `name`, `operator`, `uuid`, and `violationState`; the body itself may be omitted. The authenticated user must have `POLICY_MANAGEMENT` or `POLICY_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Policy updatePolicy(SdkConfig.ClientConfig clientConfig, UpdatePolicyRequest request) {
        return updatePolicy(clientConfig, request, null);
    }

    /**
     * Updates an existing policy. If you submit a request body, include `name`, `operator`, `uuid`, and `violationState`; the body itself may be omitted. The authenticated user must have `POLICY_MANAGEMENT` or `POLICY_MANAGEMENT_UPDATE` permission.
     *
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Policy updatePolicy(SdkConfig.ClientConfig clientConfig, UpdatePolicyRequest request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        PolicyOperatorEnum operator = request.getOperator();
        String uuid = request.getUuid();
        PolicyViolationStateEnum violationState = request.getViolationState();
        Boolean global = request.getGlobal();
        Boolean includeChildren = request.getIncludeChildren();
        Boolean invertTagMatch = request.getInvertTagMatch();
        Boolean onlyLatestProjectVersion = request.getOnlyLatestProjectVersion();
        List<PolicyCondition> policyConditions = request.getPolicyConditions();
        List<Project> projects = request.getProjects();
        List<Tag> tags = request.getTags();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("operator", operator, __l); }

        Validation.validateUuid("uuid", uuid);

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("violationState", violationState, __l); }

        return SdkClient.request(clientConfig, "POST", "/v1/policy", null, SdkClient.q("name", name, "operator", operator, "uuid", uuid, "violationState", violationState, "global", SdkClient.omitIfNull(global), "includeChildren", SdkClient.omitIfNull(includeChildren), "invertTagMatch", SdkClient.omitIfNull(invertTagMatch), "onlyLatestProjectVersion", SdkClient.omitIfNull(onlyLatestProjectVersion), "policyConditions", SdkClient.omitIfNull(policyConditions), "projects", SdkClient.omitIfNull(projects), "tags", SdkClient.omitIfNull(tags)), null, new TypeReference<Policy>(){}, "updatePolicy", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreatePolicyRequest {

        private String name;
        private PolicyOperatorEnum operator;
        private String uuid;
        private PolicyViolationStateEnum violationState;
        private Boolean global;
        private Boolean includeChildren;
        private Boolean invertTagMatch;
        private Boolean onlyLatestProjectVersion;
        private List<PolicyCondition> policyConditions;
        private List<Project> projects;
        private List<Tag> tags;

        private CreatePolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreatePolicyRequest request = new CreatePolicyRequest();
            public Builder name(String val) { request.name = val; return this; }
            public Builder operator(PolicyOperatorEnum val) { request.operator = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder violationState(PolicyViolationStateEnum val) { request.violationState = val; return this; }
            public Builder global(Boolean val) { request.global = val; return this; }
            public Builder includeChildren(Boolean val) { request.includeChildren = val; return this; }
            public Builder invertTagMatch(Boolean val) { request.invertTagMatch = val; return this; }
            public Builder onlyLatestProjectVersion(Boolean val) { request.onlyLatestProjectVersion = val; return this; }
            public Builder policyConditions(List<PolicyCondition> val) { request.policyConditions = val; return this; }
            public Builder projects(List<Project> val) { request.projects = val; return this; }
            public Builder tags(List<Tag> val) { request.tags = val; return this; }
            public CreatePolicyRequest build() { return request; }
        }
        public String getName() { return name; }
        public PolicyOperatorEnum getOperator() { return operator; }
        public String getUuid() { return uuid; }
        public PolicyViolationStateEnum getViolationState() { return violationState; }
        public Boolean getGlobal() { return global; }
        public Boolean getIncludeChildren() { return includeChildren; }
        public Boolean getInvertTagMatch() { return invertTagMatch; }
        public Boolean getOnlyLatestProjectVersion() { return onlyLatestProjectVersion; }
        public List<PolicyCondition> getPolicyConditions() { return policyConditions; }
        public List<Project> getProjects() { return projects; }
        public List<Tag> getTags() { return tags; }
    }

    /**
     * Creates a new policy. If you submit a request body, include `name`, `operator`, `uuid`, and `violationState`; the body itself may be omitted. The authenticated user must have `POLICY_MANAGEMENT` or `POLICY_MANAGEMENT_CREATE` permission.
     *
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_CREATE
     */
    public static Policy createPolicy(SdkConfig.ClientConfig clientConfig, CreatePolicyRequest request) {
        return createPolicy(clientConfig, request, null);
    }

    /**
     * Creates a new policy. If you submit a request body, include `name`, `operator`, `uuid`, and `violationState`; the body itself may be omitted. The authenticated user must have `POLICY_MANAGEMENT` or `POLICY_MANAGEMENT_CREATE` permission.
     *
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_CREATE
     */
    public static Policy createPolicy(SdkConfig.ClientConfig clientConfig, CreatePolicyRequest request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        PolicyOperatorEnum operator = request.getOperator();
        String uuid = request.getUuid();
        PolicyViolationStateEnum violationState = request.getViolationState();
        Boolean global = request.getGlobal();
        Boolean includeChildren = request.getIncludeChildren();
        Boolean invertTagMatch = request.getInvertTagMatch();
        Boolean onlyLatestProjectVersion = request.getOnlyLatestProjectVersion();
        List<PolicyCondition> policyConditions = request.getPolicyConditions();
        List<Project> projects = request.getProjects();
        List<Tag> tags = request.getTags();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("operator", operator, __l); }

        Validation.validateUuid("uuid", uuid);

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("violationState", violationState, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/policy", null, SdkClient.q("name", name, "operator", operator, "uuid", uuid, "violationState", violationState, "global", SdkClient.omitIfNull(global), "includeChildren", SdkClient.omitIfNull(includeChildren), "invertTagMatch", SdkClient.omitIfNull(invertTagMatch), "onlyLatestProjectVersion", SdkClient.omitIfNull(onlyLatestProjectVersion), "policyConditions", SdkClient.omitIfNull(policyConditions), "projects", SdkClient.omitIfNull(projects), "tags", SdkClient.omitIfNull(tags)), null, new TypeReference<Policy>(){}, "createPolicy", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class RemoveProjectFromPolicyRequest {

        private String policyUuid;
        private String projectUuid;

        private RemoveProjectFromPolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final RemoveProjectFromPolicyRequest request = new RemoveProjectFromPolicyRequest();
            public Builder policyUuid(String val) { request.policyUuid = val; return this; }
            public Builder projectUuid(String val) { request.projectUuid = val; return this; }
            public RemoveProjectFromPolicyRequest build() { return request; }
        }
        public String getPolicyUuid() { return policyUuid; }
        public String getProjectUuid() { return projectUuid; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
     */
    public static Policy removeProjectFromPolicy(SdkConfig.ClientConfig clientConfig, RemoveProjectFromPolicyRequest request) {
        return removeProjectFromPolicy(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
     */
    public static Policy removeProjectFromPolicy(SdkConfig.ClientConfig clientConfig, RemoveProjectFromPolicyRequest request, SdkConfig.RequestOptions options) {
        String policyUuid = request.getPolicyUuid();
        String projectUuid = request.getProjectUuid();

        Validation.validateUuid("policyUuid", policyUuid);

        Validation.validateUuid("projectUuid", projectUuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/policy/" + SdkClient.encodePathSegment(policyUuid) + "/project/" + SdkClient.encodePathSegment(projectUuid) + "", null, null, null, new TypeReference<Policy>(){}, "removeProjectFromPolicy", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class AddProjectToPolicyRequest {

        private String policyUuid;
        private String projectUuid;

        private AddProjectToPolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final AddProjectToPolicyRequest request = new AddProjectToPolicyRequest();
            public Builder policyUuid(String val) { request.policyUuid = val; return this; }
            public Builder projectUuid(String val) { request.projectUuid = val; return this; }
            public AddProjectToPolicyRequest build() { return request; }
        }
        public String getPolicyUuid() { return policyUuid; }
        public String getProjectUuid() { return projectUuid; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Policy addProjectToPolicy(SdkConfig.ClientConfig clientConfig, AddProjectToPolicyRequest request) {
        return addProjectToPolicy(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Policy addProjectToPolicy(SdkConfig.ClientConfig clientConfig, AddProjectToPolicyRequest request, SdkConfig.RequestOptions options) {
        String policyUuid = request.getPolicyUuid();
        String projectUuid = request.getProjectUuid();

        Validation.validateUuid("policyUuid", policyUuid);

        Validation.validateUuid("projectUuid", projectUuid);

        return SdkClient.request(clientConfig, "POST", "/v1/policy/" + SdkClient.encodePathSegment(policyUuid) + "/project/" + SdkClient.encodePathSegment(projectUuid) + "", null, null, null, new TypeReference<Policy>(){}, "addProjectToPolicy", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeletePolicyRequest {

        private String uuid;

        private DeletePolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeletePolicyRequest request = new DeletePolicyRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeletePolicyRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
     */
    public static Object deletePolicy(SdkConfig.ClientConfig clientConfig, DeletePolicyRequest request) {
        return deletePolicy(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
     */
    public static Object deletePolicy(SdkConfig.ClientConfig clientConfig, DeletePolicyRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/policy/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deletePolicy", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetPolicyRequest {

        private String uuid;

        private GetPolicyRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetPolicyRequest request = new GetPolicyRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetPolicyRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
     */
    public static Policy getPolicy(SdkConfig.ClientConfig clientConfig, GetPolicyRequest request) {
        return getPolicy(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
     */
    public static Policy getPolicy(SdkConfig.ClientConfig clientConfig, GetPolicyRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/policy/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Policy>(){}, "getPolicy", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
