// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.policy_condition.CreatePolicyConditionRequestOperatorEnum;
import dependencytrackunofficialsdk.models.policy_condition.CreatePolicyConditionRequestSubjectEnum;
import dependencytrackunofficialsdk.models.policy_condition.CreatePolicyConditionRequestViolationTypeEnum;
import dependencytrackunofficialsdk.models.policy_condition.PolicyConditionResponse;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;

public class PolicyConditionApi {

    public static class UpdatePolicyConditionParams {

        private CreatePolicyConditionRequestOperatorEnum operator;
        private CreatePolicyConditionRequestSubjectEnum subject;
        private String uuid;
        private String value;
        private CreatePolicyConditionRequestViolationTypeEnum violationType;

        private UpdatePolicyConditionParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdatePolicyConditionParams request = new UpdatePolicyConditionParams();
            public Builder operator(CreatePolicyConditionRequestOperatorEnum val) { request.operator = val; return this; }
            public Builder subject(CreatePolicyConditionRequestSubjectEnum val) { request.subject = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder value(String val) { request.value = val; return this; }
            public Builder violationType(CreatePolicyConditionRequestViolationTypeEnum val) { request.violationType = val; return this; }
            public UpdatePolicyConditionParams build() { return request; }
        }
        public CreatePolicyConditionRequestOperatorEnum getOperator() { return operator; }
        public CreatePolicyConditionRequestSubjectEnum getSubject() { return subject; }
        public String getUuid() { return uuid; }
        public String getValue() { return value; }
        public CreatePolicyConditionRequestViolationTypeEnum getViolationType() { return violationType; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static PolicyConditionResponse updatePolicyCondition(SdkConfig.ClientConfig clientConfig, UpdatePolicyConditionParams request) {
        return updatePolicyCondition(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static PolicyConditionResponse updatePolicyCondition(SdkConfig.ClientConfig clientConfig, UpdatePolicyConditionParams request, SdkConfig.RequestOptions options) {
        CreatePolicyConditionRequestOperatorEnum operator = request.getOperator();
        CreatePolicyConditionRequestSubjectEnum subject = request.getSubject();
        String uuid = request.getUuid();
        String value = request.getValue();
        CreatePolicyConditionRequestViolationTypeEnum violationType = request.getViolationType();

        Validation.validateUuid("uuid", uuid);

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("value", value, __l); }

        return SdkClient.request(clientConfig, "POST", "/v1/policy/condition", null, SdkClient.q("operator", operator, "subject", subject, "uuid", uuid, "value", value, "violationType", SdkClient.omitIfNull(violationType)), null, new TypeReference<PolicyConditionResponse>(){}, "updatePolicyCondition", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeletePolicyConditionRequest {

        private String uuid;

        private DeletePolicyConditionRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeletePolicyConditionRequest request = new DeletePolicyConditionRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeletePolicyConditionRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Object deletePolicyCondition(SdkConfig.ClientConfig clientConfig, DeletePolicyConditionRequest request) {
        return deletePolicyCondition(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static Object deletePolicyCondition(SdkConfig.ClientConfig clientConfig, DeletePolicyConditionRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/policy/condition/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deletePolicyCondition", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class CreatePolicyConditionParams {

        private String uuid;
        private CreatePolicyConditionRequestOperatorEnum operator;
        private CreatePolicyConditionRequestSubjectEnum subject;
        private String value;
        private CreatePolicyConditionRequestViolationTypeEnum violationType;

        private CreatePolicyConditionParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreatePolicyConditionParams request = new CreatePolicyConditionParams();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder operator(CreatePolicyConditionRequestOperatorEnum val) { request.operator = val; return this; }
            public Builder subject(CreatePolicyConditionRequestSubjectEnum val) { request.subject = val; return this; }
            public Builder value(String val) { request.value = val; return this; }
            public Builder violationType(CreatePolicyConditionRequestViolationTypeEnum val) { request.violationType = val; return this; }
            public CreatePolicyConditionParams build() { return request; }
        }
        public String getUuid() { return uuid; }
        public CreatePolicyConditionRequestOperatorEnum getOperator() { return operator; }
        public CreatePolicyConditionRequestSubjectEnum getSubject() { return subject; }
        public String getValue() { return value; }
        public CreatePolicyConditionRequestViolationTypeEnum getViolationType() { return violationType; }
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static PolicyConditionResponse createPolicyCondition(SdkConfig.ClientConfig clientConfig, CreatePolicyConditionParams request) {
        return createPolicyCondition(clientConfig, request, null);
    }

    /**
     * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
     */
    public static PolicyConditionResponse createPolicyCondition(SdkConfig.ClientConfig clientConfig, CreatePolicyConditionParams request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        CreatePolicyConditionRequestOperatorEnum operator = request.getOperator();
        CreatePolicyConditionRequestSubjectEnum subject = request.getSubject();
        String value = request.getValue();
        CreatePolicyConditionRequestViolationTypeEnum violationType = request.getViolationType();

        Validation.validateUuid("uuid", uuid);

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("value", value, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/policy/" + SdkClient.encodePathSegment(uuid) + "/condition", null, SdkClient.q("operator", operator, "subject", subject, "value", value, "violationType", SdkClient.omitIfNull(violationType)), null, new TypeReference<PolicyConditionResponse>(){}, "createPolicyCondition", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
