// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.repository.CreateRepositoryRequestTypeEnum;
import dependencytrackunofficialsdk.models.repository.RepositoryResponse;
import dependencytrackunofficialsdk.models.shared.RepositoryMetaComponent;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Repository {

    public static final class GetRepositoriesSortOrder {
        public static final GetRepositoriesSortOrder DESC = new GetRepositoriesSortOrder(" desc");
        public static final GetRepositoriesSortOrder ASC = new GetRepositoriesSortOrder("asc");
        private final String value;
        private GetRepositoriesSortOrder(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
        @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
        public static GetRepositoriesSortOrder fromValue(String value) {
            if (" desc".equals(value)) return DESC;
            if ("asc".equals(value)) return ASC;
            return new GetRepositoriesSortOrder(value);
        }
        @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
        @java.lang.Override public String toString() { return value; }
        @java.lang.Override public boolean equals(Object other) {
            return this == other || (other instanceof GetRepositoriesSortOrder o && value.equals(o.value));
        }
        @java.lang.Override public int hashCode() { return value.hashCode(); }
    }

    public static class GetRepositoriesRequest {

        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetRepositoriesSortOrder sortOrder;

        private GetRepositoriesRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetRepositoriesRequest request = new GetRepositoriesRequest();
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetRepositoriesSortOrder val) { request.sortOrder = val; return this; }
            public GetRepositoriesRequest build() { return request; }
        }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetRepositoriesSortOrder getSortOrder() { return sortOrder; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<RepositoryResponse> getRepositories(SdkConfig.ClientConfig clientConfig, GetRepositoriesRequest request) {
        return getRepositories(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<RepositoryResponse> getRepositories(SdkConfig.ClientConfig clientConfig, GetRepositoriesRequest request, SdkConfig.RequestOptions options) {
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetRepositoriesSortOrder sortOrder = request.getSortOrder();

        return SdkClient.request(clientConfig, "GET", "/v1/repository", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true)), null, null, new TypeReference<List<RepositoryResponse>>(){}, "getRepositories", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UpdateRepositoryParams {

        private Boolean authenticationRequired;
        private Boolean enabled;
        private String url;
        private String uuid;
        private Boolean internal;
        private String password;
        private String username;

        private UpdateRepositoryParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateRepositoryParams request = new UpdateRepositoryParams();
            public Builder authenticationRequired(Boolean val) { request.authenticationRequired = val; return this; }
            public Builder enabled(Boolean val) { request.enabled = val; return this; }
            public Builder url(String val) { request.url = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder internal(Boolean val) { request.internal = val; return this; }
            public Builder password(String val) { request.password = val; return this; }
            public Builder username(String val) { request.username = val; return this; }
            public UpdateRepositoryParams build() { return request; }
        }
        public Boolean getAuthenticationRequired() { return authenticationRequired; }
        public Boolean getEnabled() { return enabled; }
        public String getUrl() { return url; }
        public String getUuid() { return uuid; }
        public Boolean getInternal() { return internal; }
        public String getPassword() { return password; }
        public String getUsername() { return username; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static RepositoryResponse updateRepository(SdkConfig.ClientConfig clientConfig, UpdateRepositoryParams request) {
        return updateRepository(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
     */
    public static RepositoryResponse updateRepository(SdkConfig.ClientConfig clientConfig, UpdateRepositoryParams request, SdkConfig.RequestOptions options) {
        Boolean authenticationRequired = request.getAuthenticationRequired();
        Boolean enabled = request.getEnabled();
        String url = request.getUrl();
        String uuid = request.getUuid();
        Boolean internal = request.getInternal();
        String password = request.getPassword();
        String username = request.getUsername();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("url", url, __l); }

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "POST", "/v1/repository", null, SdkClient.q("authenticationRequired", authenticationRequired, "enabled", enabled, "url", url, "uuid", uuid, "internal", SdkClient.omitIfNull(internal), "password", SdkClient.omitIfNull(password), "username", SdkClient.omitIfNull(username)), null, new TypeReference<RepositoryResponse>(){}, "updateRepository", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateRepositoryParams {

        private Boolean authenticationRequired;
        private Boolean enabled;
        private String identifier;
        private CreateRepositoryRequestTypeEnum type;
        private String url;
        private Boolean internal;
        private String password;
        private String username;

        private CreateRepositoryParams() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateRepositoryParams request = new CreateRepositoryParams();
            public Builder authenticationRequired(Boolean val) { request.authenticationRequired = val; return this; }
            public Builder enabled(Boolean val) { request.enabled = val; return this; }
            public Builder identifier(String val) { request.identifier = val; return this; }
            public Builder type(CreateRepositoryRequestTypeEnum val) { request.type = val; return this; }
            public Builder url(String val) { request.url = val; return this; }
            public Builder internal(Boolean val) { request.internal = val; return this; }
            public Builder password(String val) { request.password = val; return this; }
            public Builder username(String val) { request.username = val; return this; }
            public CreateRepositoryParams build() { return request; }
        }
        public Boolean getAuthenticationRequired() { return authenticationRequired; }
        public Boolean getEnabled() { return enabled; }
        public String getIdentifier() { return identifier; }
        public CreateRepositoryRequestTypeEnum getType() { return type; }
        public String getUrl() { return url; }
        public Boolean getInternal() { return internal; }
        public String getPassword() { return password; }
        public String getUsername() { return username; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static RepositoryResponse createRepository(SdkConfig.ClientConfig clientConfig, CreateRepositoryParams request) {
        return createRepository(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
     */
    public static RepositoryResponse createRepository(SdkConfig.ClientConfig clientConfig, CreateRepositoryParams request, SdkConfig.RequestOptions options) {
        Boolean authenticationRequired = request.getAuthenticationRequired();
        Boolean enabled = request.getEnabled();
        String identifier = request.getIdentifier();
        CreateRepositoryRequestTypeEnum type = request.getType();
        String url = request.getUrl();
        Boolean internal = request.getInternal();
        String password = request.getPassword();
        String username = request.getUsername();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("identifier", identifier, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("url", url, __l); }

        return SdkClient.request(clientConfig, "PUT", "/v1/repository", null, SdkClient.q("authenticationRequired", authenticationRequired, "enabled", enabled, "identifier", identifier, "type", type, "url", url, "internal", SdkClient.omitIfNull(internal), "password", SdkClient.omitIfNull(password), "username", SdkClient.omitIfNull(username)), null, new TypeReference<RepositoryResponse>(){}, "createRepository", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetRepositoryMetaComponentRequest {

        private String purl;

        private GetRepositoryMetaComponentRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetRepositoryMetaComponentRequest request = new GetRepositoryMetaComponentRequest();
            public Builder purl(String val) { request.purl = val; return this; }
            public GetRepositoryMetaComponentRequest build() { return request; }
        }
        public String getPurl() { return purl; }
    }

    /**
     * Retrieves the latest available version metadata for a component from configured repositories. Supply `purl` as a valid Package URL; when metadata is available, the response includes the latest version and publication timestamp.
     */
    public static RepositoryMetaComponent getRepositoryMetaComponent(SdkConfig.ClientConfig clientConfig, GetRepositoryMetaComponentRequest request) {
        return getRepositoryMetaComponent(clientConfig, request, null);
    }

    /**
     * Retrieves the latest available version metadata for a component from configured repositories. Supply `purl` as a valid Package URL; when metadata is available, the response includes the latest version and publication timestamp.
     */
    public static RepositoryMetaComponent getRepositoryMetaComponent(SdkConfig.ClientConfig clientConfig, GetRepositoryMetaComponentRequest request, SdkConfig.RequestOptions options) {
        String purl = request.getPurl();

        return SdkClient.request(clientConfig, "GET", "/v1/repository/latest", SdkClient.q("purl", SdkClient.queryValue(purl, "form", true)), null, null, new TypeReference<RepositoryMetaComponent>(){}, "getRepositoryMetaComponent", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetRepositoriesByTypeRequest {

        private CreateRepositoryRequestTypeEnum type;
        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetRepositoriesSortOrder sortOrder;

        private GetRepositoriesByTypeRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetRepositoriesByTypeRequest request = new GetRepositoriesByTypeRequest();
            public Builder type(CreateRepositoryRequestTypeEnum val) { request.type = val; return this; }
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetRepositoriesSortOrder val) { request.sortOrder = val; return this; }
            public GetRepositoriesByTypeRequest build() { return request; }
        }
        public CreateRepositoryRequestTypeEnum getType() { return type; }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetRepositoriesSortOrder getSortOrder() { return sortOrder; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<RepositoryResponse> getRepositoriesByType(SdkConfig.ClientConfig clientConfig, GetRepositoriesByTypeRequest request) {
        return getRepositoriesByType(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
     */
    public static List<RepositoryResponse> getRepositoriesByType(SdkConfig.ClientConfig clientConfig, GetRepositoriesByTypeRequest request, SdkConfig.RequestOptions options) {
        CreateRepositoryRequestTypeEnum type = request.getType();
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetRepositoriesSortOrder sortOrder = request.getSortOrder();

        return SdkClient.request(clientConfig, "GET", "/v1/repository/" + SdkClient.encodePathSegment(type) + "", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true)), null, null, new TypeReference<List<RepositoryResponse>>(){}, "getRepositoriesByType", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteRepositoryRequest {

        private String uuid;

        private DeleteRepositoryRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteRepositoryRequest request = new DeleteRepositoryRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteRepositoryRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteRepository(SdkConfig.ClientConfig clientConfig, DeleteRepositoryRequest request) {
        return deleteRepository(clientConfig, request, null);
    }

    /**
     * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
     */
    public static Object deleteRepository(SdkConfig.ClientConfig clientConfig, DeleteRepositoryRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/repository/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteRepository", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }



}
