// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.shared.DataClassification;
import dependencytrackunofficialsdk.models.shared.ExternalReference;
import dependencytrackunofficialsdk.models.shared.Project;
import dependencytrackunofficialsdk.models.shared.ServiceComponent;
import dependencytrackunofficialsdk.models.shared.Vulnerability;
import dependencytrackunofficialsdk.models.shared_organizational.OrganizationalEntity;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Service {

    public static final class GetAllServicesSortOrder {
        public static final GetAllServicesSortOrder DESC = new GetAllServicesSortOrder(" desc");
        public static final GetAllServicesSortOrder ASC = new GetAllServicesSortOrder("asc");
        private final String value;
        private GetAllServicesSortOrder(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
        @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
        public static GetAllServicesSortOrder fromValue(String value) {
            if (" desc".equals(value)) return DESC;
            if ("asc".equals(value)) return ASC;
            return new GetAllServicesSortOrder(value);
        }
        @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
        @java.lang.Override public String toString() { return value; }
        @java.lang.Override public boolean equals(Object other) {
            return this == other || (other instanceof GetAllServicesSortOrder o && value.equals(o.value));
        }
        @java.lang.Override public int hashCode() { return value.hashCode(); }
    }

    public static class UpdateServiceRequest {

        private String name;
        private Project project;
        private String uuid;
        private Boolean authenticated;
        private String bomRef;
        private List<ServiceComponent> children;
        private Boolean crossesTrustBoundary;
        private List<DataClassification> data;
        private String description;
        private List<String> endpoints;
        private List<ExternalReference> externalReferences;
        private String group;
        private Double lastInheritedRiskScore;
        private String notes;
        private ServiceComponent parent;
        private OrganizationalEntity provider;
        private String version;
        private List<Vulnerability> vulnerabilities;

        private UpdateServiceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UpdateServiceRequest request = new UpdateServiceRequest();
            public Builder name(String val) { request.name = val; return this; }
            public Builder project(Project val) { request.project = val; return this; }
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder authenticated(Boolean val) { request.authenticated = val; return this; }
            public Builder bomRef(String val) { request.bomRef = val; return this; }
            public Builder children(List<ServiceComponent> val) { request.children = val; return this; }
            public Builder crossesTrustBoundary(Boolean val) { request.crossesTrustBoundary = val; return this; }
            public Builder data(List<DataClassification> val) { request.data = val; return this; }
            public Builder description(String val) { request.description = val; return this; }
            public Builder endpoints(List<String> val) { request.endpoints = val; return this; }
            public Builder externalReferences(List<ExternalReference> val) { request.externalReferences = val; return this; }
            public Builder group(String val) { request.group = val; return this; }
            public Builder lastInheritedRiskScore(Double val) { request.lastInheritedRiskScore = val; return this; }
            public Builder notes(String val) { request.notes = val; return this; }
            public Builder parent(ServiceComponent val) { request.parent = val; return this; }
            public Builder provider(OrganizationalEntity val) { request.provider = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public Builder vulnerabilities(List<Vulnerability> val) { request.vulnerabilities = val; return this; }
            public UpdateServiceRequest build() { return request; }
        }
        public String getName() { return name; }
        public Project getProject() { return project; }
        public String getUuid() { return uuid; }
        public Boolean getAuthenticated() { return authenticated; }
        public String getBomRef() { return bomRef; }
        public List<ServiceComponent> getChildren() { return children; }
        public Boolean getCrossesTrustBoundary() { return crossesTrustBoundary; }
        public List<DataClassification> getData() { return data; }
        public String getDescription() { return description; }
        public List<String> getEndpoints() { return endpoints; }
        public List<ExternalReference> getExternalReferences() { return externalReferences; }
        public String getGroup() { return group; }
        public Double getLastInheritedRiskScore() { return lastInheritedRiskScore; }
        public String getNotes() { return notes; }
        public ServiceComponent getParent() { return parent; }
        public OrganizationalEntity getProvider() { return provider; }
        public String getVersion() { return version; }
        public List<Vulnerability> getVulnerabilities() { return vulnerabilities; }
    }

    /**
     * Updates an existing service record with its metadata, data flows, references, and related project and provider information. Supply the service object with `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission. A successful response returns the updated service object.
     *
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static ServiceComponent updateService(SdkConfig.ClientConfig clientConfig, UpdateServiceRequest request) {
        return updateService(clientConfig, request, null);
    }

    /**
     * Updates an existing service record with its metadata, data flows, references, and related project and provider information. Supply the service object with `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission. A successful response returns the updated service object.
     *
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
     */
    public static ServiceComponent updateService(SdkConfig.ClientConfig clientConfig, UpdateServiceRequest request, SdkConfig.RequestOptions options) {
        String name = request.getName();
        Project project = request.getProject();
        String uuid = request.getUuid();
        Boolean authenticated = request.getAuthenticated();
        String bomRef = request.getBomRef();
        List<ServiceComponent> children = request.getChildren();
        Boolean crossesTrustBoundary = request.getCrossesTrustBoundary();
        List<DataClassification> data = request.getData();
        String description = request.getDescription();
        List<String> endpoints = request.getEndpoints();
        List<ExternalReference> externalReferences = request.getExternalReferences();
        String group = request.getGroup();
        Double lastInheritedRiskScore = request.getLastInheritedRiskScore();
        String notes = request.getNotes();
        ServiceComponent parent = request.getParent();
        OrganizationalEntity provider = request.getProvider();
        String version = request.getVersion();
        List<Vulnerability> vulnerabilities = request.getVulnerabilities();

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }

        Validation.validateUuid("uuid", uuid);

        if (description != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 1024; Validation.validateLength("description", description, __l); }
        }

        if (group != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 255; Validation.validateLength("group", group, __l); }
        }

        if (version != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 255; Validation.validateLength("version", version, __l); }
        }

        return SdkClient.request(clientConfig, "POST", "/v1/service", null, SdkClient.q("name", name, "project", project, "uuid", uuid, "authenticated", SdkClient.omitIfNull(authenticated), "bomRef", SdkClient.omitIfNull(bomRef), "children", SdkClient.omitIfNull(children), "crossesTrustBoundary", SdkClient.omitIfNull(crossesTrustBoundary), "data", SdkClient.omitIfNull(data), "description", SdkClient.omitIfNull(description), "endpoints", SdkClient.omitIfNull(endpoints), "externalReferences", SdkClient.omitIfNull(externalReferences), "group", SdkClient.omitIfNull(group), "lastInheritedRiskScore", SdkClient.omitIfNull(lastInheritedRiskScore), "notes", SdkClient.omitIfNull(notes), "parent", SdkClient.omitIfNull(parent), "provider", SdkClient.omitIfNull(provider), "version", SdkClient.omitIfNull(version), "vulnerabilities", SdkClient.omitIfNull(vulnerabilities)), null, new TypeReference<ServiceComponent>(){}, "updateService", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetAllServicesRequest {

        private String uuid;
        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetAllServicesSortOrder sortOrder;

        private GetAllServicesRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetAllServicesRequest request = new GetAllServicesRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetAllServicesSortOrder val) { request.sortOrder = val; return this; }
            public GetAllServicesRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetAllServicesSortOrder getSortOrder() { return sortOrder; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<ServiceComponent> getAllServices(SdkConfig.ClientConfig clientConfig, GetAllServicesRequest request) {
        return getAllServices(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static List<ServiceComponent> getAllServices(SdkConfig.ClientConfig clientConfig, GetAllServicesRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetAllServicesSortOrder sortOrder = request.getSortOrder();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/service/project/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true)), null, null, new TypeReference<List<ServiceComponent>>(){}, "getAllServices", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class CreateServiceRequest {

        private String uuid;
        private String name;
        private Project project;
        private String uuid_2;
        private Boolean authenticated;
        private String bomRef;
        private List<ServiceComponent> children;
        private Boolean crossesTrustBoundary;
        private List<DataClassification> data;
        private String description;
        private List<String> endpoints;
        private List<ExternalReference> externalReferences;
        private String group;
        private Double lastInheritedRiskScore;
        private String notes;
        private ServiceComponent parent;
        private OrganizationalEntity provider;
        private String version;
        private List<Vulnerability> vulnerabilities;

        private CreateServiceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final CreateServiceRequest request = new CreateServiceRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder name(String val) { request.name = val; return this; }
            public Builder project(Project val) { request.project = val; return this; }
            public Builder uuid_2(String val) { request.uuid_2 = val; return this; }
            public Builder authenticated(Boolean val) { request.authenticated = val; return this; }
            public Builder bomRef(String val) { request.bomRef = val; return this; }
            public Builder children(List<ServiceComponent> val) { request.children = val; return this; }
            public Builder crossesTrustBoundary(Boolean val) { request.crossesTrustBoundary = val; return this; }
            public Builder data(List<DataClassification> val) { request.data = val; return this; }
            public Builder description(String val) { request.description = val; return this; }
            public Builder endpoints(List<String> val) { request.endpoints = val; return this; }
            public Builder externalReferences(List<ExternalReference> val) { request.externalReferences = val; return this; }
            public Builder group(String val) { request.group = val; return this; }
            public Builder lastInheritedRiskScore(Double val) { request.lastInheritedRiskScore = val; return this; }
            public Builder notes(String val) { request.notes = val; return this; }
            public Builder parent(ServiceComponent val) { request.parent = val; return this; }
            public Builder provider(OrganizationalEntity val) { request.provider = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public Builder vulnerabilities(List<Vulnerability> val) { request.vulnerabilities = val; return this; }
            public CreateServiceRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getName() { return name; }
        public Project getProject() { return project; }
        public String getUuid2() { return uuid_2; }
        public Boolean getAuthenticated() { return authenticated; }
        public String getBomRef() { return bomRef; }
        public List<ServiceComponent> getChildren() { return children; }
        public Boolean getCrossesTrustBoundary() { return crossesTrustBoundary; }
        public List<DataClassification> getData() { return data; }
        public String getDescription() { return description; }
        public List<String> getEndpoints() { return endpoints; }
        public List<ExternalReference> getExternalReferences() { return externalReferences; }
        public String getGroup() { return group; }
        public Double getLastInheritedRiskScore() { return lastInheritedRiskScore; }
        public String getNotes() { return notes; }
        public ServiceComponent getParent() { return parent; }
        public OrganizationalEntity getProvider() { return provider; }
        public String getVersion() { return version; }
        public List<Vulnerability> getVulnerabilities() { return vulnerabilities; }
    }

    /**
     * Creates a new service for the project identified by `uuid`. When you provide a service object, include `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission. A successful response returns the created service object.
     *
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
     */
    public static ServiceComponent createService(SdkConfig.ClientConfig clientConfig, CreateServiceRequest request) {
        return createService(clientConfig, request, null);
    }

    /**
     * Creates a new service for the project identified by `uuid`. When you provide a service object, include `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission. A successful response returns the created service object.
     *
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
     */
    public static ServiceComponent createService(SdkConfig.ClientConfig clientConfig, CreateServiceRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String name = request.getName();
        Project project = request.getProject();
        String uuid_2 = request.getUuid2();
        Boolean authenticated = request.getAuthenticated();
        String bomRef = request.getBomRef();
        List<ServiceComponent> children = request.getChildren();
        Boolean crossesTrustBoundary = request.getCrossesTrustBoundary();
        List<DataClassification> data = request.getData();
        String description = request.getDescription();
        List<String> endpoints = request.getEndpoints();
        List<ExternalReference> externalReferences = request.getExternalReferences();
        String group = request.getGroup();
        Double lastInheritedRiskScore = request.getLastInheritedRiskScore();
        String notes = request.getNotes();
        ServiceComponent parent = request.getParent();
        OrganizationalEntity provider = request.getProvider();
        String version = request.getVersion();
        List<Vulnerability> vulnerabilities = request.getVulnerabilities();

        Validation.validateUuid("uuid", uuid);

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; __l.max = 255; Validation.validateLength("name", name, __l); }

        Validation.validateUuid("uuid", uuid_2);

        if (description != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 1024; Validation.validateLength("description", description, __l); }
        }

        if (group != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 255; Validation.validateLength("group", group, __l); }
        }

        if (version != null) {
            { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 0; __l.max = 255; Validation.validateLength("version", version, __l); }
        }

        return SdkClient.request(clientConfig, "PUT", "/v1/service/project/" + SdkClient.encodePathSegment(uuid) + "", null, SdkClient.q("name", name, "project", project, "uuid", uuid_2, "authenticated", SdkClient.omitIfNull(authenticated), "bomRef", SdkClient.omitIfNull(bomRef), "children", SdkClient.omitIfNull(children), "crossesTrustBoundary", SdkClient.omitIfNull(crossesTrustBoundary), "data", SdkClient.omitIfNull(data), "description", SdkClient.omitIfNull(description), "endpoints", SdkClient.omitIfNull(endpoints), "externalReferences", SdkClient.omitIfNull(externalReferences), "group", SdkClient.omitIfNull(group), "lastInheritedRiskScore", SdkClient.omitIfNull(lastInheritedRiskScore), "notes", SdkClient.omitIfNull(notes), "parent", SdkClient.omitIfNull(parent), "provider", SdkClient.omitIfNull(provider), "version", SdkClient.omitIfNull(version), "vulnerabilities", SdkClient.omitIfNull(vulnerabilities)), null, new TypeReference<ServiceComponent>(){}, "createService", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class DeleteServiceRequest {

        private String uuid;

        private DeleteServiceRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final DeleteServiceRequest request = new DeleteServiceRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public DeleteServiceRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
     */
    public static Object deleteService(SdkConfig.ClientConfig clientConfig, DeleteServiceRequest request) {
        return deleteService(clientConfig, request, null);
    }

    /**
     * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
     */
    public static Object deleteService(SdkConfig.ClientConfig clientConfig, DeleteServiceRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "DELETE", "/v1/service/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<Object>(){}, "deleteService", null, SdkClient.ResponseDecoder.EMPTY, options).data;
    }


    public static class GetServiceByUuidRequest {

        private String uuid;

        private GetServiceByUuidRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetServiceByUuidRequest request = new GetServiceByUuidRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public GetServiceByUuidRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static ServiceComponent getServiceByUuid(SdkConfig.ClientConfig clientConfig, GetServiceByUuidRequest request) {
        return getServiceByUuid(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_PORTFOLIO
     */
    public static ServiceComponent getServiceByUuid(SdkConfig.ClientConfig clientConfig, GetServiceByUuidRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/service/" + SdkClient.encodePathSegment(uuid) + "", null, null, null, new TypeReference<ServiceComponent>(){}, "getServiceByUuid", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
