// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.shared.BomUploadResponse;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;

public class Vex {

    public static class UploadVex1Request {

        private String project;
        private String projectName;
        private String projectVersion;
        private String vex;

        private UploadVex1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UploadVex1Request request = new UploadVex1Request();
            public Builder project(String val) { request.project = val; return this; }
            public Builder projectName(String val) { request.projectName = val; return this; }
            public Builder projectVersion(String val) { request.projectVersion = val; return this; }
            public Builder vex(String val) { request.vex = val; return this; }
            public UploadVex1Request build() { return request; }
        }
        public String getProject() { return project; }
        public String getProjectName() { return projectName; }
        public String getProjectVersion() { return projectVersion; }
        public String getVex() { return vex; }
    }

    /**
     * Uploads a CycloneDX VEX document for a project using multipart form data. Identify the project with `project`, or provide `projectName` and `projectVersion`; the VEX is validated against the CycloneDX schema. The authenticated user needs `VULNERABILITY_ANALYSIS` or `VULNERABILITY_ANALYSIS_UPDATE` permission, and the response includes a token for checking processing progress.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. The VEX will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
     */
    public static BomUploadResponse uploadVex1(SdkConfig.ClientConfig clientConfig, UploadVex1Request request) {
        return uploadVex1(clientConfig, request, null);
    }

    /**
     * Uploads a CycloneDX VEX document for a project using multipart form data. Identify the project with `project`, or provide `projectName` and `projectVersion`; the VEX is validated against the CycloneDX schema. The authenticated user needs `VULNERABILITY_ANALYSIS` or `VULNERABILITY_ANALYSIS_UPDATE` permission, and the response includes a token for checking processing progress.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. The VEX will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
     */
    public static BomUploadResponse uploadVex1(SdkConfig.ClientConfig clientConfig, UploadVex1Request request, SdkConfig.RequestOptions options) {
        String project = request.getProject();
        String projectName = request.getProjectName();
        String projectVersion = request.getProjectVersion();
        String vex = request.getVex();

        return SdkClient.request(clientConfig, "POST", "/v1/vex", null, SdkClient.q("project", SdkClient.omitIfNull(project), "projectName", SdkClient.omitIfNull(projectName), "projectVersion", SdkClient.omitIfNull(projectVersion), "vex", SdkClient.omitIfNull(vex)), "multipart/form-data", new TypeReference<BomUploadResponse>(){}, "uploadVex1", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class UploadVexRequest {

        private String project;
        private String projectName;
        private String projectVersion;
        private String vex;

        private UploadVexRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final UploadVexRequest request = new UploadVexRequest();
            public Builder project(String val) { request.project = val; return this; }
            public Builder projectName(String val) { request.projectName = val; return this; }
            public Builder projectVersion(String val) { request.projectVersion = val; return this; }
            public Builder vex(String val) { request.vex = val; return this; }
            public UploadVexRequest build() { return request; }
        }
        public String getProject() { return project; }
        public String getProjectName() { return projectName; }
        public String getProjectVersion() { return projectVersion; }
        public String getVex() { return vex; }
    }

    /**
     * Uploads a base64-encoded CycloneDX VEX document for a project. Provide `project`, `projectName`, `projectVersion`, and `vex`; `project` must be a UUID, and `vex` must contain valid base64-encoded data. The `vex` value is limited to 20,000,000 characters, so use POST for larger documents; the response includes a token for checking processing progress.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. The VEX will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . The maximum allowed length of the vex value is 20'000'000 characters. When uploading large VEX files, the POST endpoint is preferred, as it does not have this limit. Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
     */
    public static BomUploadResponse uploadVex(SdkConfig.ClientConfig clientConfig, UploadVexRequest request) {
        return uploadVex(clientConfig, request, null);
    }

    /**
     * Uploads a base64-encoded CycloneDX VEX document for a project. Provide `project`, `projectName`, `projectVersion`, and `vex`; `project` must be a UUID, and `vex` must contain valid base64-encoded data. The `vex` value is limited to 20,000,000 characters, so use POST for larger documents; the response includes a token for checking processing progress.
     *
     * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. The VEX will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . The maximum allowed length of the vex value is 20'000'000 characters. When uploading large VEX files, the POST endpoint is preferred, as it does not have this limit. Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
     */
    public static BomUploadResponse uploadVex(SdkConfig.ClientConfig clientConfig, UploadVexRequest request, SdkConfig.RequestOptions options) {
        String project = request.getProject();
        String projectName = request.getProjectName();
        String projectVersion = request.getProjectVersion();
        String vex = request.getVex();

        Validation.validatePattern("project", project, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("projectName", projectName, __l); }

        { Validation.LengthOpts __l = new Validation.LengthOpts(); __l.min = 1; Validation.validateLength("projectVersion", projectVersion, __l); }

        Validation.validatePattern("vex", vex, "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$");

        return SdkClient.request(clientConfig, "PUT", "/v1/vex", null, SdkClient.q("project", project, "projectName", projectName, "projectVersion", projectVersion, "vex", vex), null, new TypeReference<BomUploadResponse>(){}, "uploadVex", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class ExportProjectAsCycloneDx1Request {

        private String uuid;
        private Boolean download;
        private String version;

        private ExportProjectAsCycloneDx1Request() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final ExportProjectAsCycloneDx1Request request = new ExportProjectAsCycloneDx1Request();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder download(Boolean val) { request.download = val; return this; }
            public Builder version(String val) { request.version = val; return this; }
            public ExportProjectAsCycloneDx1Request build() { return request; }
        }
        public String getUuid() { return uuid; }
        public Boolean getDownload() { return download; }
        public String getVersion() { return version; }
    }

    /**
     * Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_READ
     */
    public static byte[] exportProjectAsCycloneDx1(SdkConfig.ClientConfig clientConfig, ExportProjectAsCycloneDx1Request request) {
        return exportProjectAsCycloneDx1(clientConfig, request, null);
    }

    /**
     * Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_READ
     */
    public static byte[] exportProjectAsCycloneDx1(SdkConfig.ClientConfig clientConfig, ExportProjectAsCycloneDx1Request request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        Boolean download = request.getDownload();
        String version = request.getVersion();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/vex/cyclonedx/project/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("download", SdkClient.queryValue(download, "form", true), "version", SdkClient.queryValue(version, "form", true)), null, null, new TypeReference<byte[]>(){}, "exportProjectAsCycloneDx1", null, SdkClient.ResponseDecoder.BYTES, options).data;
    }



}
