// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.methods;

import dependencytrackunofficialsdk.models.violation.PolicyViolation;
import dependencytrackunofficialsdk.SdkConfig;
import dependencytrackunofficialsdk.SdkClient;
import dependencytrackunofficialsdk.Validation;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

public class Violation {

    public static final class GetViolationsSortOrder {
        public static final GetViolationsSortOrder DESC = new GetViolationsSortOrder(" desc");
        public static final GetViolationsSortOrder ASC = new GetViolationsSortOrder("asc");
        private final String value;
        private GetViolationsSortOrder(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
        @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
        public static GetViolationsSortOrder fromValue(String value) {
            if (" desc".equals(value)) return DESC;
            if ("asc".equals(value)) return ASC;
            return new GetViolationsSortOrder(value);
        }
        @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
        @java.lang.Override public String toString() { return value; }
        @java.lang.Override public boolean equals(Object other) {
            return this == other || (other instanceof GetViolationsSortOrder o && value.equals(o.value));
        }
        @java.lang.Override public int hashCode() { return value.hashCode(); }
    }

    public static class GetViolationsRequest {

        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetViolationsSortOrder sortOrder;
        private Boolean suppressed;
        private Boolean showInactive;
        private String violationState;
        private String riskType;
        private String policy;
        private String analysisState;
        private String occurredOnDateFrom;
        private String occurredOnDateTo;
        private String textSearchField;
        private String textSearchInput;

        private GetViolationsRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetViolationsRequest request = new GetViolationsRequest();
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetViolationsSortOrder val) { request.sortOrder = val; return this; }
            public Builder suppressed(Boolean val) { request.suppressed = val; return this; }
            public Builder showInactive(Boolean val) { request.showInactive = val; return this; }
            public Builder violationState(String val) { request.violationState = val; return this; }
            public Builder riskType(String val) { request.riskType = val; return this; }
            public Builder policy(String val) { request.policy = val; return this; }
            public Builder analysisState(String val) { request.analysisState = val; return this; }
            public Builder occurredOnDateFrom(String val) { request.occurredOnDateFrom = val; return this; }
            public Builder occurredOnDateTo(String val) { request.occurredOnDateTo = val; return this; }
            public Builder textSearchField(String val) { request.textSearchField = val; return this; }
            public Builder textSearchInput(String val) { request.textSearchInput = val; return this; }
            public GetViolationsRequest build() { return request; }
        }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetViolationsSortOrder getSortOrder() { return sortOrder; }
        public Boolean getSuppressed() { return suppressed; }
        public Boolean getShowInactive() { return showInactive; }
        public String getViolationState() { return violationState; }
        public String getRiskType() { return riskType; }
        public String getPolicy() { return policy; }
        public String getAnalysisState() { return analysisState; }
        public String getOccurredOnDateFrom() { return occurredOnDateFrom; }
        public String getOccurredOnDateTo() { return occurredOnDateTo; }
        public String getTextSearchField() { return textSearchField; }
        public String getTextSearchInput() { return textSearchInput; }
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolations(SdkConfig.ClientConfig clientConfig, GetViolationsRequest request) {
        return getViolations(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolations(SdkConfig.ClientConfig clientConfig, GetViolationsRequest request, SdkConfig.RequestOptions options) {
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetViolationsSortOrder sortOrder = request.getSortOrder();
        Boolean suppressed = request.getSuppressed();
        Boolean showInactive = request.getShowInactive();
        String violationState = request.getViolationState();
        String riskType = request.getRiskType();
        String policy = request.getPolicy();
        String analysisState = request.getAnalysisState();
        String occurredOnDateFrom = request.getOccurredOnDateFrom();
        String occurredOnDateTo = request.getOccurredOnDateTo();
        String textSearchField = request.getTextSearchField();
        String textSearchInput = request.getTextSearchInput();

        return SdkClient.request(clientConfig, "GET", "/v1/violation", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true), "suppressed", SdkClient.queryValue(suppressed, "form", true), "showInactive", SdkClient.queryValue(showInactive, "form", true), "violationState", SdkClient.queryValue(violationState, "form", true), "riskType", SdkClient.queryValue(riskType, "form", true), "policy", SdkClient.queryValue(policy, "form", true), "analysisState", SdkClient.queryValue(analysisState, "form", true), "occurredOnDateFrom", SdkClient.queryValue(occurredOnDateFrom, "form", true), "occurredOnDateTo", SdkClient.queryValue(occurredOnDateTo, "form", true), "textSearchField", SdkClient.queryValue(textSearchField, "form", true), "textSearchInput", SdkClient.queryValue(textSearchInput, "form", true)), null, null, new TypeReference<List<PolicyViolation>>(){}, "getViolations", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetViolationsByComponentRequest {

        private String uuid;
        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetViolationsSortOrder sortOrder;
        private Boolean suppressed;

        private GetViolationsByComponentRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetViolationsByComponentRequest request = new GetViolationsByComponentRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetViolationsSortOrder val) { request.sortOrder = val; return this; }
            public Builder suppressed(Boolean val) { request.suppressed = val; return this; }
            public GetViolationsByComponentRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetViolationsSortOrder getSortOrder() { return sortOrder; }
        public Boolean getSuppressed() { return suppressed; }
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolationsByComponent(SdkConfig.ClientConfig clientConfig, GetViolationsByComponentRequest request) {
        return getViolationsByComponent(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolationsByComponent(SdkConfig.ClientConfig clientConfig, GetViolationsByComponentRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetViolationsSortOrder sortOrder = request.getSortOrder();
        Boolean suppressed = request.getSuppressed();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/violation/component/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true), "suppressed", SdkClient.queryValue(suppressed, "form", true)), null, null, new TypeReference<List<PolicyViolation>>(){}, "getViolationsByComponent", null, SdkClient.ResponseDecoder.JSON, options).data;
    }


    public static class GetViolationsByProjectRequest {

        private String uuid;
        private String pageNumber;
        private String pageSize;
        private String offset;
        private String limit;
        private String sortName;
        private GetViolationsSortOrder sortOrder;
        private Boolean suppressed;

        private GetViolationsByProjectRequest() {}

        public static Builder builder() { return new Builder(); }

        public static class Builder {
            private final GetViolationsByProjectRequest request = new GetViolationsByProjectRequest();
            public Builder uuid(String val) { request.uuid = val; return this; }
            public Builder pageNumber(String val) { request.pageNumber = val; return this; }
            public Builder pageSize(String val) { request.pageSize = val; return this; }
            public Builder offset(String val) { request.offset = val; return this; }
            public Builder limit(String val) { request.limit = val; return this; }
            public Builder sortName(String val) { request.sortName = val; return this; }
            public Builder sortOrder(GetViolationsSortOrder val) { request.sortOrder = val; return this; }
            public Builder suppressed(Boolean val) { request.suppressed = val; return this; }
            public GetViolationsByProjectRequest build() { return request; }
        }
        public String getUuid() { return uuid; }
        public String getPageNumber() { return pageNumber; }
        public String getPageSize() { return pageSize; }
        public String getOffset() { return offset; }
        public String getLimit() { return limit; }
        public String getSortName() { return sortName; }
        public GetViolationsSortOrder getSortOrder() { return sortOrder; }
        public Boolean getSuppressed() { return suppressed; }
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolationsByProject(SdkConfig.ClientConfig clientConfig, GetViolationsByProjectRequest request) {
        return getViolationsByProject(clientConfig, request, null);
    }

    /**
     * Requires permission VIEW_POLICY_VIOLATION
     */
    public static List<PolicyViolation> getViolationsByProject(SdkConfig.ClientConfig clientConfig, GetViolationsByProjectRequest request, SdkConfig.RequestOptions options) {
        String uuid = request.getUuid();
        String pageNumber = request.getPageNumber();
        String pageSize = request.getPageSize();
        String offset = request.getOffset();
        String limit = request.getLimit();
        String sortName = request.getSortName();
        GetViolationsSortOrder sortOrder = request.getSortOrder();
        Boolean suppressed = request.getSuppressed();

        Validation.validateUuid("uuid", uuid);

        return SdkClient.request(clientConfig, "GET", "/v1/violation/project/" + SdkClient.encodePathSegment(uuid) + "", SdkClient.q("pageNumber", SdkClient.queryValue(pageNumber, "form", true), "pageSize", SdkClient.queryValue(pageSize, "form", true), "offset", SdkClient.queryValue(offset, "form", true), "limit", SdkClient.queryValue(limit, "form", true), "sortName", SdkClient.queryValue(sortName, "form", true), "sortOrder", SdkClient.queryValue(sortOrder, "form", true), "suppressed", SdkClient.queryValue(suppressed, "form", true)), null, null, new TypeReference<List<PolicyViolation>>(){}, "getViolationsByProject", null, SdkClient.ResponseDecoder.JSON, options).data;
    }



}
