// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_mapped;

import dependencytrackunofficialsdk.Validation;
import dependencytrackunofficialsdk.models.shared_oidc.OidcGroup;
import javax.annotation.Nullable;

/**
 * MappedOidcGroup.
 * Typed representation of the `MappedOidcGroup` API schema.
 */

public final class MappedOidcGroup {
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Optional object value serialized in the `group` wire field.
     */
    @Nullable public OidcGroup group;
    private MappedOidcGroup() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String uuid;
        private OidcGroup group;
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder group(OidcGroup value) { this.group = value; return this; }
        public MappedOidcGroup build() {
            MappedOidcGroup result = new MappedOidcGroup();
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.group = this.group;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "MappedOidcGroup{"
            + "uuid=" + uuid
            + ", group=" + group
            + "}";
    }
}
