// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.license;

import dependencytrackunofficialsdk.Validation;
import java.util.List;
import javax.annotation.Nullable;

/**
 * CreateLicenseRequest.
 * Typed representation of the `CreateLicenseRequest` API schema.
 */

public final class CreateLicenseRequest {
    /**
     * Identifier of the license
     */
    public String licenseId;
    /**
     * Display name of the license
     */
    public String name;
    /**
     * Whether the licenseId has been deprecated by SPDX
     */
    @Nullable public Boolean isDeprecatedLicenseId;
    /**
     * Whether the license is FSF libre
     */
    @Nullable public Boolean isFsfLibre;
    /**
     * Whether the license is approved by the OSI
     */
    @Nullable public Boolean isOsiApproved;
    /**
     * Comments about the license
     */
    @Nullable public String licenseComments;
    /**
     * Full license text
     */
    @Nullable public String licenseText;
    /**
     * Additional URLs with information about the license
     */
    @Nullable public List<String> seeAlso;
    /**
     * Standard license header typically added to the top of source code
     */
    @Nullable public String standardLicenseHeader;
    /**
     * Standard license template used to derive the license text
     */
    @Nullable public String standardLicenseTemplate;
    private CreateLicenseRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String licenseId;
        private String name;
        private Boolean isDeprecatedLicenseId;
        private Boolean isFsfLibre;
        private Boolean isOsiApproved;
        private String licenseComments;
        private String licenseText;
        private List<String> seeAlso;
        private String standardLicenseHeader;
        private String standardLicenseTemplate;
        public Builder licenseId(String value) { this.licenseId = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder isDeprecatedLicenseId(Boolean value) { this.isDeprecatedLicenseId = value; return this; }
        public Builder isFsfLibre(Boolean value) { this.isFsfLibre = value; return this; }
        public Builder isOsiApproved(Boolean value) { this.isOsiApproved = value; return this; }
        public Builder licenseComments(String value) { this.licenseComments = value; return this; }
        public Builder licenseText(String value) { this.licenseText = value; return this; }
        public Builder seeAlso(List<String> value) { this.seeAlso = value; return this; }
        public Builder standardLicenseHeader(String value) { this.standardLicenseHeader = value; return this; }
        public Builder standardLicenseTemplate(String value) { this.standardLicenseTemplate = value; return this; }
        public CreateLicenseRequest build() {
            CreateLicenseRequest result = new CreateLicenseRequest();
            Validation.validateRequired("licenseId", this.licenseId);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("licenseId", this.licenseId, __length); }
            Validation.validatePattern("licenseId", this.licenseId, "^[a-zA-Z0-9_.\\-+]*$");
            result.licenseId = this.licenseId;
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            result.isDeprecatedLicenseId = this.isDeprecatedLicenseId;
            result.isFsfLibre = this.isFsfLibre;
            result.isOsiApproved = this.isOsiApproved;
            result.licenseComments = this.licenseComments;
            result.licenseText = this.licenseText;
            result.seeAlso = this.seeAlso;
            result.standardLicenseHeader = this.standardLicenseHeader;
            result.standardLicenseTemplate = this.standardLicenseTemplate;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CreateLicenseRequest{"
            + "licenseId=" + licenseId
            + ", name=" + name
            + ", isDeprecatedLicenseId=" + isDeprecatedLicenseId
            + ", isFsfLibre=" + isFsfLibre
            + ", isOsiApproved=" + isOsiApproved
            + ", licenseComments=" + licenseComments
            + ", licenseText=" + licenseText
            + ", seeAlso=" + seeAlso
            + ", standardLicenseHeader=" + standardLicenseHeader
            + ", standardLicenseTemplate=" + standardLicenseTemplate
            + "}";
    }
}
