// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.component;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * ComponentOccurrence.
 * Typed representation of the `ComponentOccurrence` API schema.
 */

public final class ComponentOccurrence {
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long createdAt;
    /**
     * Optional `uuid`-formatted value serialized in the `id` wire field.
     */
    @Nullable public String id;
    /**
     * Optional `int32`-formatted value serialized in the `line` wire field.
     */
    @Nullable public Integer line;
    /**
     * Optional `string` value serialized in the `location` wire field.
     */
    @Nullable public String location;
    /**
     * Optional `int32`-formatted value serialized in the `offset` wire field.
     */
    @Nullable public Integer offset;
    /**
     * Optional `string` value serialized in the `symbol` wire field.
     */
    @Nullable public String symbol;
    private ComponentOccurrence() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Long createdAt;
        private String id;
        private Integer line;
        private String location;
        private Integer offset;
        private String symbol;
        public Builder createdAt(Long value) { this.createdAt = value; return this; }
        public Builder id(String value) { this.id = value; return this; }
        public Builder line(Integer value) { this.line = value; return this; }
        public Builder location(String value) { this.location = value; return this; }
        public Builder offset(Integer value) { this.offset = value; return this; }
        public Builder symbol(String value) { this.symbol = value; return this; }
        public ComponentOccurrence build() {
            ComponentOccurrence result = new ComponentOccurrence();
            result.createdAt = this.createdAt;
            if (this.id != null) {
                Validation.validateUuid("id", this.id);
            }
            result.id = this.id;
            result.line = this.line;
            result.location = this.location;
            result.offset = this.offset;
            result.symbol = this.symbol;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ComponentOccurrence{"
            + "createdAt=" + createdAt
            + ", id=" + id
            + ", line=" + line
            + ", location=" + location
            + ", offset=" + offset
            + ", symbol=" + symbol
            + "}";
    }
}
