// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.oidc;

import dependencytrackunofficialsdk.Validation;

/**
 * CreateOidcGroupRequest.
 * Typed representation of the `CreateOidcGroupRequest` API schema.
 */

public final class CreateOidcGroupRequest {
    /**
     * Name of the group to create
     */
    public String name;
    private CreateOidcGroupRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        public Builder name(String value) { this.name = value; return this; }
        public CreateOidcGroupRequest build() {
            CreateOidcGroupRequest result = new CreateOidcGroupRequest();
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            Validation.validatePattern("name", this.name, "[\\P{Cc}]+");
            result.name = this.name;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CreateOidcGroupRequest{"
            + "name=" + name
            + "}";
    }
}
