// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.oidc;

import dependencytrackunofficialsdk.Validation;

/**
 * UpdateOidcGroupRequest.
 * Typed representation of the `UpdateOidcGroupRequest` API schema.
 */

public final class UpdateOidcGroupRequest {
    /**
     * New name of the group
     */
    public String name;
    /**
     * UUID of the group to update
     */
    public String uuid;
    private UpdateOidcGroupRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String uuid;
        public Builder name(String value) { this.name = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public UpdateOidcGroupRequest build() {
            UpdateOidcGroupRequest result = new UpdateOidcGroupRequest();
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            Validation.validatePattern("name", this.name, "[\\P{Cc}]+");
            result.name = this.name;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "UpdateOidcGroupRequest{"
            + "name=" + name
            + ", uuid=" + uuid
            + "}";
    }
}
