// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * ApiKey.
 * Typed representation of the `ApiKey` API schema.
 */

public final class ApiKey {
    /**
     * Optional `string` value serialized in the `comment` wire field.
     */
    @Nullable public String comment;
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long created;
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long expiresAt;
    /**
     * Optional `string` value serialized in the `key` wire field.
     */
    @Nullable public String key;
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long lastUsed;
    /**
     * Optional `boolean` value serialized in the `legacy` wire field.
     */
    @Nullable public Boolean legacy;
    /**
     * Optional `string` value serialized in the `maskedKey` wire field.
     */
    @Nullable public String maskedKey;
    /**
     * Optional `string` value serialized in the `publicId` wire field.
     */
    @Nullable public String publicId;
    private ApiKey() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String comment;
        private Long created;
        private Long expiresAt;
        private String key;
        private Long lastUsed;
        private Boolean legacy;
        private String maskedKey;
        private String publicId;
        public Builder comment(String value) { this.comment = value; return this; }
        public Builder created(Long value) { this.created = value; return this; }
        public Builder expiresAt(Long value) { this.expiresAt = value; return this; }
        public Builder key(String value) { this.key = value; return this; }
        public Builder lastUsed(Long value) { this.lastUsed = value; return this; }
        public Builder legacy(Boolean value) { this.legacy = value; return this; }
        public Builder maskedKey(String value) { this.maskedKey = value; return this; }
        public Builder publicId(String value) { this.publicId = value; return this; }
        public ApiKey build() {
            ApiKey result = new ApiKey();
            if (this.comment != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 255; Validation.validateLength("comment", this.comment, __length); }
            }
            result.comment = this.comment;
            result.created = this.created;
            result.expiresAt = this.expiresAt;
            result.key = this.key;
            result.lastUsed = this.lastUsed;
            result.legacy = this.legacy;
            result.maskedKey = this.maskedKey;
            if (this.publicId != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 5; __length.max = 8; Validation.validateLength("publicId", this.publicId, __length); }
            }
            result.publicId = this.publicId;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ApiKey{"
            + "comment=" + comment
            + ", created=" + created
            + ", expiresAt=" + expiresAt
            + ", key=" + key
            + ", lastUsed=" + lastUsed
            + ", legacy=" + legacy
            + ", maskedKey=" + maskedKey
            + ", publicId=" + publicId
            + "}";
    }
}
