// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;

/**
 * BomUploadResponse.
 * Typed representation of the `BomUploadResponse` API schema.
 */

public final class BomUploadResponse {
    /**
     * UUID of the project the BOM was uploaded for
     */
    public String projectUuid;
    /**
     * Token used to check task progress
     */
    public String token;
    private BomUploadResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String projectUuid;
        private String token;
        public Builder projectUuid(String value) { this.projectUuid = value; return this; }
        public Builder token(String value) { this.token = value; return this; }
        public BomUploadResponse build() {
            BomUploadResponse result = new BomUploadResponse();
            Validation.validateRequired("projectUuid", this.projectUuid);
            Validation.validateUuid("projectUuid", this.projectUuid);
            result.projectUuid = this.projectUuid;
            Validation.validateRequired("token", this.token);
            Validation.validateUuid("token", this.token);
            result.token = this.token;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "BomUploadResponse{"
            + "projectUuid=" + projectUuid
            + ", token=" + token
            + "}";
    }
}
