// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

/**
 * Optional enumerated value serialized in the `scope` wire field.
 */
public final class ComponentScopeEnum {
    public static final ComponentScopeEnum REQUIRED = new ComponentScopeEnum("REQUIRED");
    public static final ComponentScopeEnum OPTIONAL = new ComponentScopeEnum("OPTIONAL");
    public static final ComponentScopeEnum EXCLUDED = new ComponentScopeEnum("EXCLUDED");
    private final String value;
    private ComponentScopeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ComponentScopeEnum fromValue(String value) {
        if ("REQUIRED".equals(value)) return REQUIRED;
        if ("OPTIONAL".equals(value)) return OPTIONAL;
        if ("EXCLUDED".equals(value)) return EXCLUDED;
        return new ComponentScopeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ComponentScopeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
