// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import javax.annotation.Nullable;

/**
 * Cwe.
 * Typed representation of the `Cwe` API schema.
 */

public final class Cwe {
    /**
     * Optional `int32`-formatted value serialized in the `cweId` wire field.
     */
    @Nullable public Integer cweId;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    @Nullable public String name;
    private Cwe() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Integer cweId;
        private String name;
        public Builder cweId(Integer value) { this.cweId = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Cwe build() {
            Cwe result = new Cwe();
            result.cweId = this.cweId;
            result.name = this.name;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Cwe{"
            + "cweId=" + cweId
            + ", name=" + name
            + "}";
    }
}
