// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import javax.annotation.Nullable;

/**
 * Epss.
 * Typed representation of the `Epss` API schema.
 */

public final class Epss {
    /**
     * Optional `string` value serialized in the `cve` wire field.
     */
    @Nullable public String cve;
    /**
     * Optional `number` value serialized in the `percentile` wire field.
     */
    @Nullable public Double percentile;
    /**
     * Optional `number` value serialized in the `score` wire field.
     */
    @Nullable public Double score;
    private Epss() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String cve;
        private Double percentile;
        private Double score;
        public Builder cve(String value) { this.cve = value; return this; }
        public Builder percentile(Double value) { this.percentile = value; return this; }
        public Builder score(Double value) { this.score = value; return this; }
        public Epss build() {
            Epss result = new Epss();
            result.cve = this.cve;
            result.percentile = this.percentile;
            result.score = this.score;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Epss{"
            + "cve=" + cve
            + ", percentile=" + percentile
            + ", score=" + score
            + "}";
    }
}
