// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * ExternalReference.
 * Typed representation of the `ExternalReference` API schema.
 */

public final class ExternalReference {
    /**
     * Required `string` value serialized in the `url` wire field.
     */
    public String url;
    /**
     * Optional `string` value serialized in the `comment` wire field.
     */
    @Nullable public String comment;
    /**
     * Optional enumerated value serialized in the `type` wire field.
     */
    @Nullable public ExternalReferenceTypeEnum type;
    private ExternalReference() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String url;
        private String comment;
        private ExternalReferenceTypeEnum type;
        public Builder url(String value) { this.url = value; return this; }
        public Builder comment(String value) { this.comment = value; return this; }
        public Builder type(ExternalReferenceTypeEnum value) { this.type = value; return this; }
        public ExternalReference build() {
            ExternalReference result = new ExternalReference();
            Validation.validateRequired("url", this.url);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("url", this.url, __length); }
            result.url = this.url;
            result.comment = this.comment;
            result.type = this.type;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ExternalReference{"
            + "url=" + url
            + ", comment=" + comment
            + ", type=" + type
            + "}";
    }
}
