// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

/**
 * The counting mode for the `X-Total-Count` response header.
 */
public final class GetAllFindings1TotalCountEnum {
    public static final GetAllFindings1TotalCountEnum EXACT = new GetAllFindings1TotalCountEnum("EXACT");
    public static final GetAllFindings1TotalCountEnum BOUNDED = new GetAllFindings1TotalCountEnum("BOUNDED");
    private final String value;
    private GetAllFindings1TotalCountEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static GetAllFindings1TotalCountEnum fromValue(String value) {
        if ("EXACT".equals(value)) return EXACT;
        if ("BOUNDED".equals(value)) return BOUNDED;
        return new GetAllFindings1TotalCountEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof GetAllFindings1TotalCountEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
