// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

public final class GetFindingsByProjectSourceEnum {
    public static final GetFindingsByProjectSourceEnum NVD = new GetFindingsByProjectSourceEnum("NVD");
    public static final GetFindingsByProjectSourceEnum GITHUB = new GetFindingsByProjectSourceEnum("GITHUB");
    public static final GetFindingsByProjectSourceEnum VULNDB = new GetFindingsByProjectSourceEnum("VULNDB");
    public static final GetFindingsByProjectSourceEnum OSSINDEX = new GetFindingsByProjectSourceEnum("OSSINDEX");
    public static final GetFindingsByProjectSourceEnum INTERNAL = new GetFindingsByProjectSourceEnum("INTERNAL");
    public static final GetFindingsByProjectSourceEnum OSV = new GetFindingsByProjectSourceEnum("OSV");
    public static final GetFindingsByProjectSourceEnum SNYK = new GetFindingsByProjectSourceEnum("SNYK");
    public static final GetFindingsByProjectSourceEnum CX = new GetFindingsByProjectSourceEnum("CX");
    public static final GetFindingsByProjectSourceEnum JVN = new GetFindingsByProjectSourceEnum("JVN");
    public static final GetFindingsByProjectSourceEnum UNKNOWN = new GetFindingsByProjectSourceEnum("UNKNOWN");
    private final String value;
    private GetFindingsByProjectSourceEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static GetFindingsByProjectSourceEnum fromValue(String value) {
        if ("NVD".equals(value)) return NVD;
        if ("GITHUB".equals(value)) return GITHUB;
        if ("VULNDB".equals(value)) return VULNDB;
        if ("OSSINDEX".equals(value)) return OSSINDEX;
        if ("INTERNAL".equals(value)) return INTERNAL;
        if ("OSV".equals(value)) return OSV;
        if ("SNYK".equals(value)) return SNYK;
        if ("CX".equals(value)) return CX;
        if ("JVN".equals(value)) return JVN;
        if ("UNKNOWN".equals(value)) return UNKNOWN;
        return new GetFindingsByProjectSourceEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof GetFindingsByProjectSourceEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
