// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

public final class GetProjectsByClassifierClassifierEnum {
    public static final GetProjectsByClassifierClassifierEnum APPLICATION = new GetProjectsByClassifierClassifierEnum("APPLICATION");
    public static final GetProjectsByClassifierClassifierEnum FRAMEWORK = new GetProjectsByClassifierClassifierEnum("FRAMEWORK");
    public static final GetProjectsByClassifierClassifierEnum LIBRARY = new GetProjectsByClassifierClassifierEnum("LIBRARY");
    public static final GetProjectsByClassifierClassifierEnum CONTAINER = new GetProjectsByClassifierClassifierEnum("CONTAINER");
    public static final GetProjectsByClassifierClassifierEnum OPERATING_SYSTEM = new GetProjectsByClassifierClassifierEnum("OPERATING_SYSTEM");
    public static final GetProjectsByClassifierClassifierEnum DEVICE = new GetProjectsByClassifierClassifierEnum("DEVICE");
    public static final GetProjectsByClassifierClassifierEnum FIRMWARE = new GetProjectsByClassifierClassifierEnum("FIRMWARE");
    public static final GetProjectsByClassifierClassifierEnum FILE = new GetProjectsByClassifierClassifierEnum("FILE");
    public static final GetProjectsByClassifierClassifierEnum PLATFORM = new GetProjectsByClassifierClassifierEnum("PLATFORM");
    public static final GetProjectsByClassifierClassifierEnum DEVICE_DRIVER = new GetProjectsByClassifierClassifierEnum("DEVICE_DRIVER");
    public static final GetProjectsByClassifierClassifierEnum MACHINE_LEARNING_MODEL = new GetProjectsByClassifierClassifierEnum("MACHINE_LEARNING_MODEL");
    public static final GetProjectsByClassifierClassifierEnum DATA = new GetProjectsByClassifierClassifierEnum("DATA");
    public static final GetProjectsByClassifierClassifierEnum CRYPTOGRAPHIC_ASSET = new GetProjectsByClassifierClassifierEnum("CRYPTOGRAPHIC_ASSET");
    private final String value;
    private GetProjectsByClassifierClassifierEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static GetProjectsByClassifierClassifierEnum fromValue(String value) {
        if ("APPLICATION".equals(value)) return APPLICATION;
        if ("FRAMEWORK".equals(value)) return FRAMEWORK;
        if ("LIBRARY".equals(value)) return LIBRARY;
        if ("CONTAINER".equals(value)) return CONTAINER;
        if ("OPERATING_SYSTEM".equals(value)) return OPERATING_SYSTEM;
        if ("DEVICE".equals(value)) return DEVICE;
        if ("FIRMWARE".equals(value)) return FIRMWARE;
        if ("FILE".equals(value)) return FILE;
        if ("PLATFORM".equals(value)) return PLATFORM;
        if ("DEVICE_DRIVER".equals(value)) return DEVICE_DRIVER;
        if ("MACHINE_LEARNING_MODEL".equals(value)) return MACHINE_LEARNING_MODEL;
        if ("DATA".equals(value)) return DATA;
        if ("CRYPTOGRAPHIC_ASSET".equals(value)) return CRYPTOGRAPHIC_ASSET;
        return new GetProjectsByClassifierClassifierEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof GetProjectsByClassifierClassifierEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
