// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

public final class GetRepositoriesByTypeSortOrderEnum {
    public static final GetRepositoriesByTypeSortOrderEnum ASC_DESC = new GetRepositoriesByTypeSortOrderEnum("asc, desc");
    private final String value;
    private GetRepositoriesByTypeSortOrderEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static GetRepositoriesByTypeSortOrderEnum fromValue(String value) {
        if ("asc, desc".equals(value)) return ASC_DESC;
        return new GetRepositoriesByTypeSortOrderEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof GetRepositoriesByTypeSortOrderEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
