// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

public final class GetRepositoriesByTypeTypeEnum {
    public static final GetRepositoriesByTypeTypeEnum MAVEN = new GetRepositoriesByTypeTypeEnum("MAVEN");
    public static final GetRepositoriesByTypeTypeEnum NPM = new GetRepositoriesByTypeTypeEnum("NPM");
    public static final GetRepositoriesByTypeTypeEnum GEM = new GetRepositoriesByTypeTypeEnum("GEM");
    public static final GetRepositoriesByTypeTypeEnum PYPI = new GetRepositoriesByTypeTypeEnum("PYPI");
    public static final GetRepositoriesByTypeTypeEnum NUGET = new GetRepositoriesByTypeTypeEnum("NUGET");
    public static final GetRepositoriesByTypeTypeEnum HEX = new GetRepositoriesByTypeTypeEnum("HEX");
    public static final GetRepositoriesByTypeTypeEnum COMPOSER = new GetRepositoriesByTypeTypeEnum("COMPOSER");
    public static final GetRepositoriesByTypeTypeEnum CARGO = new GetRepositoriesByTypeTypeEnum("CARGO");
    public static final GetRepositoriesByTypeTypeEnum GO_MODULES = new GetRepositoriesByTypeTypeEnum("GO_MODULES");
    public static final GetRepositoriesByTypeTypeEnum CPAN = new GetRepositoriesByTypeTypeEnum("CPAN");
    public static final GetRepositoriesByTypeTypeEnum GITHUB = new GetRepositoriesByTypeTypeEnum("GITHUB");
    public static final GetRepositoriesByTypeTypeEnum HACKAGE = new GetRepositoriesByTypeTypeEnum("HACKAGE");
    public static final GetRepositoriesByTypeTypeEnum NIXPKGS = new GetRepositoriesByTypeTypeEnum("NIXPKGS");
    public static final GetRepositoriesByTypeTypeEnum UNSUPPORTED = new GetRepositoriesByTypeTypeEnum("UNSUPPORTED");
    private final String value;
    private GetRepositoriesByTypeTypeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static GetRepositoriesByTypeTypeEnum fromValue(String value) {
        if ("MAVEN".equals(value)) return MAVEN;
        if ("NPM".equals(value)) return NPM;
        if ("GEM".equals(value)) return GEM;
        if ("PYPI".equals(value)) return PYPI;
        if ("NUGET".equals(value)) return NUGET;
        if ("HEX".equals(value)) return HEX;
        if ("COMPOSER".equals(value)) return COMPOSER;
        if ("CARGO".equals(value)) return CARGO;
        if ("GO_MODULES".equals(value)) return GO_MODULES;
        if ("CPAN".equals(value)) return CPAN;
        if ("GITHUB".equals(value)) return GITHUB;
        if ("HACKAGE".equals(value)) return HACKAGE;
        if ("NIXPKGS".equals(value)) return NIXPKGS;
        if ("UNSUPPORTED".equals(value)) return UNSUPPORTED;
        return new GetRepositoriesByTypeTypeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof GetRepositoriesByTypeTypeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
