// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;
import java.util.List;
import javax.annotation.Nullable;

/**
 * ManagedUser.
 * Typed representation of the `ManagedUser` API schema.
 */

public final class ManagedUser {
    /**
     * UNIX epoch timestamp in milliseconds
     */
    public Long lastPasswordChange;
    /**
     * Required `string` value serialized in the `username` wire field.
     */
    public String username;
    /**
     * Optional `string` value serialized in the `confirmPassword` wire field.
     */
    @Nullable public String confirmPassword;
    /**
     * Optional `string` value serialized in the `email` wire field.
     */
    @Nullable public String email;
    /**
     * Optional `boolean` value serialized in the `forcePasswordChange` wire field.
     */
    @Nullable public Boolean forcePasswordChange;
    /**
     * Optional `string` value serialized in the `fullname` wire field.
     */
    @Nullable public String fullname;
    /**
     * Optional `string` value serialized in the `newPassword` wire field.
     */
    @Nullable public String newPassword;
    /**
     * Optional `boolean` value serialized in the `nonExpiryPassword` wire field.
     */
    @Nullable public Boolean nonExpiryPassword;
    /**
     * Optional array value serialized in the `permissions` wire field.
     */
    @Nullable public List<Permission> permissions;
    /**
     * Optional `boolean` value serialized in the `suspended` wire field.
     */
    @Nullable public Boolean suspended;
    /**
     * Optional array value serialized in the `teams` wire field.
     */
    @Nullable public List<Team> teams;
    private ManagedUser() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Long lastPasswordChange;
        private String username;
        private String confirmPassword;
        private String email;
        private Boolean forcePasswordChange;
        private String fullname;
        private String newPassword;
        private Boolean nonExpiryPassword;
        private List<Permission> permissions;
        private Boolean suspended;
        private List<Team> teams;
        public Builder lastPasswordChange(Long value) { this.lastPasswordChange = value; return this; }
        public Builder username(String value) { this.username = value; return this; }
        public Builder confirmPassword(String value) { this.confirmPassword = value; return this; }
        public Builder email(String value) { this.email = value; return this; }
        public Builder forcePasswordChange(Boolean value) { this.forcePasswordChange = value; return this; }
        public Builder fullname(String value) { this.fullname = value; return this; }
        public Builder newPassword(String value) { this.newPassword = value; return this; }
        public Builder nonExpiryPassword(Boolean value) { this.nonExpiryPassword = value; return this; }
        public Builder permissions(List<Permission> value) { this.permissions = value; return this; }
        public Builder suspended(Boolean value) { this.suspended = value; return this; }
        public Builder teams(List<Team> value) { this.teams = value; return this; }
        public ManagedUser build() {
            ManagedUser result = new ManagedUser();
            Validation.validateRequired("lastPasswordChange", this.lastPasswordChange);
            result.lastPasswordChange = this.lastPasswordChange;
            Validation.validateRequired("username", this.username);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("username", this.username, __length); }
            Validation.validatePattern("username", this.username, "[\\P{Cc}]+");
            result.username = this.username;
            result.confirmPassword = this.confirmPassword;
            if (this.email != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 255; Validation.validateLength("email", this.email, __length); }
                Validation.validatePattern("email", this.email, "[\\P{Cc}]+");
            }
            result.email = this.email;
            result.forcePasswordChange = this.forcePasswordChange;
            if (this.fullname != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 255; Validation.validateLength("fullname", this.fullname, __length); }
                Validation.validatePattern("fullname", this.fullname, "[\\P{Cc}]+");
            }
            result.fullname = this.fullname;
            result.newPassword = this.newPassword;
            result.nonExpiryPassword = this.nonExpiryPassword;
            result.permissions = this.permissions;
            result.suspended = this.suspended;
            result.teams = this.teams;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "ManagedUser{"
            + "lastPasswordChange=" + lastPasswordChange
            + ", username=" + username
            + ", confirmPassword=" + confirmPassword
            + ", email=" + email
            + ", forcePasswordChange=" + forcePasswordChange
            + ", fullname=" + fullname
            + ", newPassword=" + newPassword
            + ", nonExpiryPassword=" + nonExpiryPassword
            + ", permissions=" + permissions
            + ", suspended=" + suspended
            + ", teams=" + teams
            + "}";
    }
}
