// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * Parent.
 * Typed representation of the `Parent` API schema.
 */

public final class Parent {
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Optional `string` value serialized in the `version` wire field.
     */
    @Nullable public String version;
    private Parent() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String uuid;
        private String version;
        public Builder name(String value) { this.name = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public Parent build() {
            Parent result = new Parent();
            Validation.validateRequired("name", this.name);
            result.name = this.name;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.version = this.version;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Parent{"
            + "name=" + name
            + ", uuid=" + uuid
            + ", version=" + version
            + "}";
    }
}
