// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

/**
 * Optional enumerated value serialized in the `classifier` wire field.
 */
public final class ProjectClassifierEnum {
    public static final ProjectClassifierEnum APPLICATION = new ProjectClassifierEnum("APPLICATION");
    public static final ProjectClassifierEnum FRAMEWORK = new ProjectClassifierEnum("FRAMEWORK");
    public static final ProjectClassifierEnum LIBRARY = new ProjectClassifierEnum("LIBRARY");
    public static final ProjectClassifierEnum CONTAINER = new ProjectClassifierEnum("CONTAINER");
    public static final ProjectClassifierEnum OPERATING_SYSTEM = new ProjectClassifierEnum("OPERATING_SYSTEM");
    public static final ProjectClassifierEnum DEVICE = new ProjectClassifierEnum("DEVICE");
    public static final ProjectClassifierEnum FIRMWARE = new ProjectClassifierEnum("FIRMWARE");
    public static final ProjectClassifierEnum FILE = new ProjectClassifierEnum("FILE");
    public static final ProjectClassifierEnum PLATFORM = new ProjectClassifierEnum("PLATFORM");
    public static final ProjectClassifierEnum DEVICE_DRIVER = new ProjectClassifierEnum("DEVICE_DRIVER");
    public static final ProjectClassifierEnum MACHINE_LEARNING_MODEL = new ProjectClassifierEnum("MACHINE_LEARNING_MODEL");
    public static final ProjectClassifierEnum DATA = new ProjectClassifierEnum("DATA");
    public static final ProjectClassifierEnum CRYPTOGRAPHIC_ASSET = new ProjectClassifierEnum("CRYPTOGRAPHIC_ASSET");
    private final String value;
    private ProjectClassifierEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ProjectClassifierEnum fromValue(String value) {
        if ("APPLICATION".equals(value)) return APPLICATION;
        if ("FRAMEWORK".equals(value)) return FRAMEWORK;
        if ("LIBRARY".equals(value)) return LIBRARY;
        if ("CONTAINER".equals(value)) return CONTAINER;
        if ("OPERATING_SYSTEM".equals(value)) return OPERATING_SYSTEM;
        if ("DEVICE".equals(value)) return DEVICE;
        if ("FIRMWARE".equals(value)) return FIRMWARE;
        if ("FILE".equals(value)) return FILE;
        if ("PLATFORM".equals(value)) return PLATFORM;
        if ("DEVICE_DRIVER".equals(value)) return DEVICE_DRIVER;
        if ("MACHINE_LEARNING_MODEL".equals(value)) return MACHINE_LEARNING_MODEL;
        if ("DATA".equals(value)) return DATA;
        if ("CRYPTOGRAPHIC_ASSET".equals(value)) return CRYPTOGRAPHIC_ASSET;
        return new ProjectClassifierEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ProjectClassifierEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
