// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

/**
 * Optional enumerated value serialized in the `collectionLogic` wire field.
 */
public final class ProjectCollectionLogicEnum {
    public static final ProjectCollectionLogicEnum AGGREGATE_DIRECT_CHILDREN = new ProjectCollectionLogicEnum("AGGREGATE_DIRECT_CHILDREN");
    public static final ProjectCollectionLogicEnum AGGREGATE_DIRECT_CHILDREN_WITH_TAG = new ProjectCollectionLogicEnum("AGGREGATE_DIRECT_CHILDREN_WITH_TAG");
    public static final ProjectCollectionLogicEnum AGGREGATE_LATEST_VERSION_CHILDREN = new ProjectCollectionLogicEnum("AGGREGATE_LATEST_VERSION_CHILDREN");
    private final String value;
    private ProjectCollectionLogicEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ProjectCollectionLogicEnum fromValue(String value) {
        if ("AGGREGATE_DIRECT_CHILDREN".equals(value)) return AGGREGATE_DIRECT_CHILDREN;
        if ("AGGREGATE_DIRECT_CHILDREN_WITH_TAG".equals(value)) return AGGREGATE_DIRECT_CHILDREN_WITH_TAG;
        if ("AGGREGATE_LATEST_VERSION_CHILDREN".equals(value)) return AGGREGATE_LATEST_VERSION_CHILDREN;
        return new ProjectCollectionLogicEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ProjectCollectionLogicEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
