// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import javax.annotation.Nullable;

/**
 * RepositoryMetaComponent.
 * Typed representation of the `RepositoryMetaComponent` API schema.
 */

public final class RepositoryMetaComponent {
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long lastCheck;
    /**
     * Optional `string` value serialized in the `latestVersion` wire field.
     */
    @Nullable public String latestVersion;
    /**
     * UNIX epoch timestamp in milliseconds
     */
    @Nullable public Long latestVersionPublishedAt;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    @Nullable public String name;
    /**
     * Optional `string` value serialized in the `namespace` wire field.
     */
    @Nullable public String namespace;
    /**
     * Optional enumerated value serialized in the `repositoryType` wire field.
     */
    @Nullable public RepositoryMetaComponentRepositoryTypeEnum repositoryType;
    private RepositoryMetaComponent() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Long lastCheck;
        private String latestVersion;
        private Long latestVersionPublishedAt;
        private String name;
        private String namespace;
        private RepositoryMetaComponentRepositoryTypeEnum repositoryType;
        public Builder lastCheck(Long value) { this.lastCheck = value; return this; }
        public Builder latestVersion(String value) { this.latestVersion = value; return this; }
        public Builder latestVersionPublishedAt(Long value) { this.latestVersionPublishedAt = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder namespace(String value) { this.namespace = value; return this; }
        public Builder repositoryType(RepositoryMetaComponentRepositoryTypeEnum value) { this.repositoryType = value; return this; }
        public RepositoryMetaComponent build() {
            RepositoryMetaComponent result = new RepositoryMetaComponent();
            result.lastCheck = this.lastCheck;
            result.latestVersion = this.latestVersion;
            result.latestVersionPublishedAt = this.latestVersionPublishedAt;
            result.name = this.name;
            result.namespace = this.namespace;
            result.repositoryType = this.repositoryType;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "RepositoryMetaComponent{"
            + "lastCheck=" + lastCheck
            + ", latestVersion=" + latestVersion
            + ", latestVersionPublishedAt=" + latestVersionPublishedAt
            + ", name=" + name
            + ", namespace=" + namespace
            + ", repositoryType=" + repositoryType
            + "}";
    }
}
