// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import dependencytrackunofficialsdk.Validation;

/**
 * Tag.
 * Typed representation of the `Tag` API schema.
 */

public final class Tag {
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    private Tag() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        public Builder name(String value) { this.name = value; return this; }
        public Tag build() {
            Tag result = new Tag();
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Tag{"
            + "name=" + name
            + "}";
    }
}
