// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared;

import java.util.List;
import javax.annotation.Nullable;

/**
 * Tools.
 * Typed representation of the `Tools` API schema.
 */

public final class Tools {
    /**
     * Optional array value serialized in the `components` wire field.
     */
    @Nullable public List<Component> components;
    /**
     * Optional array value serialized in the `services` wire field.
     */
    @Nullable public List<ServiceComponent> services;
    private Tools() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private List<Component> components;
        private List<ServiceComponent> services;
        public Builder components(List<Component> value) { this.components = value; return this; }
        public Builder services(List<ServiceComponent> value) { this.services = value; return this; }
        public Tools build() {
            Tools result = new Tools();
            result.components = this.components;
            result.services = this.services;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Tools{"
            + "components=" + components
            + ", services=" + services
            + "}";
    }
}
