// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.tag;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * TaggedCollectionProjectListResponseItem.
 * Typed representation of the `TaggedCollectionProjectListResponseItem` API schema.
 */

public final class TaggedCollectionProjectListResponseItem {
    /**
     * Name of the collection project
     */
    public String name;
    /**
     * UUID of the collection project
     */
    public String uuid;
    /**
     * Version of the collection project
     */
    @Nullable public String version;
    private TaggedCollectionProjectListResponseItem() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String uuid;
        private String version;
        public Builder name(String value) { this.name = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public TaggedCollectionProjectListResponseItem build() {
            TaggedCollectionProjectListResponseItem result = new TaggedCollectionProjectListResponseItem();
            Validation.validateRequired("name", this.name);
            result.name = this.name;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.version = this.version;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "TaggedCollectionProjectListResponseItem{"
            + "name=" + name
            + ", uuid=" + uuid
            + ", version=" + version
            + "}";
    }
}
