// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.tag;

import dependencytrackunofficialsdk.Validation;

/**
 * TagListResponseItem.
 * Typed representation of the `TagListResponseItem` API schema.
 */

public final class TagListResponseItem {
    /**
     * Number of collection projects assigned to this tag
     */
    public Long collectionProjectCount;
    /**
     * Name of the tag
     */
    public String name;
    /**
     * Number of notification rules assigned to this tag
     */
    public Long notificationRuleCount;
    /**
     * Number of policies assigned to this tag
     */
    public Long policyCount;
    /**
     * Number of projects assigned to this tag
     */
    public Long projectCount;
    /**
     * Number of vulnerabilities assigned to this tag
     */
    public Long vulnerabilityCount;
    private TagListResponseItem() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Long collectionProjectCount;
        private String name;
        private Long notificationRuleCount;
        private Long policyCount;
        private Long projectCount;
        private Long vulnerabilityCount;
        public Builder collectionProjectCount(Long value) { this.collectionProjectCount = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder notificationRuleCount(Long value) { this.notificationRuleCount = value; return this; }
        public Builder policyCount(Long value) { this.policyCount = value; return this; }
        public Builder projectCount(Long value) { this.projectCount = value; return this; }
        public Builder vulnerabilityCount(Long value) { this.vulnerabilityCount = value; return this; }
        public TagListResponseItem build() {
            TagListResponseItem result = new TagListResponseItem();
            Validation.validateRequired("collectionProjectCount", this.collectionProjectCount);
            result.collectionProjectCount = this.collectionProjectCount;
            Validation.validateRequired("name", this.name);
            result.name = this.name;
            Validation.validateRequired("notificationRuleCount", this.notificationRuleCount);
            result.notificationRuleCount = this.notificationRuleCount;
            Validation.validateRequired("policyCount", this.policyCount);
            result.policyCount = this.policyCount;
            Validation.validateRequired("projectCount", this.projectCount);
            result.projectCount = this.projectCount;
            Validation.validateRequired("vulnerabilityCount", this.vulnerabilityCount);
            result.vulnerabilityCount = this.vulnerabilityCount;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "TagListResponseItem{"
            + "collectionProjectCount=" + collectionProjectCount
            + ", name=" + name
            + ", notificationRuleCount=" + notificationRuleCount
            + ", policyCount=" + policyCount
            + ", projectCount=" + projectCount
            + ", vulnerabilityCount=" + vulnerabilityCount
            + "}";
    }
}
