// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.tag;

import java.util.Map;
import javax.annotation.Nullable;

public final class TagOperationProblemDetailsVariant1 {
    /**
     * Errors encountered during the operation, grouped by tag name
     */
    @Nullable public Map<String, String> errors;
    private TagOperationProblemDetailsVariant1() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Map<String, String> errors;
        public Builder errors(Map<String, String> value) { this.errors = value; return this; }
        public TagOperationProblemDetailsVariant1 build() {
            TagOperationProblemDetailsVariant1 result = new TagOperationProblemDetailsVariant1();
            result.errors = this.errors;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "TagOperationProblemDetailsVariant1{"
            + "errors=" + errors
            + "}";
    }
}
