// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.policy_condition;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * PolicyConditionResponse.
 * Typed representation of the `PolicyConditionResponse` API schema.
 */

public final class PolicyConditionResponse {
    /**
     * Operator used to compare the subject to the value
     */
    public PolicyConditionResponseOperatorEnum operator;
    /**
     * Subject the condition evaluates
     */
    public PolicyConditionResponseSubjectEnum subject;
    /**
     * UUID of the policy condition
     */
    public String uuid;
    /**
     * Value the subject is compared to
     */
    public String value;
    /**
     * Violation type produced when the condition matches
     */
    @Nullable public PolicyConditionResponseViolationTypeEnum violationType;
    private PolicyConditionResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private PolicyConditionResponseOperatorEnum operator;
        private PolicyConditionResponseSubjectEnum subject;
        private String uuid;
        private String value;
        private PolicyConditionResponseViolationTypeEnum violationType;
        public Builder operator(PolicyConditionResponseOperatorEnum value) { this.operator = value; return this; }
        public Builder subject(PolicyConditionResponseSubjectEnum value) { this.subject = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder value(String value) { this.value = value; return this; }
        public Builder violationType(PolicyConditionResponseViolationTypeEnum value) { this.violationType = value; return this; }
        public PolicyConditionResponse build() {
            PolicyConditionResponse result = new PolicyConditionResponse();
            Validation.validateRequired("operator", this.operator);
            result.operator = this.operator;
            Validation.validateRequired("subject", this.subject);
            result.subject = this.subject;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            Validation.validateRequired("value", this.value);
            result.value = this.value;
            result.violationType = this.violationType;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "PolicyConditionResponse{"
            + "operator=" + operator
            + ", subject=" + subject
            + ", uuid=" + uuid
            + ", value=" + value
            + ", violationType=" + violationType
            + "}";
    }
}
