// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.policy_condition;

/**
 * Subject the condition evaluates
 */
public final class UpdatePolicyConditionRequestSubjectEnum {
    public static final UpdatePolicyConditionRequestSubjectEnum AGE = new UpdatePolicyConditionRequestSubjectEnum("AGE");
    public static final UpdatePolicyConditionRequestSubjectEnum COORDINATES = new UpdatePolicyConditionRequestSubjectEnum("COORDINATES");
    public static final UpdatePolicyConditionRequestSubjectEnum CPE = new UpdatePolicyConditionRequestSubjectEnum("CPE");
    public static final UpdatePolicyConditionRequestSubjectEnum EXPRESSION = new UpdatePolicyConditionRequestSubjectEnum("EXPRESSION");
    public static final UpdatePolicyConditionRequestSubjectEnum LICENSE = new UpdatePolicyConditionRequestSubjectEnum("LICENSE");
    public static final UpdatePolicyConditionRequestSubjectEnum LICENSE_GROUP = new UpdatePolicyConditionRequestSubjectEnum("LICENSE_GROUP");
    public static final UpdatePolicyConditionRequestSubjectEnum PACKAGE_URL = new UpdatePolicyConditionRequestSubjectEnum("PACKAGE_URL");
    public static final UpdatePolicyConditionRequestSubjectEnum SEVERITY = new UpdatePolicyConditionRequestSubjectEnum("SEVERITY");
    public static final UpdatePolicyConditionRequestSubjectEnum SWID_TAGID = new UpdatePolicyConditionRequestSubjectEnum("SWID_TAGID");
    public static final UpdatePolicyConditionRequestSubjectEnum VERSION = new UpdatePolicyConditionRequestSubjectEnum("VERSION");
    public static final UpdatePolicyConditionRequestSubjectEnum COMPONENT_HASH = new UpdatePolicyConditionRequestSubjectEnum("COMPONENT_HASH");
    public static final UpdatePolicyConditionRequestSubjectEnum IS_INTERNAL = new UpdatePolicyConditionRequestSubjectEnum("IS_INTERNAL");
    public static final UpdatePolicyConditionRequestSubjectEnum CWE = new UpdatePolicyConditionRequestSubjectEnum("CWE");
    public static final UpdatePolicyConditionRequestSubjectEnum VULNERABILITY_ID = new UpdatePolicyConditionRequestSubjectEnum("VULNERABILITY_ID");
    public static final UpdatePolicyConditionRequestSubjectEnum VERSION_DISTANCE = new UpdatePolicyConditionRequestSubjectEnum("VERSION_DISTANCE");
    public static final UpdatePolicyConditionRequestSubjectEnum EPSS = new UpdatePolicyConditionRequestSubjectEnum("EPSS");
    private final String value;
    private UpdatePolicyConditionRequestSubjectEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static UpdatePolicyConditionRequestSubjectEnum fromValue(String value) {
        if ("AGE".equals(value)) return AGE;
        if ("COORDINATES".equals(value)) return COORDINATES;
        if ("CPE".equals(value)) return CPE;
        if ("EXPRESSION".equals(value)) return EXPRESSION;
        if ("LICENSE".equals(value)) return LICENSE;
        if ("LICENSE_GROUP".equals(value)) return LICENSE_GROUP;
        if ("PACKAGE_URL".equals(value)) return PACKAGE_URL;
        if ("SEVERITY".equals(value)) return SEVERITY;
        if ("SWID_TAGID".equals(value)) return SWID_TAGID;
        if ("VERSION".equals(value)) return VERSION;
        if ("COMPONENT_HASH".equals(value)) return COMPONENT_HASH;
        if ("IS_INTERNAL".equals(value)) return IS_INTERNAL;
        if ("CWE".equals(value)) return CWE;
        if ("VULNERABILITY_ID".equals(value)) return VULNERABILITY_ID;
        if ("VERSION_DISTANCE".equals(value)) return VERSION_DISTANCE;
        if ("EPSS".equals(value)) return EPSS;
        return new UpdatePolicyConditionRequestSubjectEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof UpdatePolicyConditionRequestSubjectEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
