// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_oidc;

import dependencytrackunofficialsdk.Validation;

/**
 * OidcGroup.
 * Typed representation of the `OidcGroup` API schema.
 */

public final class OidcGroup {
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    private OidcGroup() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String uuid;
        public Builder name(String value) { this.name = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public OidcGroup build() {
            OidcGroup result = new OidcGroup();
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            Validation.validatePattern("name", this.name, "[\\P{Cc}]+");
            result.name = this.name;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "OidcGroup{"
            + "name=" + name
            + ", uuid=" + uuid
            + "}";
    }
}
