// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.analysis;

/**
 * Optional enumerated value serialized in the `analysisState` wire field.
 */
public final class AnalysisRequestAnalysisStateEnum {
    public static final AnalysisRequestAnalysisStateEnum EXPLOITABLE = new AnalysisRequestAnalysisStateEnum("EXPLOITABLE");
    public static final AnalysisRequestAnalysisStateEnum IN_TRIAGE = new AnalysisRequestAnalysisStateEnum("IN_TRIAGE");
    public static final AnalysisRequestAnalysisStateEnum FALSE_POSITIVE = new AnalysisRequestAnalysisStateEnum("FALSE_POSITIVE");
    public static final AnalysisRequestAnalysisStateEnum NOT_AFFECTED = new AnalysisRequestAnalysisStateEnum("NOT_AFFECTED");
    public static final AnalysisRequestAnalysisStateEnum RESOLVED = new AnalysisRequestAnalysisStateEnum("RESOLVED");
    public static final AnalysisRequestAnalysisStateEnum NOT_SET = new AnalysisRequestAnalysisStateEnum("NOT_SET");
    private final String value;
    private AnalysisRequestAnalysisStateEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static AnalysisRequestAnalysisStateEnum fromValue(String value) {
        if ("EXPLOITABLE".equals(value)) return EXPLOITABLE;
        if ("IN_TRIAGE".equals(value)) return IN_TRIAGE;
        if ("FALSE_POSITIVE".equals(value)) return FALSE_POSITIVE;
        if ("NOT_AFFECTED".equals(value)) return NOT_AFFECTED;
        if ("RESOLVED".equals(value)) return RESOLVED;
        if ("NOT_SET".equals(value)) return NOT_SET;
        return new AnalysisRequestAnalysisStateEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof AnalysisRequestAnalysisStateEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
