// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.analysis;

/**
 * The state of the analysis decision
 */
public final class AnalysisTrailResponseAnalysisStateEnum {
    public static final AnalysisTrailResponseAnalysisStateEnum EXPLOITABLE = new AnalysisTrailResponseAnalysisStateEnum("EXPLOITABLE");
    public static final AnalysisTrailResponseAnalysisStateEnum IN_TRIAGE = new AnalysisTrailResponseAnalysisStateEnum("IN_TRIAGE");
    public static final AnalysisTrailResponseAnalysisStateEnum FALSE_POSITIVE = new AnalysisTrailResponseAnalysisStateEnum("FALSE_POSITIVE");
    public static final AnalysisTrailResponseAnalysisStateEnum NOT_AFFECTED = new AnalysisTrailResponseAnalysisStateEnum("NOT_AFFECTED");
    public static final AnalysisTrailResponseAnalysisStateEnum RESOLVED = new AnalysisTrailResponseAnalysisStateEnum("RESOLVED");
    public static final AnalysisTrailResponseAnalysisStateEnum NOT_SET = new AnalysisTrailResponseAnalysisStateEnum("NOT_SET");
    private final String value;
    private AnalysisTrailResponseAnalysisStateEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static AnalysisTrailResponseAnalysisStateEnum fromValue(String value) {
        if ("EXPLOITABLE".equals(value)) return EXPLOITABLE;
        if ("IN_TRIAGE".equals(value)) return IN_TRIAGE;
        if ("FALSE_POSITIVE".equals(value)) return FALSE_POSITIVE;
        if ("NOT_AFFECTED".equals(value)) return NOT_AFFECTED;
        if ("RESOLVED".equals(value)) return RESOLVED;
        if ("NOT_SET".equals(value)) return NOT_SET;
        return new AnalysisTrailResponseAnalysisStateEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof AnalysisTrailResponseAnalysisStateEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
