// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.analysis;

/**
 * The justification of the analysis decision
 */
public final class AnalysisTrailResponseAnalysisJustificationEnum {
    public static final AnalysisTrailResponseAnalysisJustificationEnum CODE_NOT_PRESENT = new AnalysisTrailResponseAnalysisJustificationEnum("CODE_NOT_PRESENT");
    public static final AnalysisTrailResponseAnalysisJustificationEnum CODE_NOT_REACHABLE = new AnalysisTrailResponseAnalysisJustificationEnum("CODE_NOT_REACHABLE");
    public static final AnalysisTrailResponseAnalysisJustificationEnum REQUIRES_CONFIGURATION = new AnalysisTrailResponseAnalysisJustificationEnum("REQUIRES_CONFIGURATION");
    public static final AnalysisTrailResponseAnalysisJustificationEnum REQUIRES_DEPENDENCY = new AnalysisTrailResponseAnalysisJustificationEnum("REQUIRES_DEPENDENCY");
    public static final AnalysisTrailResponseAnalysisJustificationEnum REQUIRES_ENVIRONMENT = new AnalysisTrailResponseAnalysisJustificationEnum("REQUIRES_ENVIRONMENT");
    public static final AnalysisTrailResponseAnalysisJustificationEnum PROTECTED_BY_COMPILER = new AnalysisTrailResponseAnalysisJustificationEnum("PROTECTED_BY_COMPILER");
    public static final AnalysisTrailResponseAnalysisJustificationEnum PROTECTED_AT_RUNTIME = new AnalysisTrailResponseAnalysisJustificationEnum("PROTECTED_AT_RUNTIME");
    public static final AnalysisTrailResponseAnalysisJustificationEnum PROTECTED_AT_PERIMETER = new AnalysisTrailResponseAnalysisJustificationEnum("PROTECTED_AT_PERIMETER");
    public static final AnalysisTrailResponseAnalysisJustificationEnum PROTECTED_BY_MITIGATING_CONTROL = new AnalysisTrailResponseAnalysisJustificationEnum("PROTECTED_BY_MITIGATING_CONTROL");
    public static final AnalysisTrailResponseAnalysisJustificationEnum NOT_SET = new AnalysisTrailResponseAnalysisJustificationEnum("NOT_SET");
    private final String value;
    private AnalysisTrailResponseAnalysisJustificationEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static AnalysisTrailResponseAnalysisJustificationEnum fromValue(String value) {
        if ("CODE_NOT_PRESENT".equals(value)) return CODE_NOT_PRESENT;
        if ("CODE_NOT_REACHABLE".equals(value)) return CODE_NOT_REACHABLE;
        if ("REQUIRES_CONFIGURATION".equals(value)) return REQUIRES_CONFIGURATION;
        if ("REQUIRES_DEPENDENCY".equals(value)) return REQUIRES_DEPENDENCY;
        if ("REQUIRES_ENVIRONMENT".equals(value)) return REQUIRES_ENVIRONMENT;
        if ("PROTECTED_BY_COMPILER".equals(value)) return PROTECTED_BY_COMPILER;
        if ("PROTECTED_AT_RUNTIME".equals(value)) return PROTECTED_AT_RUNTIME;
        if ("PROTECTED_AT_PERIMETER".equals(value)) return PROTECTED_AT_PERIMETER;
        if ("PROTECTED_BY_MITIGATING_CONTROL".equals(value)) return PROTECTED_BY_MITIGATING_CONTROL;
        if ("NOT_SET".equals(value)) return NOT_SET;
        return new AnalysisTrailResponseAnalysisJustificationEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof AnalysisTrailResponseAnalysisJustificationEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
