// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.version;

import javax.annotation.Nullable;

/**
 * Framework.
 * Typed representation of the `Framework` API schema.
 */

public final class Framework {
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    @Nullable public String name;
    /**
     * Optional `string` value serialized in the `timestamp` wire field.
     */
    @Nullable public String timestamp;
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     */
    @Nullable public String uuid;
    /**
     * Optional `string` value serialized in the `version` wire field.
     */
    @Nullable public String version;
    private Framework() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String timestamp;
        private String uuid;
        private String version;
        public Builder name(String value) { this.name = value; return this; }
        public Builder timestamp(String value) { this.timestamp = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public Framework build() {
            Framework result = new Framework();
            result.name = this.name;
            result.timestamp = this.timestamp;
            result.uuid = this.uuid;
            result.version = this.version;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "Framework{"
            + "name=" + name
            + ", timestamp=" + timestamp
            + ", uuid=" + uuid
            + ", version=" + version
            + "}";
    }
}
