// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.repository;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * CreateRepositoryRequest.
 * Typed representation of the `CreateRepositoryRequest` API schema.
 */

public final class CreateRepositoryRequest {
    /**
     * Whether the repository requires authentication
     */
    public Boolean authenticationRequired;
    /**
     * Whether the repository is enabled
     */
    public Boolean enabled;
    /**
     * Unique identifier of the repository within its type
     */
    public String identifier;
    /**
     * Type of the repository
     */
    public CreateRepositoryRequestTypeEnum type;
    /**
     * URL of the repository
     */
    public String url;
    /**
     * Whether the repository is internal to the organization
     */
    @Nullable public Boolean internal;
    /**
     * Name of the secret holding the password or token
     */
    @Nullable public String password;
    /**
     * Username to authenticate with
     */
    @Nullable public String username;
    private CreateRepositoryRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Boolean authenticationRequired;
        private Boolean enabled;
        private String identifier;
        private CreateRepositoryRequestTypeEnum type;
        private String url;
        private Boolean internal;
        private String password;
        private String username;
        public Builder authenticationRequired(Boolean value) { this.authenticationRequired = value; return this; }
        public Builder enabled(Boolean value) { this.enabled = value; return this; }
        public Builder identifier(String value) { this.identifier = value; return this; }
        public Builder type(CreateRepositoryRequestTypeEnum value) { this.type = value; return this; }
        public Builder url(String value) { this.url = value; return this; }
        public Builder internal(Boolean value) { this.internal = value; return this; }
        public Builder password(String value) { this.password = value; return this; }
        public Builder username(String value) { this.username = value; return this; }
        public CreateRepositoryRequest build() {
            CreateRepositoryRequest result = new CreateRepositoryRequest();
            Validation.validateRequired("authenticationRequired", this.authenticationRequired);
            result.authenticationRequired = this.authenticationRequired;
            Validation.validateRequired("enabled", this.enabled);
            result.enabled = this.enabled;
            Validation.validateRequired("identifier", this.identifier);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("identifier", this.identifier, __length); }
            result.identifier = this.identifier;
            Validation.validateRequired("type", this.type);
            result.type = this.type;
            Validation.validateRequired("url", this.url);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("url", this.url, __length); }
            result.url = this.url;
            result.internal = this.internal;
            result.password = this.password;
            result.username = this.username;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CreateRepositoryRequest{"
            + "authenticationRequired=" + authenticationRequired
            + ", enabled=" + enabled
            + ", identifier=" + identifier
            + ", type=" + type
            + ", url=" + url
            + ", internal=" + internal
            + ", password=" + password
            + ", username=" + username
            + "}";
    }
}
