// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.repository;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * UpdateRepositoryRequest.
 * Typed representation of the `UpdateRepositoryRequest` API schema.
 */

public final class UpdateRepositoryRequest {
    /**
     * Whether the repository requires authentication
     */
    public Boolean authenticationRequired;
    /**
     * Whether the repository is enabled
     */
    public Boolean enabled;
    /**
     * URL of the repository
     */
    public String url;
    /**
     * UUID of the repository to update
     */
    public String uuid;
    /**
     * Whether the repository is internal to the organization
     */
    @Nullable public Boolean internal;
    /**
     * Name of the secret holding the password or token
     */
    @Nullable public String password;
    /**
     * Username to authenticate with
     */
    @Nullable public String username;
    private UpdateRepositoryRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private Boolean authenticationRequired;
        private Boolean enabled;
        private String url;
        private String uuid;
        private Boolean internal;
        private String password;
        private String username;
        public Builder authenticationRequired(Boolean value) { this.authenticationRequired = value; return this; }
        public Builder enabled(Boolean value) { this.enabled = value; return this; }
        public Builder url(String value) { this.url = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder internal(Boolean value) { this.internal = value; return this; }
        public Builder password(String value) { this.password = value; return this; }
        public Builder username(String value) { this.username = value; return this; }
        public UpdateRepositoryRequest build() {
            UpdateRepositoryRequest result = new UpdateRepositoryRequest();
            Validation.validateRequired("authenticationRequired", this.authenticationRequired);
            result.authenticationRequired = this.authenticationRequired;
            Validation.validateRequired("enabled", this.enabled);
            result.enabled = this.enabled;
            Validation.validateRequired("url", this.url);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("url", this.url, __length); }
            result.url = this.url;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.internal = this.internal;
            result.password = this.password;
            result.username = this.username;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "UpdateRepositoryRequest{"
            + "authenticationRequired=" + authenticationRequired
            + ", enabled=" + enabled
            + ", url=" + url
            + ", uuid=" + uuid
            + ", internal=" + internal
            + ", password=" + password
            + ", username=" + username
            + "}";
    }
}
