// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.acl;

import dependencytrackunofficialsdk.Validation;

/**
 * AclMappingRequest.
 * Typed representation of the `AclMappingRequest` API schema.
 */

public final class AclMappingRequest {
    /**
     * Required `string` value serialized in the `project` wire field.
     */
    public String project;
    /**
     * Required `string` value serialized in the `team` wire field.
     */
    public String team;
    private AclMappingRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String project;
        private String team;
        public Builder project(String value) { this.project = value; return this; }
        public Builder team(String value) { this.team = value; return this; }
        public AclMappingRequest build() {
            AclMappingRequest result = new AclMappingRequest();
            Validation.validateRequired("project", this.project);
            Validation.validatePattern("project", this.project, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
            result.project = this.project;
            Validation.validateRequired("team", this.team);
            Validation.validatePattern("team", this.team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
            result.team = this.team;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "AclMappingRequest{"
            + "project=" + project
            + ", team=" + team
            + "}";
    }
}
