// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.calculator;

/**
 * Optional enumerated value serialized in the `businessImpact` wire field.
 */
public final class ScoreBusinessImpactEnum {
    public static final ScoreBusinessImpactEnum HIGH = new ScoreBusinessImpactEnum("HIGH");
    public static final ScoreBusinessImpactEnum MEDIUM = new ScoreBusinessImpactEnum("MEDIUM");
    public static final ScoreBusinessImpactEnum LOW = new ScoreBusinessImpactEnum("LOW");
    private final String value;
    private ScoreBusinessImpactEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ScoreBusinessImpactEnum fromValue(String value) {
        if ("HIGH".equals(value)) return HIGH;
        if ("MEDIUM".equals(value)) return MEDIUM;
        if ("LOW".equals(value)) return LOW;
        return new ScoreBusinessImpactEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ScoreBusinessImpactEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
