// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import java.io.File;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Parameter;
import java.lang.reflect.Type;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.junit.jupiter.api.Test;


final class SdkMethodTest {
    // Configured the way the SDK configures its own mapper, so a value read back
    // out of a decoded response is spelled the way the SDK spells it on the wire.
    // Jackson's default writes a timestamp as a number of seconds since the epoch.
    private static final ObjectMapper MAPPER = new ObjectMapper()
        .findAndRegisterModules()
        .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    private static String normalized(String value) {
        return value.replaceAll("[^A-Za-z0-9]", "").toLowerCase(Locale.ROOT);
    }

    private static JsonNode byName(JsonNode object, String name) {
        if (object == null || !object.isObject()) return null;
        // An exact key wins: distinct wire keys (foo-bar, foo_bar) share a normalized name.
        if (object.has(name)) return object.get(name);
        Iterator<Map.Entry<String, JsonNode>> fields = object.properties().iterator();
        while (fields.hasNext()) {
            Map.Entry<String, JsonNode> entry = fields.next();
            if (normalized(entry.getKey()).equals(normalized(name))) return entry.getValue();
        }
        return null;
    }

    private static boolean delegating(Class<?> type) {
        for (Constructor<?> constructor : type.getDeclaredConstructors()) {
            if (isDelegatingCreator(constructor.getAnnotation(
                com.fasterxml.jackson.annotation.JsonCreator.class))) return true;
        }
        for (Method method : type.getDeclaredMethods()) {
            if (isDelegatingCreator(method.getAnnotation(
                com.fasterxml.jackson.annotation.JsonCreator.class))) return true;
        }
        return false;
    }

    private static boolean isDelegatingCreator(
        com.fasterxml.jackson.annotation.JsonCreator creator) {
        return creator != null
            && creator.mode() == com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING;
    }

    private static boolean aggregate(Class<?> type) {
        // A parameter object standing in for the whole argument list, whose fields
        // the fixture states at the top level under no name of its own. It is
        // declared inside the class holding the method, which is what separates it
        // from a body typed as a model whose name happens to end the same way.
        if (type.getEnclosingClass() == null) return false;
        String name = type.getSimpleName();
        return name.endsWith("Request") || name.endsWith("Params") || name.endsWith("Options");
    }

    private static Object convert(Type target, JsonNode value) throws ReflectiveOperationException {
        JavaType javaType = MAPPER.getTypeFactory().constructType(target);
        Class<?> raw = javaType.getRawClass();
        if (value == null || value.isNull()) return raw.isPrimitive() ? MAPPER.convertValue(0, javaType) : null;
        if (java.util.List.class.isAssignableFrom(raw)
            && target instanceof java.lang.reflect.ParameterizedType listType) {
            // Converted one element at a time, so an element type this method
            // knows how to build - a file part, say - is built the same way in
            // a list as it is on its own.
            Type element = listType.getActualTypeArguments()[0];
            java.util.List<Object> items = new java.util.ArrayList<>();
            for (JsonNode item : value) items.add(convert(element, item));
            return items;
        }
        if (raw.isPrimitive() || raw.isEnum() || raw.getName().startsWith("java.") || raw == Object.class) {
            return MAPPER.convertValue(value, javaType);
        }
        if (raw.isInterface() || Modifier.isAbstract(raw.getModifiers())) {
            // A union is an annotated interface: it declares no constructor to
            // reflect over, and its variant is already selected by Jackson from
            // the discriminator the generated subtypes register.
            return MAPPER.convertValue(value, javaType);
        }
        if (raw.getSimpleName().equals("OptionalValue")) {
            // A tri-state optional parameter. The fixture states a value, so the
            // call has to receive it as present; the wrapper hides its constructor
            // behind the two factories instead.
            Type inner = target instanceof java.lang.reflect.ParameterizedType parameterized
                ? parameterized.getActualTypeArguments()[0]
                : Object.class;
            return raw.getMethod("present", Object.class).invoke(null, convert(inner, value));
        }
        if (raw.getSimpleName().equals("UploadFile")) {
            // A multipart file part. The fixture states the file as its text,
            // which is the payload the mock compares against.
            String text = value.isTextual() ? value.asText() : value.toString();
            return raw.getConstructor(byte[].class, String.class, String.class)
                .newInstance(text.getBytes(java.nio.charset.StandardCharsets.UTF_8), "upload", null);
        }
        if (!value.isObject() || delegating(raw)) {
            // Only an object node has properties to match against constructor
            // parameters. A scalar reaching a generated class means the class
            // wraps that scalar - an open enum, say - and it declares the creator
            // Jackson needs to build it. A class with a delegating creator takes
            // the whole node the same way: a free-form map holds its entries in
            // one field the payload never names, and matching that field against
            // the payload's own keys hands the constructor nothing.
            return MAPPER.convertValue(value, javaType);
        }
        Constructor<?>[] constructors = raw.getDeclaredConstructors();
        Constructor<?> noArgs = null;
        for (Constructor<?> constructor : constructors) if (constructor.getParameterCount() == 0) noArgs = constructor;
        if (noArgs != null) {
            noArgs.setAccessible(true);
            Object instance = noArgs.newInstance();
            for (Field field : raw.getDeclaredFields()) {
                if (Modifier.isStatic(field.getModifiers()) || field.isSynthetic()) continue;
                JsonNode child = byName(value, field.getName());
                if (child == null) continue;
                field.setAccessible(true);
                field.set(instance, convert(field.getGenericType(), child));
            }
            return instance;
        }
        Constructor<?> constructor = constructors[0];
        constructor.setAccessible(true);
        Field[] fields = raw.getDeclaredFields();
        List<Field> instanceFields = new ArrayList<>();
        for (Field field : fields) {
            if (!Modifier.isStatic(field.getModifiers()) && !field.isSynthetic()) instanceFields.add(field);
        }
        Object[] values = new Object[constructor.getParameterCount()];
        Type[] types = constructor.getGenericParameterTypes();
        for (int index = 0; index < values.length; index++) {
            Field field = instanceFields.get(index);
            values[index] = convert(types[index], byName(value, field.getName()));
        }
        return constructor.newInstance(values);
    }

    private static Method targetMethod(Class<?> owner, String name) {
        for (Method method : owner.getMethods()) {
            if (method.getName().equals(name) && !method.isSynthetic()) return method;
        }
        throw new IllegalStateException("No generated method " + owner.getName() + "." + name);
    }

    private static Instant instant(String value) {
        try {
            return OffsetDateTime.parse(value).toInstant();
        } catch (DateTimeParseException notTimestamp) {
            return null;
        }
    }

    /** The path at which the decoded response departs from the mock, or null when it does not. */
    private static String mismatch(JsonNode actual, JsonNode expected, String path) {
        if (expected == null || expected.isNull()) {
            return actual == null || actual.isNull() ? null : path + ": expected null, decoded " + actual;
        }
        // OpenAPI examples sometimes use an empty string for nullable temporal fields.
        // Jackson correctly decodes those placeholders as null, so compare them as equivalent.
        if (expected.isTextual() && expected.asText().isEmpty() && (actual == null || actual.isNull())) {
            return null;
        }
        if (expected.isObject()) {
            if (actual == null || !actual.isObject()) return path + ": expected an object, decoded " + actual;
            Iterator<Map.Entry<String, JsonNode>> fields = expected.properties().iterator();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> entry = fields.next();
                JsonNode child = byName(actual, entry.getKey());
                if (child == null) return path + "." + entry.getKey() + ": missing from the decoded response";
                String found = mismatch(child, entry.getValue(), path + "." + entry.getKey());
                if (found != null) return found;
            }
            return null;
        }
        if (expected.isArray()) {
            if (actual == null || !actual.isArray()) return path + ": expected an array, decoded " + actual;
            if (actual.size() != expected.size()) {
                return path + ": decoded " + actual.size() + " items, the mock states " + expected.size();
            }
            for (int index = 0; index < expected.size(); index++) {
                String found = mismatch(actual.get(index), expected.get(index), path + "[" + index + "]");
                if (found != null) return found;
            }
            return null;
        }
        // A number is compared by value: a field typed as a floating point
        // decodes 0 as 0.0, which is the same number the mock stated.
        if (expected.isNumber()) {
            boolean same = actual != null && actual.isNumber()
                && expected.decimalValue().compareTo(actual.decimalValue()) == 0;
            return same ? null : path + ": decoded " + actual + ", the mock states " + expected;
        }
        // A timestamp is compared as an instant: the mock states whatever
        // precision the API documents, and the SDK writes its own.
        if (expected.isTextual() && actual != null && actual.isTextual()) {
            Instant wanted = instant(expected.asText());
            if (wanted != null && wanted.equals(instant(actual.asText()))) return null;
        }
        // Decoded bytes stay a binary node; their text is the base64 the mock sent.
        if (expected.isTextual() && actual != null && actual.isBinary()) {
            return expected.asText().equals(actual.asText()) ? null : path + ": decoded " + actual + ", the mock states " + expected;
        }
        return expected.equals(actual) ? null : path + ": decoded " + actual + ", the mock states " + expected;
    }

    @Test
    void everyGeneratedMethodReachesMockAndDecodesItsResponse() throws Exception {
        String baseUrl = System.getenv("SDK_METHOD_TEST_BASE_URL");
        if (baseUrl == null || baseUrl.isBlank()) return;
        SdkConfig.ClientConfig config = new SdkConfig.ClientConfig();
        config.baseUrl = baseUrl;
        SdkConfig.configureClient(config);
        JsonNode cases = MAPPER.readTree(new File("test/sdk-method-cases.json")).get("cases");
        assertTrue(cases.size() > 0, "method fixture is empty");
        for (JsonNode testCase : cases) {
            Class<?> owner = Class.forName(testCase.get("owner").asText());
            Method method = targetMethod(owner, testCase.get("methodName").asText());
            JsonNode arguments = testCase.get("arguments");
            JsonNode order = testCase.get("argumentOrder");
            Object[] values = new Object[method.getParameterCount()];
            Parameter[] parameters = method.getParameters();
            int positional = 0;
            for (int index = 0; index < parameters.length; index++) {
                Parameter parameter = parameters[index];
                Class<?> type = parameter.getType();
                if (type == SdkConfig.ClientConfig.class) {
                    values[index] = SdkConfig.getClientConfig();
                } else if (aggregate(type)) {
                    values[index] = convert(parameter.getParameterizedType(), arguments);
                } else {
                    JsonNode input = byName(arguments, parameter.getName());
                    if (input == null && positional < order.size()) input = byName(arguments, order.get(positional++).asText());
                    values[index] = convert(parameter.getParameterizedType(), input);
                }
            }
            Object actual = method.invoke(null, values);
            if ("stream".equals(testCase.get("mode").asText()) && actual instanceof java.util.stream.Stream<?> stream) {
                try (stream) {
                    actual = stream.findFirst().orElse(null);
                }
            }
            JsonNode response = testCase.get("response");
            if ("empty".equals(response.get("kind").asText())) {
                assertEquals(null, actual, testCase.get("id").asText());
            } else if ("bytes".equals(response.get("kind").asText())) {
                assertEquals(response.get("byteLength").asInt(), ((byte[]) actual).length, testCase.get("id").asText());
            } else {
                assertNull(
                    mismatch(MAPPER.valueToTree(actual), response.get("expected"), "response"),
                    testCase.get("id").asText() + " decoded a response that differs from the mock"
                );
            }
        }
    }
}
