// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.config_property;

/**
 * Type of the property
 */
public final class ConfigPropertyResponsePropertyTypeEnum {
    public static final ConfigPropertyResponsePropertyTypeEnum BOOLEAN = new ConfigPropertyResponsePropertyTypeEnum("BOOLEAN");
    public static final ConfigPropertyResponsePropertyTypeEnum INTEGER = new ConfigPropertyResponsePropertyTypeEnum("INTEGER");
    public static final ConfigPropertyResponsePropertyTypeEnum NUMBER = new ConfigPropertyResponsePropertyTypeEnum("NUMBER");
    public static final ConfigPropertyResponsePropertyTypeEnum STRING = new ConfigPropertyResponsePropertyTypeEnum("STRING");
    public static final ConfigPropertyResponsePropertyTypeEnum TIMESTAMP = new ConfigPropertyResponsePropertyTypeEnum("TIMESTAMP");
    public static final ConfigPropertyResponsePropertyTypeEnum URL = new ConfigPropertyResponsePropertyTypeEnum("URL");
    public static final ConfigPropertyResponsePropertyTypeEnum UUID = new ConfigPropertyResponsePropertyTypeEnum("UUID");
    private final String value;
    private ConfigPropertyResponsePropertyTypeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ConfigPropertyResponsePropertyTypeEnum fromValue(String value) {
        if ("BOOLEAN".equals(value)) return BOOLEAN;
        if ("INTEGER".equals(value)) return INTEGER;
        if ("NUMBER".equals(value)) return NUMBER;
        if ("STRING".equals(value)) return STRING;
        if ("TIMESTAMP".equals(value)) return TIMESTAMP;
        if ("URL".equals(value)) return URL;
        if ("UUID".equals(value)) return UUID;
        return new ConfigPropertyResponsePropertyTypeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ConfigPropertyResponsePropertyTypeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
