// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.license_group;

import dependencytrackunofficialsdk.Validation;
import dependencytrackunofficialsdk.models.shared_license.License;
import java.util.List;

/**
 * LicenseGroupResponse.
 * Typed representation of the `LicenseGroupResponse` API schema.
 */

public final class LicenseGroupResponse {
    /**
     * Licenses belonging to the license group
     */
    public List<License> licenses;
    /**
     * Name of the license group
     */
    public String name;
    /**
     * Risk weight assigned to violations of this group
     */
    public Integer riskWeight;
    /**
     * UUID of the license group
     */
    public String uuid;
    private LicenseGroupResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private List<License> licenses;
        private String name;
        private Integer riskWeight;
        private String uuid;
        public Builder licenses(List<License> value) { this.licenses = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder riskWeight(Integer value) { this.riskWeight = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public LicenseGroupResponse build() {
            LicenseGroupResponse result = new LicenseGroupResponse();
            Validation.validateRequired("licenses", this.licenses);
            result.licenses = this.licenses;
            Validation.validateRequired("name", this.name);
            result.name = this.name;
            Validation.validateRequired("riskWeight", this.riskWeight);
            result.riskWeight = this.riskWeight;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "LicenseGroupResponse{"
            + "licenses=" + licenses
            + ", name=" + name
            + ", riskWeight=" + riskWeight
            + ", uuid=" + uuid
            + "}";
    }
}
