// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.license_group;

import dependencytrackunofficialsdk.Validation;

/**
 * UpdateLicenseGroupRequest.
 * Typed representation of the `UpdateLicenseGroupRequest` API schema.
 */

public final class UpdateLicenseGroupRequest {
    /**
     * New name of the license group
     */
    public String name;
    /**
     * UUID of the license group to update
     */
    public String uuid;
    private UpdateLicenseGroupRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private String uuid;
        public Builder name(String value) { this.name = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public UpdateLicenseGroupRequest build() {
            UpdateLicenseGroupRequest result = new UpdateLicenseGroupRequest();
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "UpdateLicenseGroupRequest{"
            + "name=" + name
            + ", uuid=" + uuid
            + "}";
    }
}
