// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.team;

import dependencytrackunofficialsdk.Validation;
import dependencytrackunofficialsdk.models.shared.Permission;
import java.util.List;
import javax.annotation.Nullable;

/**
 * TeamSelfResponse.
 * Typed representation of the `TeamSelfResponse` API schema.
 */

public final class TeamSelfResponse {
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    @Nullable public String name;
    /**
     * Optional array value serialized in the `permissions` wire field.
     */
    @Nullable public List<Permission> permissions;
    /**
     * Optional `uuid`-formatted value serialized in the `uuid` wire field.
     */
    @Nullable public String uuid;
    private TeamSelfResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String name;
        private List<Permission> permissions;
        private String uuid;
        public Builder name(String value) { this.name = value; return this; }
        public Builder permissions(List<Permission> value) { this.permissions = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public TeamSelfResponse build() {
            TeamSelfResponse result = new TeamSelfResponse();
            result.name = this.name;
            result.permissions = this.permissions;
            if (this.uuid != null) {
                Validation.validateUuid("uuid", this.uuid);
            }
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "TeamSelfResponse{"
            + "name=" + name
            + ", permissions=" + permissions
            + ", uuid=" + uuid
            + "}";
    }
}
