// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_component;

/**
 * Required enumerated value serialized in the `propertyType` wire field.
 */
public final class ComponentPropertyPropertyTypeEnum {
    public static final ComponentPropertyPropertyTypeEnum BOOLEAN = new ComponentPropertyPropertyTypeEnum("BOOLEAN");
    public static final ComponentPropertyPropertyTypeEnum INTEGER = new ComponentPropertyPropertyTypeEnum("INTEGER");
    public static final ComponentPropertyPropertyTypeEnum NUMBER = new ComponentPropertyPropertyTypeEnum("NUMBER");
    public static final ComponentPropertyPropertyTypeEnum STRING = new ComponentPropertyPropertyTypeEnum("STRING");
    public static final ComponentPropertyPropertyTypeEnum TIMESTAMP = new ComponentPropertyPropertyTypeEnum("TIMESTAMP");
    public static final ComponentPropertyPropertyTypeEnum URL = new ComponentPropertyPropertyTypeEnum("URL");
    public static final ComponentPropertyPropertyTypeEnum UUID = new ComponentPropertyPropertyTypeEnum("UUID");
    private final String value;
    private ComponentPropertyPropertyTypeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static ComponentPropertyPropertyTypeEnum fromValue(String value) {
        if ("BOOLEAN".equals(value)) return BOOLEAN;
        if ("INTEGER".equals(value)) return INTEGER;
        if ("NUMBER".equals(value)) return NUMBER;
        if ("STRING".equals(value)) return STRING;
        if ("TIMESTAMP".equals(value)) return TIMESTAMP;
        if ("URL".equals(value)) return URL;
        if ("UUID".equals(value)) return UUID;
        return new ComponentPropertyPropertyTypeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof ComponentPropertyPropertyTypeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
