// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.dependency_graph;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * DependencyGraphResponse.
 * Typed representation of the `DependencyGraphResponse` API schema.
 */

public final class DependencyGraphResponse {
    /**
     * Optional `string` value serialized in the `directDependencies` wire field.
     */
    @Nullable public String directDependencies;
    /**
     * Optional `string` value serialized in the `latestVersion` wire field.
     */
    @Nullable public String latestVersion;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    @Nullable public String name;
    /**
     * Optional `string` value serialized in the `purl` wire field.
     */
    @Nullable public String purl;
    /**
     * Optional `uuid`-formatted value serialized in the `uuid` wire field.
     */
    @Nullable public String uuid;
    /**
     * Optional `string` value serialized in the `version` wire field.
     */
    @Nullable public String version;
    private DependencyGraphResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String directDependencies;
        private String latestVersion;
        private String name;
        private String purl;
        private String uuid;
        private String version;
        public Builder directDependencies(String value) { this.directDependencies = value; return this; }
        public Builder latestVersion(String value) { this.latestVersion = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder purl(String value) { this.purl = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public DependencyGraphResponse build() {
            DependencyGraphResponse result = new DependencyGraphResponse();
            result.directDependencies = this.directDependencies;
            result.latestVersion = this.latestVersion;
            result.name = this.name;
            result.purl = this.purl;
            if (this.uuid != null) {
                Validation.validateUuid("uuid", this.uuid);
            }
            result.uuid = this.uuid;
            result.version = this.version;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "DependencyGraphResponse{"
            + "directDependencies=" + directDependencies
            + ", latestVersion=" + latestVersion
            + ", name=" + name
            + ", purl=" + purl
            + ", uuid=" + uuid
            + ", version=" + version
            + "}";
    }
}
