// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk;

import java.time.Duration;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

public class SdkConfig {

    /**
     * A single in-flight HTTP attempt as seen by middleware. Mutate `headers`
     * or `body` to alter the request before it hits the wire. `meta` is a
     * free-form map middleware can use to share state across the chain.
     */
    public static final class SdkRequest {
        public String method;
        public String url;
        public Map<String, String> headers;
        public String body;
        // Raw body bytes (multipart/form-data, octet-stream); when set it takes
        // precedence over `body` so binary content is sent byte-faithfully.
        public byte[] bodyBytes;
        public String contentType;
        public String operationId;
        public int attempt;
        public Map<String, Object> meta;

        public SdkRequest() { this.headers = new HashMap<>(); this.meta = new HashMap<>(); }
    }

    /** Raw response visible to middleware. Body bytes are never pre-decoded. */
    public static final class SdkRawResponse {
        public int statusCode;
        public String statusText;
        public Map<String, String> headers;
        public byte[] body;
        public String requestId;
        public Duration latency;
        public int attempt;
    }

    /** Innermost continuation in a middleware chain. */
    @FunctionalInterface
    public interface SdkNext {
        SdkRawResponse handle(SdkRequest request);
    }

    /**
     * User-supplied request interceptor. Runs once per HTTP attempt — retries
     * pass through the chain N times. Compose logging, tracing, caching, etc.
     * without forking the generator.
     *
     * <pre>
     * SdkConfig.Middleware logger = (req, next) -&gt; {
     *     SdkConfig.SdkRawResponse resp = next.handle(req);
     *     System.out.println(req.method + " " + req.url + " -&gt; " + resp.statusCode);
     *     return resp;
     * };
     * </pre>
     */
    @FunctionalInterface
    public interface Middleware {
        SdkRawResponse handle(SdkRequest request, SdkNext next);
    }

    /** Controls Idempotency-Key generation. Enabled by default for POST/PATCH. */
    public static final class IdempotencyConfig {
        public boolean enabled = true;
        public String headerName = "Idempotency-Key";
        public List<String> methods = Arrays.asList("POST", "PATCH");
    }

    public static class ClientAuthConfig {


        public String apiKeyAuth;

        public String bearerAuth;

        public Map<String, String> headers;
    }


    public static class LoggingConfig {
        public Boolean enabled;
        public String endpoint;
        public String apiKey;
        // Enrichment forwarded with every logged event.
        public String environment;
        public String release;
        public Map<String, Object> user;
        public Map<String, Object> tags;
        /** Redacts common credentials and direct identifiers before telemetry (default true). */
        public Boolean filterPii = Boolean.TRUE;
    }

    public static class RetryConfig {
        public int maxAttempts = 3;
        public List<Integer> retryOn = Arrays.asList(408, 425, 429, 500, 502, 503, 504);
        public Duration backoff = Duration.ofMillis(500);
        public Duration maxBackoff = Duration.ofSeconds(8);
    }

    /**
     * Per-call options every generated operation accepts in an overload. Each
     * set field applies to that call only, over the client config. Streaming
     * operations apply only {@code headers}.
     */
    public static class RequestOptions {
        /** Merged over the auth and operation headers for this call. */
        public Map<String, String> headers = new HashMap<>();
        /** Replaces the generated Idempotency-Key; an empty key sends none. */
        public String idempotencyKey;
        /** Replaces the client retry policy. */
        public RetryConfig retry;
        /** Replaces the client per-attempt timeout. */
        public Duration timeout;
    }

    public static class ClientConfig {
        public String baseUrl;
        public ClientAuthConfig auth;
        public LoggingConfig logging;
        public RetryConfig retry;
        public IdempotencyConfig idempotency;
        public Duration timeout;
        public Consumer<SdkResponse<?>> onResponse;
        /**
         * Middleware chain. Replaced wholesale on configureClient(); to extend,
         * read the current value and pass a new list including the previous
         * entries.
         */
        public List<Middleware> middleware = Collections.emptyList();
    }

    private static ClientConfig clientConfig = new ClientConfig();

    static {
        clientConfig.baseUrl = "http://localhost:8081/api";
        clientConfig.logging = new LoggingConfig();
        // The reporting endpoint is baked in from the dashboard monitoring config,
        // but logging stays OFF at rest: nothing is reported until the consumer
        // opts in via setLoggingConfig(...) or a ClientConfig with logging enabled.
        clientConfig.logging.enabled = false;
        clientConfig.logging.endpoint = null;
        clientConfig.logging.apiKey = null;
        clientConfig.logging.environment = null;
        clientConfig.retry = new RetryConfig();
        clientConfig.idempotency = new IdempotencyConfig();
        clientConfig.timeout = Duration.ofSeconds(30);
    }

    /**
     * Replaces or merges into the global SDK configuration. Non-null fields on
     * the provided config override the current config.
     */
    public static ClientConfig configureClient(ClientConfig config) {
        if (config != null) {
            if (config.baseUrl != null) clientConfig.baseUrl = config.baseUrl;
            if (config.auth != null) clientConfig.auth = config.auth;
            if (config.logging != null) clientConfig.logging = config.logging;
            if (config.retry != null) clientConfig.retry = config.retry;
            if (config.idempotency != null) clientConfig.idempotency = config.idempotency;
            if (config.timeout != null) clientConfig.timeout = config.timeout;
            if (config.onResponse != null) clientConfig.onResponse = config.onResponse;
            if (config.middleware != null && !config.middleware.isEmpty()) clientConfig.middleware = config.middleware;
        }
        return clientConfig;
    }

    public static ClientConfig getClientConfig() {
        return clientConfig;
    }

    /**
     * Turns SDK logging on and configures it in one call.
     *
     * <p>Logging is OFF by default — this SDK reports nothing until you ask it to.
     * There are exactly two ways to turn it on:
     *
     * <pre>
     *   ClientConfig c = new ClientConfig();
     *   c.logging = new LoggingConfig();
     *   c.logging.enabled = true;
     *   configureClient(c);              // at init
     *
     *   setLoggingConfig(null);          // any time after
     * </pre>
     *
     * <p>Reports go to the endpoint this build was generated with, or to the
     * {@code endpoint} you pass; with neither, nothing is sent. Pass a
     * {@link LoggingConfig} to set the endpoint, environment, release, tags, etc.
     * Its {@code enabled} flag is honoured only when explicitly set to
     * {@code FALSE} (the field is a {@code Boolean}, so an unset value stays
     * {@code null}) — otherwise calling this method IS the opt-in.
     */
    public static LoggingConfig setLoggingConfig(LoggingConfig config) {
        if (clientConfig.logging == null) clientConfig.logging = new LoggingConfig();
        LoggingConfig current = clientConfig.logging;
        if (config != null) {
            if (config.endpoint != null) current.endpoint = config.endpoint;
            if (config.apiKey != null) current.apiKey = config.apiKey;
            if (config.environment != null) current.environment = config.environment;
            if (config.release != null) current.release = config.release;
            if (config.user != null) current.user = config.user;
            if (config.tags != null) current.tags = config.tags;
            if (config.filterPii != null) current.filterPii = config.filterPii;
        }
        // Opting in IS the point of this call, so enabled flips to true unless the
        // caller explicitly said FALSE — which makes this the off switch too.
        current.enabled = (config == null || config.enabled == null) ? Boolean.TRUE : config.enabled;
        return current;
    }
}
