// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk;

import java.util.Map;

/**
 * Thrown for an HTTP 404 response.
 */
public final class SdkNotFoundError extends SdkHttpError {
    private static final long serialVersionUID = 1L;

    public SdkNotFoundError(int statusCode, String statusText, byte[] body, Map<String, String> headers, String requestId) {
        super(statusCode, statusText, body, headers, requestId);
    }
}
