// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk;

import java.util.Collections;
import java.util.Map;

/**
 * Returned when a method argument fails an OpenAPI constraint pre-flight.
 */
public final class SdkValidationError extends SdkError {
    private static final long serialVersionUID = 1L;

    public final String field;
    public final String code;
    public final transient Map<String, Object> meta;

    public SdkValidationError(String field, String code, String message) {
        this(field, code, message, Collections.emptyMap());
    }

    public SdkValidationError(String field, String code, String message, Map<String, Object> meta) {
        super(message);
        this.field = field;
        this.code = code;
        this.meta = meta != null ? Collections.unmodifiableMap(meta) : Collections.emptyMap();
    }
}
