// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk;import java.util.UUID;import java.time.OffsetDateTime;
import java.time.format.DateTimeParseException;import java.net.URI;import java.util.List;/**
 * Canonical validation helpers. Each throws {@link SdkValidationError} on failure.
 */
public final class Validation {
    private Validation() {}

    public static void validateRequired(String field, Object value) {
        if (value == null) {
            throw new SdkValidationError(field, "required",
                "Validation failed for '" + field + "': value is required");
        }
    }
private static String stringValue(Object value) {
        return String.valueOf(value);
    }
    public static void validateEnum(String field, Object value, List<?> allowed) {
        if (value == null) return;
        // Compare via toString so generated Java enums and String literals
        // round-trip cleanly (e.g. UserStatus.ACTIVE.toString() == "active").
        String s = stringValue(value);
        for (Object a : allowed) {
            if (s.equals(String.valueOf(a))) return;
        }
        StringBuilder list = new StringBuilder();
        for (int i = 0; i < allowed.size(); i++) {
            if (i > 0) list.append(", ");
            list.append(allowed.get(i));
        }
        throw new SdkValidationError(field, "enum",
            "Validation failed for '" + field + "': must be one of " + list);
    }

    public static class RangeOpts {
        public Double min;
        public Double max;
        public Double exclusiveMin;
        public Double exclusiveMax;
        public Double multipleOf;
    }

    public static void validateRange(String field, Object value, RangeOpts opts) {
        if (value instanceof Number number) {
            validateRange(field, number, opts);
        }
    }

    public static void validateRange(String field, Number value, RangeOpts opts) {
        double v = value.doubleValue();
        if (opts.min != null && v < opts.min) {
            throw rangeErr(field, "must be >= " + opts.min);
        }
        if (opts.max != null && v > opts.max) {
            throw rangeErr(field, "must be <= " + opts.max);
        }
        if (opts.exclusiveMin != null && v <= opts.exclusiveMin) {
            throw rangeErr(field, "must be > " + opts.exclusiveMin);
        }
        if (opts.exclusiveMax != null && v >= opts.exclusiveMax) {
            throw rangeErr(field, "must be < " + opts.exclusiveMax);
        }
        if (opts.multipleOf != null && opts.multipleOf != 0) {
            double quotient = v / opts.multipleOf;
            double nearestInteger = Math.rint(quotient);
            double tolerance = Math.ulp(quotient) * 4;
            if (Math.abs(quotient - nearestInteger) > tolerance) {
                throw rangeErr(field, "must be a multiple of " + opts.multipleOf);
            }
        }
    }

    private static SdkValidationError rangeErr(String field, String msg) {
        return new SdkValidationError(field, "range",
            "Validation failed for '" + field + "': " + msg);
    }

    public static class LengthOpts {
        public Integer min;
        public Integer max;
    }

    public static void validateLength(String field, Object value, LengthOpts opts) {
        int n = stringValue(value).length();
        if (opts.min != null && n < opts.min) {
            throw new SdkValidationError(field, "length",
                "Validation failed for '" + field + "': length must be >= " + opts.min);
        }
        if (opts.max != null && n > opts.max) {
            throw new SdkValidationError(field, "length",
                "Validation failed for '" + field + "': length must be <= " + opts.max);
        }
    }

    public static void validateItems(String field, java.util.Collection<?> value, LengthOpts opts) {
        int n = value.size();
        if (opts.min != null && n < opts.min) {
            throw new SdkValidationError(field, "items",
                "Validation failed for '" + field + "': must have at least " + opts.min + " items");
        }
        if (opts.max != null && n > opts.max) {
            throw new SdkValidationError(field, "items",
                "Validation failed for '" + field + "': must have at most " + opts.max + " items");
        }
    }

    public static void validatePattern(String field, Object value, String pattern) {
        if (!java.util.regex.Pattern.compile(pattern).matcher(stringValue(value)).find()) {
            throw new SdkValidationError(field, "pattern",
                "Validation failed for '" + field + "': must match pattern " + pattern);
        }
    }

    public static void validateUri(String field, Object value) {
        try {
            URI uri = URI.create(stringValue(value));
            if (uri.getScheme() == null || uri.getHost() == null) {
                throw new IllegalArgumentException();
            }
        } catch (Exception e) {
            throw new SdkValidationError(field, "format:uri",
                "Validation failed for '" + field + "': must be a valid URI");
        }
    }

    public static void validateUuid(String field, Object value) {
        try {
            UUID.fromString(stringValue(value));
        } catch (IllegalArgumentException e) {
            throw new SdkValidationError(field, "format:uuid",
                "Validation failed for '" + field + "': must be a valid UUID");
        }
    }

    public static void validateDateTime(String field, Object value) {
        if (value instanceof java.time.OffsetDateTime) return;
        try {
            OffsetDateTime.parse(stringValue(value));
        } catch (DateTimeParseException offsetError) {
            throw new SdkValidationError(field, "format:date-time",
                "Validation failed for '" + field + "': must be an RFC 3339 date-time with a UTC indicator or offset");
        }
    }

}
