// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_policy;

/**
 * Required enumerated value serialized in the `operator` wire field.
 */
public final class PolicyConditionOperatorEnum {
    public static final PolicyConditionOperatorEnum IS = new PolicyConditionOperatorEnum("IS");
    public static final PolicyConditionOperatorEnum IS_NOT = new PolicyConditionOperatorEnum("IS_NOT");
    public static final PolicyConditionOperatorEnum MATCHES = new PolicyConditionOperatorEnum("MATCHES");
    public static final PolicyConditionOperatorEnum NO_MATCH = new PolicyConditionOperatorEnum("NO_MATCH");
    public static final PolicyConditionOperatorEnum NUMERIC_GREATER_THAN = new PolicyConditionOperatorEnum("NUMERIC_GREATER_THAN");
    public static final PolicyConditionOperatorEnum NUMERIC_LESS_THAN = new PolicyConditionOperatorEnum("NUMERIC_LESS_THAN");
    public static final PolicyConditionOperatorEnum NUMERIC_EQUAL = new PolicyConditionOperatorEnum("NUMERIC_EQUAL");
    public static final PolicyConditionOperatorEnum NUMERIC_NOT_EQUAL = new PolicyConditionOperatorEnum("NUMERIC_NOT_EQUAL");
    public static final PolicyConditionOperatorEnum NUMERIC_GREATER_THAN_OR_EQUAL = new PolicyConditionOperatorEnum("NUMERIC_GREATER_THAN_OR_EQUAL");
    public static final PolicyConditionOperatorEnum NUMERIC_LESSER_THAN_OR_EQUAL = new PolicyConditionOperatorEnum("NUMERIC_LESSER_THAN_OR_EQUAL");
    public static final PolicyConditionOperatorEnum CONTAINS_ALL = new PolicyConditionOperatorEnum("CONTAINS_ALL");
    public static final PolicyConditionOperatorEnum CONTAINS_ANY = new PolicyConditionOperatorEnum("CONTAINS_ANY");
    private final String value;
    private PolicyConditionOperatorEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static PolicyConditionOperatorEnum fromValue(String value) {
        if ("IS".equals(value)) return IS;
        if ("IS_NOT".equals(value)) return IS_NOT;
        if ("MATCHES".equals(value)) return MATCHES;
        if ("NO_MATCH".equals(value)) return NO_MATCH;
        if ("NUMERIC_GREATER_THAN".equals(value)) return NUMERIC_GREATER_THAN;
        if ("NUMERIC_LESS_THAN".equals(value)) return NUMERIC_LESS_THAN;
        if ("NUMERIC_EQUAL".equals(value)) return NUMERIC_EQUAL;
        if ("NUMERIC_NOT_EQUAL".equals(value)) return NUMERIC_NOT_EQUAL;
        if ("NUMERIC_GREATER_THAN_OR_EQUAL".equals(value)) return NUMERIC_GREATER_THAN_OR_EQUAL;
        if ("NUMERIC_LESSER_THAN_OR_EQUAL".equals(value)) return NUMERIC_LESSER_THAN_OR_EQUAL;
        if ("CONTAINS_ALL".equals(value)) return CONTAINS_ALL;
        if ("CONTAINS_ANY".equals(value)) return CONTAINS_ANY;
        return new PolicyConditionOperatorEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof PolicyConditionOperatorEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
