// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.shared_policy;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * PolicyCondition.
 * Typed representation of the `PolicyCondition` API schema.
 */

public final class PolicyCondition {
    /**
     * Required enumerated value serialized in the `operator` wire field.
     */
    public PolicyConditionOperatorEnum operator;
    /**
     * Required enumerated value serialized in the `subject` wire field.
     */
    public PolicyConditionSubjectEnum subject;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Required `string` value serialized in the `value` wire field.
     */
    public String value;
    /**
     * Optional object value serialized in the `policy` wire field.
     */
    @Nullable public Policy policy;
    /**
     * Optional enumerated value serialized in the `violationType` wire field.
     */
    @Nullable public PolicyConditionViolationTypeEnum violationType;
    private PolicyCondition() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private PolicyConditionOperatorEnum operator;
        private PolicyConditionSubjectEnum subject;
        private String uuid;
        private String value;
        private Policy policy;
        private PolicyConditionViolationTypeEnum violationType;
        public Builder operator(PolicyConditionOperatorEnum value) { this.operator = value; return this; }
        public Builder subject(PolicyConditionSubjectEnum value) { this.subject = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder value(String value) { this.value = value; return this; }
        public Builder policy(Policy value) { this.policy = value; return this; }
        public Builder violationType(PolicyConditionViolationTypeEnum value) { this.violationType = value; return this; }
        public PolicyCondition build() {
            PolicyCondition result = new PolicyCondition();
            Validation.validateRequired("operator", this.operator);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("operator", this.operator, __length); }
            result.operator = this.operator;
            Validation.validateRequired("subject", this.subject);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("subject", this.subject, __length); }
            result.subject = this.subject;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            Validation.validateRequired("value", this.value);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 2147483647; Validation.validateLength("value", this.value, __length); }
            result.value = this.value;
            result.policy = this.policy;
            if (this.violationType != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("violationType", this.violationType, __length); }
            }
            result.violationType = this.violationType;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "PolicyCondition{"
            + "operator=" + operator
            + ", subject=" + subject
            + ", uuid=" + uuid
            + ", value=" + value
            + ", policy=" + policy
            + ", violationType=" + violationType
            + "}";
    }
}
