// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.ldap;

import dependencytrackunofficialsdk.Validation;

/**
 * MappedLdapGroupResponse.
 * Typed representation of the `MappedLdapGroupResponse` API schema.
 */

public final class MappedLdapGroupResponse {
    /**
     * Distinguished name of the mapped LDAP group
     */
    public String dn;
    /**
     * UUID of the mapping
     */
    public String uuid;
    private MappedLdapGroupResponse() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String dn;
        private String uuid;
        public Builder dn(String value) { this.dn = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public MappedLdapGroupResponse build() {
            MappedLdapGroupResponse result = new MappedLdapGroupResponse();
            Validation.validateRequired("dn", this.dn);
            result.dn = this.dn;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "MappedLdapGroupResponse{"
            + "dn=" + dn
            + ", uuid=" + uuid
            + "}";
    }
}
