// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.project;

import com.fasterxml.jackson.annotation.JsonProperty;
import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * CloneProjectRequest.
 * Typed representation of the `CloneProjectRequest` API schema.
 */

public final class CloneProjectRequest {
    /**
     * Required `string` value serialized in the `project` wire field.
     */
    public String project;
    /**
     * Required `string` value serialized in the `version` wire field.
     */
    public String version;
    /**
     * Optional `boolean` value serialized in the `includeACL` wire field.
     */
    @Nullable @JsonProperty("includeACL") public Boolean includeAcl;
    /**
     * Optional `boolean` value serialized in the `includeAuditHistory` wire field.
     */
    @Nullable public Boolean includeAuditHistory;
    /**
     * Optional `boolean` value serialized in the `includeComponents` wire field.
     */
    @Nullable public Boolean includeComponents;
    /**
     * Optional `boolean` value serialized in the `includeDependencies` wire field.
     */
    @Nullable public Boolean includeDependencies;
    /**
     * Optional `boolean` value serialized in the `includePolicyViolations` wire field.
     */
    @Nullable public Boolean includePolicyViolations;
    /**
     * Optional `boolean` value serialized in the `includeProperties` wire field.
     */
    @Nullable public Boolean includeProperties;
    /**
     * Optional `boolean` value serialized in the `includeServices` wire field.
     */
    @Nullable public Boolean includeServices;
    /**
     * Optional `boolean` value serialized in the `includeTags` wire field.
     */
    @Nullable public Boolean includeTags;
    /**
     * Optional `boolean` value serialized in the `makeCloneLatest` wire field.
     */
    @Nullable public Boolean makeCloneLatest;
    private CloneProjectRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String project;
        private String version;
        private Boolean includeAcl;
        private Boolean includeAuditHistory;
        private Boolean includeComponents;
        private Boolean includeDependencies;
        private Boolean includePolicyViolations;
        private Boolean includeProperties;
        private Boolean includeServices;
        private Boolean includeTags;
        private Boolean makeCloneLatest;
        public Builder project(String value) { this.project = value; return this; }
        public Builder version(String value) { this.version = value; return this; }
        public Builder includeAcl(Boolean value) { this.includeAcl = value; return this; }
        public Builder includeAuditHistory(Boolean value) { this.includeAuditHistory = value; return this; }
        public Builder includeComponents(Boolean value) { this.includeComponents = value; return this; }
        public Builder includeDependencies(Boolean value) { this.includeDependencies = value; return this; }
        public Builder includePolicyViolations(Boolean value) { this.includePolicyViolations = value; return this; }
        public Builder includeProperties(Boolean value) { this.includeProperties = value; return this; }
        public Builder includeServices(Boolean value) { this.includeServices = value; return this; }
        public Builder includeTags(Boolean value) { this.includeTags = value; return this; }
        public Builder makeCloneLatest(Boolean value) { this.makeCloneLatest = value; return this; }
        public CloneProjectRequest build() {
            CloneProjectRequest result = new CloneProjectRequest();
            Validation.validateRequired("project", this.project);
            Validation.validatePattern("project", this.project, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
            result.project = this.project;
            Validation.validateRequired("version", this.version);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("version", this.version, __length); }
            result.version = this.version;
            result.includeAcl = this.includeAcl;
            result.includeAuditHistory = this.includeAuditHistory;
            result.includeComponents = this.includeComponents;
            result.includeDependencies = this.includeDependencies;
            result.includePolicyViolations = this.includePolicyViolations;
            result.includeProperties = this.includeProperties;
            result.includeServices = this.includeServices;
            result.includeTags = this.includeTags;
            result.makeCloneLatest = this.makeCloneLatest;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CloneProjectRequest{"
            + "project=" + project
            + ", version=" + version
            + ", includeAcl=" + includeAcl
            + ", includeAuditHistory=" + includeAuditHistory
            + ", includeComponents=" + includeComponents
            + ", includeDependencies=" + includeDependencies
            + ", includePolicyViolations=" + includePolicyViolations
            + ", includeProperties=" + includeProperties
            + ", includeServices=" + includeServices
            + ", includeTags=" + includeTags
            + ", makeCloneLatest=" + makeCloneLatest
            + "}";
    }
}
