// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

/**
 * Required enumerated value serialized in the `level` wire field.
 */
public final class CreateNotificationRuleRequestLevelEnum {
    public static final CreateNotificationRuleRequestLevelEnum INFORMATIONAL = new CreateNotificationRuleRequestLevelEnum("INFORMATIONAL");
    public static final CreateNotificationRuleRequestLevelEnum WARNING = new CreateNotificationRuleRequestLevelEnum("WARNING");
    public static final CreateNotificationRuleRequestLevelEnum ERROR = new CreateNotificationRuleRequestLevelEnum("ERROR");
    private final String value;
    private CreateNotificationRuleRequestLevelEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static CreateNotificationRuleRequestLevelEnum fromValue(String value) {
        if ("INFORMATIONAL".equals(value)) return INFORMATIONAL;
        if ("WARNING".equals(value)) return WARNING;
        if ("ERROR".equals(value)) return ERROR;
        return new CreateNotificationRuleRequestLevelEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof CreateNotificationRuleRequestLevelEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
