// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

/**
 * Required enumerated value serialized in the `level` wire field.
 */
public final class CreateScheduledNotificationRuleRequestLevelEnum {
    public static final CreateScheduledNotificationRuleRequestLevelEnum INFORMATIONAL = new CreateScheduledNotificationRuleRequestLevelEnum("INFORMATIONAL");
    public static final CreateScheduledNotificationRuleRequestLevelEnum WARNING = new CreateScheduledNotificationRuleRequestLevelEnum("WARNING");
    public static final CreateScheduledNotificationRuleRequestLevelEnum ERROR = new CreateScheduledNotificationRuleRequestLevelEnum("ERROR");
    private final String value;
    private CreateScheduledNotificationRuleRequestLevelEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static CreateScheduledNotificationRuleRequestLevelEnum fromValue(String value) {
        if ("INFORMATIONAL".equals(value)) return INFORMATIONAL;
        if ("WARNING".equals(value)) return WARNING;
        if ("ERROR".equals(value)) return ERROR;
        return new CreateScheduledNotificationRuleRequestLevelEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof CreateScheduledNotificationRuleRequestLevelEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
