// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

import dependencytrackunofficialsdk.Validation;

/**
 * CreateNotificationRuleRequest.
 * Typed representation of the `CreateNotificationRuleRequest` API schema.
 */

public final class CreateNotificationRuleRequest {
    /**
     * Required enumerated value serialized in the `level` wire field.
     */
    public CreateNotificationRuleRequestLevelEnum level;
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    /**
     * Required object value serialized in the `publisher` wire field.
     */
    public Publisher publisher;
    /**
     * Required enumerated value serialized in the `scope` wire field.
     */
    public CreateNotificationRuleRequestScopeEnum scope;
    private CreateNotificationRuleRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private CreateNotificationRuleRequestLevelEnum level;
        private String name;
        private Publisher publisher;
        private CreateNotificationRuleRequestScopeEnum scope;
        public Builder level(CreateNotificationRuleRequestLevelEnum value) { this.level = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder publisher(Publisher value) { this.publisher = value; return this; }
        public Builder scope(CreateNotificationRuleRequestScopeEnum value) { this.scope = value; return this; }
        public CreateNotificationRuleRequest build() {
            CreateNotificationRuleRequest result = new CreateNotificationRuleRequest();
            Validation.validateRequired("level", this.level);
            result.level = this.level;
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            Validation.validateRequired("publisher", this.publisher);
            result.publisher = this.publisher;
            Validation.validateRequired("scope", this.scope);
            result.scope = this.scope;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CreateNotificationRuleRequest{"
            + "level=" + level
            + ", name=" + name
            + ", publisher=" + publisher
            + ", scope=" + scope
            + "}";
    }
}
