// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

/**
 * Optional enumerated value serialized in the `notificationLevel` wire field.
 */
public final class NotificationRuleNotificationLevelEnum {
    public static final NotificationRuleNotificationLevelEnum INFORMATIONAL = new NotificationRuleNotificationLevelEnum("INFORMATIONAL");
    public static final NotificationRuleNotificationLevelEnum WARNING = new NotificationRuleNotificationLevelEnum("WARNING");
    public static final NotificationRuleNotificationLevelEnum ERROR = new NotificationRuleNotificationLevelEnum("ERROR");
    private final String value;
    private NotificationRuleNotificationLevelEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static NotificationRuleNotificationLevelEnum fromValue(String value) {
        if ("INFORMATIONAL".equals(value)) return INFORMATIONAL;
        if ("WARNING".equals(value)) return WARNING;
        if ("ERROR".equals(value)) return ERROR;
        return new NotificationRuleNotificationLevelEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof NotificationRuleNotificationLevelEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
