// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

/**
 * Required enumerated value serialized in the `scope` wire field.
 */
public final class NotificationRuleScopeEnum {
    public static final NotificationRuleScopeEnum SYSTEM = new NotificationRuleScopeEnum("SYSTEM");
    public static final NotificationRuleScopeEnum PORTFOLIO = new NotificationRuleScopeEnum("PORTFOLIO");
    private final String value;
    private NotificationRuleScopeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static NotificationRuleScopeEnum fromValue(String value) {
        if ("SYSTEM".equals(value)) return SYSTEM;
        if ("PORTFOLIO".equals(value)) return PORTFOLIO;
        return new NotificationRuleScopeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof NotificationRuleScopeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
