// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

/**
 * Required enumerated value serialized in the `triggerType` wire field.
 */
public final class NotificationRuleTriggerTypeEnum {
    public static final NotificationRuleTriggerTypeEnum EVENT = new NotificationRuleTriggerTypeEnum("EVENT");
    public static final NotificationRuleTriggerTypeEnum SCHEDULE = new NotificationRuleTriggerTypeEnum("SCHEDULE");
    private final String value;
    private NotificationRuleTriggerTypeEnum(String value) { this.value = java.util.Objects.requireNonNull(value, "value"); }
    @com.fasterxml.jackson.annotation.JsonCreator(mode = com.fasterxml.jackson.annotation.JsonCreator.Mode.DELEGATING)
    public static NotificationRuleTriggerTypeEnum fromValue(String value) {
        if ("EVENT".equals(value)) return EVENT;
        if ("SCHEDULE".equals(value)) return SCHEDULE;
        return new NotificationRuleTriggerTypeEnum(value);
    }
    @com.fasterxml.jackson.annotation.JsonValue public String getValue() { return value; }
    @java.lang.Override public String toString() { return value; }
    @java.lang.Override public boolean equals(Object other) {
        return this == other || (other instanceof NotificationRuleTriggerTypeEnum o && value.equals(o.value));
    }
    @java.lang.Override public int hashCode() { return value.hashCode(); }
}
