// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * NotificationPublisher.
 * Typed representation of the `NotificationPublisher` API schema.
 */

public final class NotificationPublisher {
    /**
     * Required `string` value serialized in the `extensionName` wire field.
     */
    public String extensionName;
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    /**
     * Required `string` value serialized in the `templateMimeType` wire field.
     */
    public String templateMimeType;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Optional `boolean` value serialized in the `defaultPublisher` wire field.
     */
    @Nullable public Boolean defaultPublisher;
    /**
     * Optional `string` value serialized in the `description` wire field.
     */
    @Nullable public String description;
    /**
     * Optional `string` value serialized in the `template` wire field.
     */
    @Nullable public String template;
    private NotificationPublisher() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String extensionName;
        private String name;
        private String templateMimeType;
        private String uuid;
        private Boolean defaultPublisher;
        private String description;
        private String template;
        public Builder extensionName(String value) { this.extensionName = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder templateMimeType(String value) { this.templateMimeType = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder defaultPublisher(Boolean value) { this.defaultPublisher = value; return this; }
        public Builder description(String value) { this.description = value; return this; }
        public Builder template(String value) { this.template = value; return this; }
        public NotificationPublisher build() {
            NotificationPublisher result = new NotificationPublisher();
            Validation.validateRequired("extensionName", this.extensionName);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 1024; Validation.validateLength("extensionName", this.extensionName, __length); }
            result.extensionName = this.extensionName;
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            Validation.validateRequired("templateMimeType", this.templateMimeType);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("templateMimeType", this.templateMimeType, __length); }
            result.templateMimeType = this.templateMimeType;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.defaultPublisher = this.defaultPublisher;
            if (this.description != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 1024; Validation.validateLength("description", this.description, __length); }
            }
            result.description = this.description;
            result.template = this.template;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "NotificationPublisher{"
            + "extensionName=" + extensionName
            + ", name=" + name
            + ", templateMimeType=" + templateMimeType
            + ", uuid=" + uuid
            + ", defaultPublisher=" + defaultPublisher
            + ", description=" + description
            + ", template=" + template
            + "}";
    }
}
