// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.notification;

import dependencytrackunofficialsdk.Validation;
import dependencytrackunofficialsdk.models.shared.Tag;
import java.util.List;
import javax.annotation.Nullable;

/**
 * UpdateNotificationRuleRequest.
 * Typed representation of the `UpdateNotificationRuleRequest` API schema.
 */

public final class UpdateNotificationRuleRequest {
    /**
     * Required enumerated value serialized in the `level` wire field.
     */
    public UpdateNotificationRuleRequestLevelEnum level;
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    public String name;
    /**
     * Required enumerated value serialized in the `scope` wire field.
     */
    public UpdateNotificationRuleRequestScopeEnum scope;
    /**
     * Required `uuid`-formatted value serialized in the `uuid` wire field.
     */
    public String uuid;
    /**
     * Optional `boolean` value serialized in the `enabled` wire field.
     */
    @Nullable public Boolean enabled;
    /**
     * Optional `string` value serialized in the `filterExpression` wire field.
     */
    @Nullable public String filterExpression;
    /**
     * Optional `boolean` value serialized in the `logSuccessfulPublish` wire field.
     */
    @Nullable public Boolean logSuccessfulPublish;
    /**
     * Optional `boolean` value serialized in the `notifyChildren` wire field.
     */
    @Nullable public Boolean notifyChildren;
    /**
     * Optional array value serialized in the `notifyOn` wire field.
     */
    @Nullable public List<UpdateNotificationRuleRequestNotifyOnItemEnum> notifyOn;
    /**
     * Optional `string` value serialized in the `publisherConfig` wire field.
     */
    @Nullable public String publisherConfig;
    /**
     * Optional `string` value serialized in the `scheduleCron` wire field.
     */
    @Nullable public String scheduleCron;
    /**
     * Optional `boolean` value serialized in the `scheduleSkipUnchanged` wire field.
     */
    @Nullable public Boolean scheduleSkipUnchanged;
    /**
     * Optional array value serialized in the `tags` wire field.
     */
    @Nullable public List<Tag> tags;
    private UpdateNotificationRuleRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private UpdateNotificationRuleRequestLevelEnum level;
        private String name;
        private UpdateNotificationRuleRequestScopeEnum scope;
        private String uuid;
        private Boolean enabled;
        private String filterExpression;
        private Boolean logSuccessfulPublish;
        private Boolean notifyChildren;
        private List<UpdateNotificationRuleRequestNotifyOnItemEnum> notifyOn;
        private String publisherConfig;
        private String scheduleCron;
        private Boolean scheduleSkipUnchanged;
        private List<Tag> tags;
        public Builder level(UpdateNotificationRuleRequestLevelEnum value) { this.level = value; return this; }
        public Builder name(String value) { this.name = value; return this; }
        public Builder scope(UpdateNotificationRuleRequestScopeEnum value) { this.scope = value; return this; }
        public Builder uuid(String value) { this.uuid = value; return this; }
        public Builder enabled(Boolean value) { this.enabled = value; return this; }
        public Builder filterExpression(String value) { this.filterExpression = value; return this; }
        public Builder logSuccessfulPublish(Boolean value) { this.logSuccessfulPublish = value; return this; }
        public Builder notifyChildren(Boolean value) { this.notifyChildren = value; return this; }
        public Builder notifyOn(List<UpdateNotificationRuleRequestNotifyOnItemEnum> value) { this.notifyOn = value; return this; }
        public Builder publisherConfig(String value) { this.publisherConfig = value; return this; }
        public Builder scheduleCron(String value) { this.scheduleCron = value; return this; }
        public Builder scheduleSkipUnchanged(Boolean value) { this.scheduleSkipUnchanged = value; return this; }
        public Builder tags(List<Tag> value) { this.tags = value; return this; }
        public UpdateNotificationRuleRequest build() {
            UpdateNotificationRuleRequest result = new UpdateNotificationRuleRequest();
            Validation.validateRequired("level", this.level);
            result.level = this.level;
            Validation.validateRequired("name", this.name);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; Validation.validateLength("name", this.name, __length); }
            result.name = this.name;
            Validation.validateRequired("scope", this.scope);
            result.scope = this.scope;
            Validation.validateRequired("uuid", this.uuid);
            Validation.validateUuid("uuid", this.uuid);
            result.uuid = this.uuid;
            result.enabled = this.enabled;
            if (this.filterExpression != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 2048; Validation.validateLength("filterExpression", this.filterExpression, __length); }
            }
            result.filterExpression = this.filterExpression;
            result.logSuccessfulPublish = this.logSuccessfulPublish;
            result.notifyChildren = this.notifyChildren;
            result.notifyOn = this.notifyOn;
            result.publisherConfig = this.publisherConfig;
            result.scheduleCron = this.scheduleCron;
            result.scheduleSkipUnchanged = this.scheduleSkipUnchanged;
            result.tags = this.tags;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "UpdateNotificationRuleRequest{"
            + "level=" + level
            + ", name=" + name
            + ", scope=" + scope
            + ", uuid=" + uuid
            + ", enabled=" + enabled
            + ", filterExpression=" + filterExpression
            + ", logSuccessfulPublish=" + logSuccessfulPublish
            + ", notifyChildren=" + notifyChildren
            + ", notifyOn=" + notifyOn
            + ", publisherConfig=" + publisherConfig
            + ", scheduleCron=" + scheduleCron
            + ", scheduleSkipUnchanged=" + scheduleSkipUnchanged
            + ", tags=" + tags
            + "}";
    }
}
