// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dependencytrackunofficialsdk.models.project_property;

import dependencytrackunofficialsdk.Validation;
import javax.annotation.Nullable;

/**
 * CreateProjectPropertyRequest.
 * Typed representation of the `CreateProjectPropertyRequest` API schema.
 */

public final class CreateProjectPropertyRequest {
    /**
     * Group the property belongs to
     */
    public String groupName;
    /**
     * Name of the property
     */
    public String propertyName;
    /**
     * Type of the property
     */
    public CreateProjectPropertyRequestPropertyTypeEnum propertyType;
    /**
     * Description of the property
     */
    @Nullable public String description;
    /**
     * Value of the property
     */
    @Nullable public String propertyValue;
    private CreateProjectPropertyRequest() {}
    public static Builder builder() { return new Builder(); }
    public static final class Builder {
        private String groupName;
        private String propertyName;
        private CreateProjectPropertyRequestPropertyTypeEnum propertyType;
        private String description;
        private String propertyValue;
        public Builder groupName(String value) { this.groupName = value; return this; }
        public Builder propertyName(String value) { this.propertyName = value; return this; }
        public Builder propertyType(CreateProjectPropertyRequestPropertyTypeEnum value) { this.propertyType = value; return this; }
        public Builder description(String value) { this.description = value; return this; }
        public Builder propertyValue(String value) { this.propertyValue = value; return this; }
        public CreateProjectPropertyRequest build() {
            CreateProjectPropertyRequest result = new CreateProjectPropertyRequest();
            Validation.validateRequired("groupName", this.groupName);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("groupName", this.groupName, __length); }
            Validation.validatePattern("groupName", this.groupName, "\\P{Cc}+");
            result.groupName = this.groupName;
            Validation.validateRequired("propertyName", this.propertyName);
            { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 1; __length.max = 255; Validation.validateLength("propertyName", this.propertyName, __length); }
            Validation.validatePattern("propertyName", this.propertyName, "\\P{Cc}+");
            result.propertyName = this.propertyName;
            Validation.validateRequired("propertyType", this.propertyType);
            result.propertyType = this.propertyType;
            if (this.description != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 255; Validation.validateLength("description", this.description, __length); }
                Validation.validatePattern("description", this.description, "\\P{Cc}+");
            }
            result.description = this.description;
            if (this.propertyValue != null) {
                { Validation.LengthOpts __length = new Validation.LengthOpts(); __length.min = 0; __length.max = 1024; Validation.validateLength("propertyValue", this.propertyValue, __length); }
                Validation.validatePattern("propertyValue", this.propertyValue, "\\P{Cc}+");
            }
            result.propertyValue = this.propertyValue;
            return result;
        }
    }
    @java.lang.Override
    public String toString() {
        return "CreateProjectPropertyRequest{"
            + "groupName=" + groupName
            + ", propertyName=" + propertyName
            + ", propertyType=" + propertyType
            + ", description=" + description
            + ", propertyValue=" + propertyValue
            + "}";
    }
}
